keycloak/keycloak-ui

- Gruntfile.js
- package.json
- yarn.lock
> added post install hook to copy fonts

- src/index.tsx
> setup i18n for the application

- package.json
- prettierrc.json
use settings file instead of command line
fixes: #8
> added prettierrc file

- src/App.tsx
- src/forms/realm/NewRealmForm.tsx
- stories/6-RealmForm.stories.js
Lay out the components for the New Realm form.
APPDUX-407, also issue #12
> [WIP] APPDUX-407 Lays out components for new realm form

- package.json
- snowpack.config.js
- src/App.tsx
- src/PageHeader.tsx
- src/PageNav.tsx
- src/components/realm-selector/RealmSelector.tsx
- src/forms/realm/NewRealmForm.tsx
- yarn.lock
Adds react-router to keycloak admin UI. 
To test, click on "Add Realm" button in the Realms dropdown. Realm form component should render in place of clients list.
> Add routing

- src/components/scroll-form/FormPanel.tsx
- src/components/scroll-form/ScrollForm.tsx
- src/components/scroll-form/form-panel.module.css
- src/components/scroll-form/scroll-form.module.css
- stories/4-ClientList.stories.js
- stories/5-AlertPanel.stories.js
- stories/7-ScrollSpy.stories.js
> Initial version of scrollable form panel

- babel.config.json
- package.json
- snowpack.config.js
- yarn.lock
> fixed build by changing it to webpack

- .github/workflows/node.js.yml
- package.json
- src/PageHeader.tsx
- src/PageNav.tsx
- src/__mocks__/fileMock.js
- src/auth/KeycloakContext.tsx
- src/auth/keycloak.service.ts
- src/auth/keycloak.ts
- src/clients/ClientList.test.tsx
- src/clients/ClientList.tsx
- src/components/alert/Alerts.test.tsx
- src/components/alert/Alerts.tsx
- src/components/alert/__snapshots__/Alerts.test.tsx.snap
- src/components/data-loader/DataLoader.tsx
- src/components/external-link/ExternalLink.tsx
- src/components/realm-selector/RealmSelector.tsx
- src/components/scroll-form/FormPanel.tsx
- src/components/scroll-form/ScrollForm.tsx
- src/components/table-toolbar/TableToolbar.tsx
- src/forms/realm/NewRealmForm.tsx
- src/http-service/HttpClientContext.tsx
- src/http-service/http-client.ts
- src/i18n.ts
- src/index.tsx
- src/util.ts
Added github actions to automate the build, test, and linting after a contributor checks in code.
This addresses Issue #15
> Added github actions to automate build, test, and linting

- src/App.tsx
- src/forms/client/ClientDescription.tsx
- src/forms/client/ImportForm.tsx
- src/forms/client/Step1.tsx
- src/messages.json
- src/page/ClientsPage.tsx
initial version of the import client json file
> Import client json file

- src/PageHeader.tsx
- src/components/help-enabler/HelpHeader.tsx
- src/components/help-enabler/__snapshots__/HelpHeader.test.tsx.snap
- src/components/help-enabler/help-header.module.css
This adjusts a few things on the toolbar help menu and kebab menu. It fixes alignment and spacing of icons and moves to use the DropdownItem description attribute for the descriptive text. The color of the descriptive text is manually styled pending a bug fix in Patternfly.
Related to comments in #30 as well as other discussions.
> Adjusts toolbar help menu items

- src/components/alert/__tests__/Alerts.test.tsx
- src/components/alert/__tests__/__snapshots__/Alerts.test.tsx.snap
@ssilvert when we talked about this also implemented it ;)
> small fix to make the alert test more readable

- .storybook/preview-head.html
- public/index.css
Adds PatternFly addons to the main CSS file and to storybook as well.
This allows us to use utility classes.
> adds patternfly addons

- src/groups/GroupsList.tsx
- src/groups/GroupsSection.tsx
- src/groups/models/groups.tsx
Couldn't help but create an initial version of this screen
> initial version of groups

- src/components/realm-selector/RealmSelector.tsx
- src/components/realm-selector/__tests__/__snapshots__/RealmSelector.test.tsx.snap
- src/components/realm-selector/realm-selector.css
> always show realm add button and filter on keystroke

- src/App.tsx
- src/PageHeader.tsx
- src/clients/__tests__/__snapshots__/ClientList.test.tsx.snap
- src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap
- src/components/realm-context/RealmContext.tsx
- src/components/realm-selector/RealmSelector.tsx
- src/components/realm-selector/__tests__/__snapshots__/RealmSelector.test.tsx.snap
- src/whoami/WhoAmI.tsx
- src/whoami/__tests__/WhoAmI.test.tsx
- src/whoami/__tests__/mock-whoami.json
- src/whoami/who-am-i-model.ts
WhoAmIContext provides a WhoAmI object from the server.  This provides things such as the proper display name of the user, whether the user is allowed to create new realms, and the realm that the user signed into.  It also sets the locale.
A subsequent PR will provide an AccessContext.  This will use the RealmAccess data from WhoAmI to provide permission checks.  This can not be done inside WhoAmIContext because we need to know the current realm and the RealmContext is not available yet (RealmContext uses home realm as initial realm, so we have a chicken and egg problem).
Eventually, App.tsx will look like this:
```
<Router>
<WhoAmIContextProvider>
<RealmContextProvider>
<AccessProvider>
{children}
</AccessProvider>
</RealmContextProvider>
</WhoAmIContextProvider>
</Router>
```
> Create whoami context

- src/App.tsx
- src/client-scopes/add/NewClientScopeForm.tsx
- src/clients/ClientList.tsx
- src/clients/ClientSettings.tsx
- src/clients/__tests__/__snapshots__/ClientList.test.tsx.snap
- src/clients/add/NewClientForm.tsx
- src/clients/import/ImportForm.tsx
- src/components/alert/Alerts.tsx
- src/components/alert/__tests__/Alerts.test.tsx
- src/components/alert/__tests__/__snapshots__/Alerts.test.tsx.snap
- src/realm-roles/add/NewRoleForm.tsx
- src/realm/add/NewRealmForm.tsx
- src/stories/AlertPanel.stories.tsx
> changed alerts to have a provider

- .github/workflows/node.js.yml
- CODING_GUIDELINES.md
- package.json
- src/components/download-dialog/DownloadDialog.tsx
Added coding standards and also updated the package json so that the scripts have consistent naming conventions.
Addresses issue #13
> Added coding standards to the project.

- CODE_OF_CONDUCT.md
Added code of conduct to the project.
> Added code of conduct to project.

- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/messages.json
- src/clients/ClientsSection.tsx
- src/common-messages.json
- src/components/data-loader/DataLoader.tsx
- src/components/table-toolbar/PaginatingTableToolbar.tsx
- src/components/table-toolbar/TableToolbar.tsx
- src/groups/GroupsList.tsx
- src/groups/GroupsSection.tsx
- src/realm-roles/RealmRolesSection.tsx
- src/realm-roles/messages.json
so introduced non paginating toolbar that can be used for pages like groups
> Some pages don't support pagination

- src/clients/add/NewClientForm.tsx
- src/clients/messages.json
> i18n keys for success and error message

- src/clients/ClientSettings.tsx
- src/clients/messages.json
- src/components/download-dialog/DownloadDialog.tsx
[marvel](https://marvelapp.com/prototype/908c3c3/screen/72040453)
> added download dialog to client actions

- src/context/auth/keycloak.ts
> introduced "/" for keycloak.json

- src/client-scopes/form/ClientScopeForm.tsx
> changed path

- src/client-scopes/form/ClientScopeForm.tsx
- src/util.ts
We are going to need this in multiple places better move it to this util
> moved workaround for dots in form names to util

- src/App.tsx
- src/ForbiddenSection.tsx
- src/PageNav.tsx
- src/context/access/Access.tsx
- src/context/whoami/WhoAmI.tsx
- src/context/whoami/who-am-i-model.ts
- src/route-config.ts
- Add access context
- Change left nav item from a function to a component
- Routes now specify access requirement and enforce access
> Implement basic access control.

- src/App.tsx
Navigation to deep links not working.
Added `exact` to routes.
Go to anyplace with a deep link such as client details screen.
> Fix exact routes

- src/groups/GroupsCreateModal.tsx
- src/groups/GroupsList.tsx
- src/groups/GroupsSection.tsx
- src/groups/messages.json
https://issues.redhat.com/browse/APPDUX-556
Add multi delete functionality from the toolbar
1. Go to Groups 
2. Select multiple table rows
3. Click on the top kebab and click 'delete'
4. This should delete all the table rows that were selected and refresh
5. Create a group and then try to delete multiple groups in different rows.
6. Delete a group from the table row and then try to delete multiple rows from toolbar.
> add multiple group delete functionality

- src/components/download-dialog/DownloadDialog.tsx
> only update snippet when component is mounted

- src/common-messages.json
- src/components/realm-selector/RealmSelector.tsx
- src/realm/add/NewRealmForm.tsx
Broken i18n.
Fixed i18n in two places of create realm process.
Create a realm and see fix.
> Cleanup create realm.

- src/client-scopes/form/ClientScopeForm.tsx
> removed placeholder value

- src/PageNav.tsx
- src/client-scopes/add/RoleMappingForm.tsx
- src/client-scopes/form/ClientScopeForm.tsx
- src/clients/ClientDescription.tsx
- src/common-messages.json
- src/context/whoami/WhoAmI.tsx
- src/groups/GroupsCreateModal.tsx
- src/realm-roles/add/NewRoleForm.tsx
This will make the fields look nicer / indicate there is an error
> added validated property to fields instead of only on FormGroup

- src/PageNav.tsx
This makes the transistion between sections a bit nicer
before:
after:
> make the part to update smaller

- src/App.tsx
- src/context/whoami/WhoAmI.tsx
- src/index.tsx
This avoids a circle dependency on realm
Currently changing realm on master is broken
This will fix that.
Create a new realm switch to this newly created realm
> changed how whoAmI uses the admin client

- src/client-scopes/details/MapperList.tsx
- src/client-scopes/details/MappingDetails.tsx
- src/client-scopes/messages.json
- src/components/bread-crumb/PageBreadCrumbs.tsx
- src/route-config.ts
added [this dialog](https://marvelapp.com/prototype/f0e8fih/screen/72041877) and put it so that when you press [this button](https://marvelapp.com/prototype/f0e8fih/screen/72041876) it pops up
> added by configuration dialog into the flow

- package.json
- src/user-federation/UserFederationSection.tsx
- yarn.lock
also fix name of project
made some small fixes to `keycloak-admin` that we need here.
> update to latest keycloak-admin

- src/clients/ClientDetails.tsx
Even though this didn't give any errors, it's not good practise to use hooks in a render
> removed inline created component

- src/context/auth/keycloak.ts
> fix for login on realm other then master

- src/clients/ClientDetails.tsx
- src/clients/ClientList.tsx
- src/clients/messages.json
- src/clients/service-account/ServiceAccount.tsx
- src/clients/service-account/service-account.css
- src/realm-roles/RoleList.tsx
- src/util.ts
Doesn't have any actions yet just the basic list with a toggle function. [marvel design](https://marvelapp.com/prototype/f058374/screen/71931942)
initial version of design
Go to client details when client is of type "service account" then you'll have an extra tab also called "service account"
> Initial version of the Service Account tab

- src/components/scroll-form/ScrollForm.tsx
Remove unused import.
Follow up on this comment: https://github.com/keycloak/keycloak-admin-ui/pull/246#pullrequestreview-545934239
> Remove useEffect import.

- src/clients/scopes/ClientScopes.tsx
added missing kebab menu seen here: https://marvelapp.com/prototype/f082f24/screen/71969035 in "D"
> added missing remove all kabab item

- src/user/UsersSection.tsx
- src/user/messages.json
with the new "DataList" (will change name in another PR) this user list is easy
See user section of the app now has a searchabe user list
> initial version of the user list

- package.json
- src/events/AdminEvents.tsx
- src/events/EventsSection.tsx
- src/events/messages.json
- yarn.lock
using the new list component quick implementation of the events tab list
new events tab
first go to the old console and turn on event logging then create some login event and failed login events
then check the events tab section to see these events.
> initial version of the events tab

- package.json
- src/user/UsersSection.tsx
- src/user/messages.json
- yarn.lock
update the admin client that has brute force endpoints added icon on the user list if temporary locked due brute force login attempt 
Create a new realm and enable brute force detection => Realm settings => security settings => Brute force Detection:
add a user and login wrong for "Max Login Failures"
Then go to the users section and see the temporary locked icon for that user.
> added brute login user temporary lock indication

- src/common-messages.json
- src/components/keycloak-card/KeycloakCard.tsx
- src/route-config.ts
- src/stories/UserFedLDAPSettingsTab.stories.tsx
- src/user-federation/UserFederationKerberosSettings.tsx
- src/user-federation/UserFederationLdapSettings.tsx
- src/user-federation/UserFederationSection.tsx
- src/user-federation/kerberos/KerberosSettingsCache.tsx
- src/user-federation/kerberos/KerberosSettingsRequired.tsx
- src/user-federation/ldap/LdapSettingsAdvanced.tsx
- src/user-federation/ldap/LdapSettingsCache.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/ldap/LdapSettingsGeneral.tsx
- src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
- src/user-federation/ldap/LdapSettingsSearching.tsx
- src/user-federation/ldap/LdapSettingsSynchronization.tsx
- src/user-federation/messages.json
Related JIRA issues:
https://issues.redhat.com/browse/APPDUX-655
Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72098368
Fetches and displays settings data for a specific individual LDAP provider card that is clicked in the user federation card view. 
This PR does not cover Save nor the showing/hiding of UI components based on selections. These will be handled in future PRs. This PR only covers pulling in the data and getting to the settings page from the cards.
1. Click an LDAP card in the user fed card view.
2. Verify that all settings match those that have been configured for that LDAP provider (presumably, the ones configured and saved in the old admin UI). There should be 7 sections: **General options**, **Connection and authentication settings**, **LDAP searching and …
> User Federation: populate all LDAP settings

- src/sessions/SessionsSection.tsx
- src/sessions/messages.json
[marvel app](https://marvelapp.com/prototype/5e9e849/screen/73427080)
Go to sessions
> initial version of the sessions section

- src/user-federation/kerberos/KerberosSettingsCache.tsx
- src/user-federation/kerberos/KerberosSettingsRequired.tsx
Show/hide controls correctly when cache policy dropdown is changed as well as some refactoring.
Verify that different controls are visible when you select a different cache policy.
> Show/hide Kerberos cache policy related controls

- src/client-scopes/add/RoleMappingForm.tsx
- src/client-scopes/details/MappingDetails.tsx
- src/client-scopes/form/ClientScopeForm.tsx
- src/clients/ClientDetails.tsx
- src/clients/credentials/Credentials.tsx
- src/clients/scopes/ClientScopes.tsx
- src/components/data-loader/DataLoader.tsx
- src/components/download-dialog/DownloadDialog.tsx
- src/components/scroll-form/ScrollForm.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/context/auth/AdminClient.tsx
- src/realm-roles/RealmRoleForm.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/RoleAttributes.tsx
- src/user-federation/UserFederationSection.tsx
- src/user-federation/kerberos/KerberosSettingsCache.tsx
- src/user-federation/ldap/LdapSettingsAdvanced.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/ldap/LdapSettingsGeneral.tsx
- src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
- src/user-federation/ldap/LdapSettingsSearching.tsx
- src/user-federation/ldap/LdapSettingsSynchronization.tsx
when the component is unmounted because we have navigated to another page we shouldn't update the state of this component anymore
> only update state when component is mounted

- src/groups/GroupsCreateModal.tsx
> onEnter should not post the form

- src/groups/GroupsSection.tsx
> refresh and message on group delete

- src/components/form-access/FormAccess.tsx
- src/components/form-access/__tests__/__snapshots__/FormAccess.test.tsx.snap
as before it would override an existing isDisabled
> only add isDisabled when needed otherwise

- src/clients/ClientsSection.tsx
- src/components/form-access/FormAccess.tsx
- src/components/realm-selector/RealmSelector.tsx
- src/i18n.ts
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/help.json
- src/realm-settings/messages.json
- src/util.ts
First tab of the realm section
Give all sections something to do, also makes the console more useable ;)
Go to there realm section, enable / disable / delete and save work. Partial export / imports don't
> initial version realm settings section

- src/client-scopes/form/ClientScopeForm.tsx
- src/clients/ClientDetails.tsx
- src/components/keycloak-tabs/KeycloakTabs.tsx
- src/events/EventsSection.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/route-config.ts
so we can bookmark the selected tab
Introduced a `KeycloakTabs` component that extends the PF `Tabs` that uses the react router to save it's state.
Click on any page that has tabs and see that the url reflects the selected tab.
> created bookmarkable tabs component

- src/authentication/AuthenticationSection.tsx
- src/components/work-in-progress/WorkInProgress.tsx
- src/components/work-in-progress/work-in-progress.css
- src/identity-providers/IdentityProvidersSection.tsx
Adds a iframe with the marvel app for sections that are not yet developed.
> added links to marvel for work in progress parts

- tests/cypress.json
Add retries to Cypress tests to fix some random load error from Cypress
> Add retries

- src/clients/scopes/EvaluateScopes.tsx
> override aria labels invalidly genrated by PF

- package.json
- src/authentication/AuthenticationSection.tsx
- src/authentication/DuplicateFlowModal.tsx
- src/authentication/authentication-section.css
- src/authentication/messages.json
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/i18n.ts
- yarn.lock
updated the admin client to support flows and excutions and implemented front sreeen [marvel](https://marvelapp.com/prototype/bh91013/screen/75647039)
First page with "delete" and "duplicate" functionality
> initial version of authentication section

- src/dashboard/Dashboard.tsx
- src/dashboard/messages.json
point 3 and 4 of #341 are fixed and capitalised the product name
> partially fixes 341

- src/clients/ClientDetails.tsx
> sort the role list alphabetically

- src/PageHeader.tsx
- src/common-messages.json
- src/dashboard/Dashboard.tsx
> toggle help on kebab click

- src/client-scopes/form/ClientScopeForm.tsx
- src/client-scopes/messages.json
> now validates if gui order is a number

- src/components/table-toolbar/PaginatingTableToolbar.tsx
> fixing round errors in paginating

- src/clients/ClientDescription.tsx
- src/clients/ClientsSection.tsx
- src/components/external-link/FormattedLink.tsx
- src/components/external-link/__tests__/__snapshots__/FormattedLink.test.tsx.snap
- src/components/table-toolbar/TableToolbar.tsx
- src/components/view-header/ViewHeader.tsx
- src/stories/FormattedLink.stories.tsx
> ux review fixes

- package.json
- src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap
- yarn.lock
Update Patternfly to the latest releases so we stay current with the latest changes.
As part of the Patternfly release process, I perform sanity tests of the new proposed versions on the keycloak admin UI and file issues as needed. This occurs about every 3 weeks. As part of that process, we should update keycloak to the latest versions on a regular cadence.
Use the keycloak admin UI and verify that no visual or behavioral issues have been introduced, and that there are no new console warnings/errors.
Testing on keycloak is complete and it passed. Keeping PR as draft until it passes from other projects and officially releases.
> Update to latest Patternfly releases

- src/user/messages.json
> fixed search text

- package.json
- src/App.tsx
- src/client-scopes/add/RoleMappingForm.tsx
- src/client-scopes/details/MappingDetails.tsx
- src/client-scopes/form/ClientScopeForm.tsx
- src/clients/ClientDetails.tsx
- src/clients/credentials/Credentials.tsx
- src/clients/scopes/ClientScopes.tsx
- src/clients/scopes/EvaluateScopes.tsx
- src/common-messages.json
- src/components/data-loader/DataLoader.tsx
- src/components/error/ErrorRenderer.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/context/auth/AdminClient.tsx
- src/context/whoami/WhoAmI.tsx
- src/realm-settings/RealmSettingsSection.tsx
- yarn.lock
by using this react-error-boundary package this works also in hooks
> created better error handling

- src/common-help.json
- src/components/help-enabler/HelpHeader.tsx
- src/components/help-enabler/__tests__/__snapshots__/HelpHeader.test.tsx.snap
- src/components/help-enabler/help-header.css
> updated to match ui design

- src/clients/ClientDetails.tsx
- src/clients/ClientSettings.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/help.json
- src/clients/messages.json
- src/clients/scopes/EvaluateScopes.tsx
fixes 3 issues on the client detail page
* #386
* #377
See issues
> Fix some issues on client detail page

- src/PageNav.tsx
> remain active on child pages of main section

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- src/clients/ClientsSection.tsx
see: https://github.com/keycloak/keycloak-admin-ui/issues/352#issuecomment-788677779
> added space between buttons

- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/add/RoleMappingForm.tsx
- src/client-scopes/details/MapperList.tsx
- src/client-scopes/details/MappingDetails.tsx
- src/clients/ClientDetails.tsx
- src/clients/ClientsSection.tsx
- src/clients/add/NewClientForm.tsx
- src/components/bread-crumb/__tests__/PageBreadCrumbs.test.tsx
- src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap
- src/components/keycloak-tabs/KeycloakTabs.tsx
- src/realm-roles/RolesList.tsx
- src/route-config.ts
the bookmarkable subtab made the navigation between tabs strange so removed that feature
fixes: #404
See issue
> removed bookmarable sub tab

- src/components/multi-line-input/MultiLineInput.tsx
- src/components/table-toolbar/PaginatingTableToolbar.tsx
- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm/add/NewRealmForm.tsx
- src/user-federation/UserFederationLdapWizard.tsx
use === instead of == and unused imports
> Fixed some warnings

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/manage/groups/GroupDetailPage.ts
- cypress/support/util/AdminClient.ts
- src/App.tsx
- src/components/attribute-form/AttributeForm.tsx
- src/components/attribute-form/attribute-form.css
- src/components/bread-crumb/GroupBreadCrumbs.tsx
- src/components/bread-crumb/__tests__/GroupBreadCrumbs.test.tsx
- src/groups/GroupAttributes.tsx
- src/groups/GroupTable.tsx
- src/groups/GroupsSection.tsx
- src/groups/Members.tsx
- src/groups/SubGroupsContext.tsx
- src/groups/groupIdUtils.ts
- src/groups/messages.json
- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/RealmRolesSection.css
Added the group details to the group section
Go to the groups section create a couple of groups click on the group see the new group details
> Group details

- src/clients/initial-access/CreateInitialAccessToken.tsx
- src/clients/initial-access/InitialAccessTokenList.tsx
- src/clients/messages.json
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/components/time-selector/TimeSelector.tsx
> changed time select order + added success message

- src/client-scopes/details/MapperList.tsx
- src/clients/scopes/ClientScopes.tsx
- src/clients/service-account/ServiceAccount.tsx
- src/route-config.ts
so it will benifid from a general way tables work in the admin console
> changed to use the keycloak datatable

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- nginx-default.conf
- security-admin-console-v2-combined.json
Adding `Dockerfile` and `docker-compose.yml` for ready-to-use local build for all the not-frontend-proficient folks like me 😄 
docker-compose build
docker-compose up -d 
Access http://localhost:8080/adminv2
> add Docker and docker-compose

- src/components/attribute-form/AttributeForm.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
Towards #416 
1. Go to Realm Roles section.
2. Click on a role. 
3. Add a few associated roles.
4. Verify that the roles are alphabetized. 
5. Search for a particular associated role in the search input field. 
6. Click the search button and verify that filtering works as expected.
7. Go to Role Attributes. 
8. Verify it matches the new design: https://marvelapp.com/prototype/6j3ecj2/screen/77563386, and adding/saving attributes works as expected
> roles(associated roles+attributes): address UX feedback

- src/components/table-toolbar/KeycloakDataTable.tsx
even when the backend doesn't support pagination we still show paginated results
> adds fake pagination to datatable

- src/groups/GroupsModal.tsx
> add missing cancel button

- src/realm-roles/AssociatedRolesTab.tsx
You don't need to filter yourself this is taken care of in the `KeycloakDataTable`
> small refactor

- src/groups/MembersModal.tsx
> use diff instead of xor

- src/clients/add/GeneralSettings.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/help.json
- src/clients/messages.json
changed to be progressive added help to type
and made `openid-connect` the default
fixes: #446
> new client wizard uxd review

- src/client-scopes/details/MapperList.tsx
- src/client-scopes/details/MappingDetails.tsx
- src/route-config.ts
> fixed urls

- src/components/table-toolbar/KeycloakDataTable.tsx
- src/components/table-toolbar/PaginatingTableToolbar.tsx
> added `isRowDisabled` function to disble rows

- src/client-scopes/ClientScopesSection.tsx
> give protocol a bit more width

- src/clients/ClientSettings.tsx
- src/clients/advanced/SaveReset.tsx
Some how the floating action buttons on the client detail screen have disappeared again just added the for the second time
> re added floating action

- src/clients/ClientDetails.tsx
- src/clients/add/CapabilityConfig.tsx
- src/clients/add/NewClientForm.tsx
> public client = false when clientAuthentication

- src/clients/ClientDetails.tsx
- src/clients/messages.json
- src/clients/scopes/AddScopeDialog.tsx
- src/clients/scopes/ClientScopes.tsx
- src/clients/scopes/client-scopes.css
- src/components/table-toolbar/KeycloakDataTable.tsx
> fixing uxd issues

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/manage/groups/MoveGroupModal.ts
- src/groups/GroupTable.tsx
- src/groups/MoveGroupDialog.tsx
- src/groups/messages.json
disabled "Move" button on root level
fixing: #476
> can't move groups to the root level

- src/App.tsx
- src/PageNav.tsx
- src/common-messages.json
- src/components/realm-selector/RealmSelector.tsx
- src/components/realm-selector/recent-used.ts
- src/context/realm-context/RealmContext.tsx
> added recently used realms to the top

- src/clients/service-account/AddServiceAccountModal.tsx
> disable when nothing selected

- src/clients/ClientDetails.tsx
> move back to list on delete

- src/client-scopes/form/ClientScopeForm.tsx
> added max length check

- src/clients/add/CapabilityConfig.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/help.json
- src/clients/messages.json
fixing issue on merged PR: https://github.com/keycloak/keycloak-admin-ui/pull/474#issuecomment-817620993
> more help items and small linout

- src/clients/AdvancedTab.tsx
> protocol can be not set

- src/clients/AdvancedTab.tsx
fixing issue comment
https://github.com/keycloak/keycloak-admin-ui/issues/422#issuecomment-815421080
> removed top margin

- src/authentication/DuplicateFlowModal.tsx
- src/client-scopes/ChangeTypeDialog.tsx
- src/client-scopes/add/MapperDialog.tsx
- src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap
- src/clients/advanced/AddHostDialog.tsx
- src/clients/scopes/AddScopeDialog.tsx
- src/groups/GroupsModal.tsx
- src/groups/MembersModal.tsx
- src/groups/MoveGroupDialog.tsx
> changed all cancel buttons to type "link"

- src/events/AdminEvents.tsx
- src/user/UsersSection.tsx
- src/user/UsersTabs.tsx
> fixing issues defined in 510

- src/clients/scopes/EvaluateScopes.tsx
- src/components/help-enabler/HelpItem.tsx
> added unwrap so that HelpItem can be on a button

- src/components/table-toolbar/KeycloakDataTable.tsx
- src/components/view-header/ViewHeader.tsx
- src/events/AdminEvents.tsx
- src/events/EventsSection.tsx
- src/events/events-section.css
- src/events/messages.json
- src/realm-roles/RolesList.tsx
> fixing UXD review issue

- src/clients/AdvancedTab.tsx
- src/clients/ClientSettings.tsx
- src/clients/credentials/Credentials.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/428#issuecomment-818504696
> fixing comment on issue:

- cypress/integration/users_test.spec.ts
- cypress/support/pages/admin_console/manage/users/CreateUserPage.ts
- cypress/support/pages/admin_console/manage/users/UserGroupsPage.ts
- src/user/JoinGroupDialog.tsx
- src/user/UserForm.tsx
- src/user/UserGroups.tsx
- src/user/UsersTabs.tsx
- src/user/messages.json
- src/user/user-section.css
https://issues.redhat.com/browse/APPDUX-912
1. Go to Users section. 
2. Click "Add user"
3. Create the new user and add groups to the user within the form.
4. Verify that groups selected show up in the "Groups" tab once the user is created.
> Users(Create user form): Update create user form with new design

- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/AssociatedRolesTab.tsx
Data list cells of associated roles should not be links
Before:
After:
> Fix associated roles list 

- .gitignore
- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/manage/clients/KeysTab.ts
- package.json
- src/clients/ClientDetails.tsx
- src/clients/help.json
- src/clients/keys/GenerateKeyDialog.tsx
- src/clients/keys/ImportKeyDialog.tsx
- src/clients/keys/Keys.tsx
- src/clients/keys/StoreSettings.tsx
- src/clients/messages.json
- src/common-help.json
- src/components/password-input/PasswordInput.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- yarn.lock
Implementation of the [keys tab](https://marvelapp.com/prototype/913a02j/screen/72334850) without changing the backend
> added keys tab to client details

- .github/workflows/cypress.yml
- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/integration/group_test.spec.ts
- cypress/integration/identity_providers.spec.ts
- cypress/integration/realm_settings_test.spec.ts
- cypress/integration/realm_test.spec.ts
- cypress/integration/users_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/SidebarPage.ts
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
- cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- cypress/support/pages/admin_console/manage/groups/GroupModal.ts
- cypress/support/pages/admin_console/manage/groups/MoveGroupModal.ts
- cypress/support/util/AdminClient.ts
- package.json
- src/components/realm-selector/realm-selector.css
- yarn.lock
Seems like the cypress tests where not running on the PRs and where broken for a while, this PR fixes that
> Fixing cypress tests

- src/realm-roles/UsersInRoleTab.tsx
> fixed undefined

- cypress/integration/identity_providers.spec.ts
- cypress/support/pages/admin_console/SidebarPage.ts
- cypress/support/pages/admin_console/manage/identity_providers/CreateProviderPage.ts
Fixes the identity provider cypress tests.
Allows the cypress tests to work without failures.
Run the identity providers cypress tests locally, or wait for CI to process them.
N/A
> fixes identity provider cypress tests

- src/App.tsx
- src/sessions/SessionsSection.tsx
this makes the ids unique so that they only get queried once
> only query each client session once

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/groups/GroupTable.tsx
- src/groups/GroupsSection.tsx
- src/groups/Members.tsx
- src/groups/SubGroupsContext.tsx
instead of static waiting wait for the memeber query to finish
> using smarter wait to fix group tests

- src/components/realm-selector/RealmSelector.tsx
> filter recent used realms as well as others

- src/identity-providers/add/DiscoverySettings.tsx
- src/identity-providers/add/discovery-settings.css
- src/identity-providers/component/SwitchField.tsx
> fixing issues described in 595

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/manage/groups/GroupModal.ts
- cypress/support/pages/admin_console/manage/groups/MoveGroupModal.ts
added more waits and a check to see if the loading spinner is gone.
> try and fix group tests again

- src/realm-settings/GeneralTab.tsx
- src/realm-settings/messages.json
> fixed name

- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/details/ScopeForm.tsx
- src/client-scopes/form/ClientScopeForm.tsx
- src/client-scopes/help.json
- src/client-scopes/messages.json
- src/components/client-scope/ClientScopeTypes.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/route-config.ts
* Removed divider
* Adding type field
* Hide "Consent screen text" field when display consent screen is off
* Fixed cancel button
fixing: #470
> Fixing UXD design review

- src/clients/credentials/SignedJWT.tsx
- src/clients/credentials/X509.tsx
- src/clients/messages.json
- src/common-messages.json
- src/components/keycloak-tabs/KeycloakTabs.tsx
- src/components/multi-line-input/MultiLineInput.tsx
- src/components/scroll-form/ScrollForm.tsx
> fixing the remainder of issue 428

- src/realm-settings/KeysProvidersTab.tsx
- src/realm-settings/LoginTab.tsx
- src/realm-settings/RealmSettingsSection.css
Closes #630 
Padding/margin alignment now matches mock (see #630)
1. Go to Clients -> Advanced
2. Verify the cards/form panels are aligned appropriately.
> Fixes form panel styling in clients -> advanced tab

- src/realm-settings/EmailTab.tsx
- src/realm-settings/KeysListTab.tsx
- src/realm-settings/KeysProvidersTab.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/help.json
currently save on realm screen didn't work as the email settings where required. Fixed this by changing email to be it's own section. Also email section was using the wrong attributes therefor the changes where not reflected in the old console
> fixes realm save

- public/index.css
- src/clients/advanced/SaveReset.tsx
> fixed type of save button

- cypress/integration/client_scopes_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- src/client-scopes/ClientScopesSection.tsx
Added a wait for the loading to be done just like on the group test
> makes client scope test more reliable

- src/realm-settings/ThemesTab.tsx
Towards #637 
Toggle remains open to support multi select
> Fix supported locales toggle

- src/user/UsersTabs.tsx
> fixed issue + small layout of page

- src/clients/import/ImportForm.tsx
- src/components/json-file-upload/JsonFileUpload.tsx
- src/components/json-file-upload/__tests__/__snapshots__/JsonFileUpload.test.tsx.snap
- src/identity-providers/add/OpenIdConnectSettings.tsx
- src/realm-settings/PartialImport.tsx
- src/realm/add/NewRealmForm.tsx
> fixes issue around importing files

- src/components/realm-selector/RealmSelector.tsx
- src/components/realm-selector/realm-selector.css
- src/components/realm-selector/recent-used.ts
https://github.com/keycloak/keycloak-admin-ui/issues/396#issuecomment-846901717
> fixing issue comment:

- src/client-scopes/details/ScopeForm.tsx
- src/client-scopes/form/ClientScopeForm.tsx
comments C and D on issue: #469
fixes: #469
> fixed default value and link to settings on create

- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/messages.json
@jenny-s51 already did some of the things in this issue...
> fixing issue 416

- src/client-scopes/details/ScopeForm.tsx
- src/client-scopes/form/ClientScopeForm.tsx
see: https://github.com/keycloak/keycloak-admin-ui/pull/657#issuecomment-857488393
> Fixed issue comment on PR

- package.json
Minor changes to package.json.  Interestingly, all this time the license statement in package.json didn't match the LICENSE file and nobody noticed.
> Prepare for first alpha release

- README.md
- cypress/integration/realm_roles_test.spec.ts
Test works locally, but not in CI.  See issue #713
> Comment out Realm role CRUD test

- src/components/group/GroupPath.tsx
- src/groups/Members.tsx
- src/groups/SearchGroups.tsx
- src/user/UserGroups.tsx
> fixing issue

- package.json
- src/realm-settings/EmailTab.tsx
- src/realm-settings/LocalizationTab.tsx
- yarn.lock
the new admin client supports these endpoints now
* test smtp settings - email
* localisation support
To test see email setting under realm and localisation
> updated admin client with new endpoints

- public/index.css
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/user/UserGroups.tsx
- src/user/UsersSection.tsx
- src/user/UsersTabs.tsx
- src/user/user-section.css
> fixed issue

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/manage/groups/GroupModal.ts
- cypress/support/pages/admin_console/manage/groups/MoveGroupModal.ts
- src/groups/GroupTable.tsx
The member count was a very intensive query at best and not do-able for other storage providers. So we decided to remove it.
> removed member count column

- src/components/alert/AlertPanel.tsx
- src/components/alert/Alerts.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/realm-settings/KeysListTab.tsx
* removed double loading indicator
* fix order of alerts where the newest is on the top
> Fixed these 2 issues:

- src/realm-settings/KeysProvidersTab.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/746.
View realm settings and verify that the console error no longer appears.
The realm settings cypress tests that were failing may want to be re-investigated as this may have been the culprit.
> Fix realm settings console error

- package.json
- src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap
- src/components/alert/__tests__/__snapshots__/Alerts.test.tsx.snap
- src/components/confirm-dialog/__tests__/__snapshots__/ConfirmDialog.test.tsx.snap
- src/components/json-file-upload/__tests__/__snapshots__/JsonFileUpload.test.tsx.snap
- yarn.lock
Update Patternfly to the latest releases so we stay current with the latest changes.
As part of the Patternfly release process, I perform sanity tests of the new proposed versions on the keycloak admin UI and file issues as needed. This occurs about every 3 weeks. As part of that process, we should update keycloak to the latest versions on a regular cadence.
Use the keycloak admin UI and verify that no visual or behavioral issues have been introduced, and that there are no new console warnings/errors.
None
> Update to Patternfly 4.115.2 (latest release)

- package.json
> bumped babel-core dependency to 7.11.5

- src/components/group/GroupPickerDialog.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/groups/GroupTable.tsx
- src/user/UserForm.tsx
- src/user/user-section.css
Now follows the design more closely
> Changed the group picker to reflect the updated design

- .storybook/main.js
- package.json
- yarn.lock
Required for #805 as it's not allowed to have multiple dependencies of different versions in NPM v7.
> Use WebPack 5 for Storybook builds

- .github/workflows/cypress.yml
- cypress.json
- Disable uploads for videos of tests that have passed
- Disable compression of videos to speed up runs
> Optimize performance of Cypress tests on CI

- src/clients/ClientSettings.tsx
- src/clients/add/CapabilityConfig.tsx
- src/clients/add/GeneralSettings.tsx
- src/components/list-empty-state/ListEmptyState.tsx
- src/components/multi-line-input/MultiLineInput.tsx
- src/components/scroll-form/ScrollPanel.tsx
- src/dashboard/Dashboard.tsx
Reverts keycloak/keycloak-admin-ui#813
> Revert "Ay11"

- src/clients/ClientSettings.tsx
- src/clients/add/CapabilityConfig.tsx
- src/clients/add/GeneralSettings.tsx
- src/components/list-empty-state/ListEmptyState.tsx
- src/components/multi-line-input/MultiLineInput.tsx
- src/components/scroll-form/ScrollPanel.tsx
- src/dashboard/Dashboard.tsx
> added accessibility fixes

- src/client-scopes/details/ScopeForm.tsx
- src/clients/AdvancedTab.tsx
- src/clients/advanced/AdvancedSettings.tsx
- src/clients/advanced/AuthenticationOverrides.tsx
- src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
- src/clients/keys/Keys.tsx
- src/components/scroll-form/FormPanel.tsx
- src/components/time-selector/TimeSelector.tsx
- src/groups/GroupsModal.tsx
- src/identity-providers/icons/FontAwesomeIcon.tsx
- src/realm-roles/RealmRoleForm.tsx
- src/realm-settings/EmailTab.tsx
- src/realm-settings/GeneralTab.tsx
- src/realm-settings/LoginTab.tsx
- src/realm-settings/event-config/EventConfigForm.tsx
- src/realm-settings/event-config/EventsTab.tsx
- src/user/UserForm.tsx
Fixing accessibility issues
Accessibility fixes
Using deque's DevTools the following screens can be verified. Below attached are before and after screenshots:
Clients keys tab
Clients create role tab
Clients advanced tab
Client scopes
Users create
Create group
Realm settings general tab
Real settings login tab
Realm settings email tab
Realm settings events tab
Identity providers
> Accessibility more fixes

- src/index.tsx
This change enables [Strict Mode](https://reactjs.org/docs/strict-mode.html), which activates additional checks and warnings for React.
> Enable Strict Mode for React

- build/pom.xml
- src/PageHeader.tsx
- src/context/auth/keycloak.ts
- src/context/realm-context/RealmContext.tsx
- src/context/whoami/WhoAmI.tsx
- src/context/whoami/__tests__/WhoAmI.test.tsx
- src/dashboard/Dashboard.tsx
- src/environment.ts
- src/util.ts
Prevents having to use global variables for environment variables injected by running the application as a Keycloak theme.
> Parse environment information as JSON

- start.js
This reverts commit d67b37e48e144f3e3479a19e6e6c14351a958f10.
Breaks the tests, we have to take a better look at this.
> Revert "Update development Keycloak server to version 14 (#853)"

- package-lock.json
- package.json
Looks like I missed these in the Snowpack 3 upgrade.
> Update Snowpack and related dependencies to latest version

- cypress/support/pages/admin_console/ListingPage.ts
- src/clients/AdvancedTab.tsx
- src/clients/ClientDetails.tsx
- src/clients/ClientsSection.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/import/ImportForm.tsx
- src/clients/initial-access/CreateInitialAccessToken.tsx
- src/clients/initial-access/InitialAccessTokenList.tsx
- src/clients/routes.ts
- src/clients/routes/AddClient.ts
- src/clients/routes/Client.ts
- src/clients/routes/Clients.ts
- src/clients/routes/CreateInitialAccessToken.ts
- src/clients/routes/ImportClient.ts
- src/route-config.ts
Aligns the routing for client routes with the conventions as discussed in the team meeting.
> Use new routing conventions for client routes

- src/PageNav.tsx
- src/components/realm-selector/RealmSelector.tsx
- src/realm/routes.ts
- src/realm/routes/AddRealm.ts
- src/route-config.ts
Aligns the routing for client realm with the conventions as discussed in the team meeting.
> Use new routing conventions for realm routes

- src/authentication/routes.ts
- src/authentication/routes/Authentication.ts
- src/route-config.ts
Aligns the routing for authentication with the conventions as discussed in the team meeting.
> Use new routing conventions for authentication routes

- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/routes.ts
- src/client-scopes/routes/ClientScope.ts
- src/client-scopes/routes/ClientScopes.ts
- src/client-scopes/routes/Mapper.ts
- src/client-scopes/routes/NewClientScope.ts
- src/client-scopes/routes/OidcRoleNameMapper.ts
- src/route-config.ts
Aligns the routing for client scope with the conventions as discussed in the team meeting.
> Use new routing conventions for client scope routes

- src/realm-roles/routes.ts
- src/realm-roles/routes/AddRole.ts
- src/realm-roles/routes/AddRoleToClient.ts
- src/realm-roles/routes/ClientRole.ts
- src/realm-roles/routes/RealmRole.ts
- src/realm-roles/routes/RealmRoles.ts
- src/route-config.ts
Aligns the routing for realm role with the conventions as discussed in the team meeting.
> Use new routing conventions for realm role routes

- CODING_GUIDELINES.md
Also removes sections from the guidelines that are already documented in the React TypeScript Cheat sheet.
Aligns with what was agreed during the team meeting.
> Add section to code guidelines about non-null assertions

- src/route-config.ts
- src/user/routes.ts
- src/user/routes/AddUser.ts
- src/user/routes/User.ts
- src/user/routes/Users.ts
Aligns the routing for user routes with the conventions as discussed in the team meeting.
> Use new routing conventions for user routes

- cypress/integration/realm_roles_test.spec.ts
- cypress/integration/realm_settings_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
Added some waits instead of timeouts waiting for backend loads to take place, this will hopefully fix these tests :)
> better waits for realm role tests

- src/events/routes.ts
- src/events/routes/Events.ts
- src/route-config.ts
Aligns the routing for event routes with the conventions as discussed in the team meetingoutput.
> Use new routing conventions for event routes

- src/realm-settings/routes.ts
- src/realm-settings/routes/AesGeneratedSettings.ts
- src/realm-settings/routes/EcdsaGeneratedSettings.ts
- src/realm-settings/routes/HmacGeneratedSettings.ts
- src/realm-settings/routes/JavaKeystoreSettings.ts
- src/realm-settings/routes/RealmSettings.ts
- src/realm-settings/routes/RsaGeneratedSettings.ts
- src/realm-settings/routes/RsaSettings.ts
- src/route-config.ts
Aligns the routing for realm setting routes with the conventions as discussed in the team meetingoutput.
> Use new routing conventions for realm settings

- src/identity-providers/routes.ts
- src/identity-providers/routes/IdentityProvider.ts
- src/identity-providers/routes/IdentityProviderKeycloakOidc.ts
- src/identity-providers/routes/IdentityProviderOidc.ts
- src/identity-providers/routes/IdentityProviderTab.ts
- src/identity-providers/routes/IdentityProviders.ts
- src/route-config.ts
Aligns the routing for identity provider routes with the conventions as discussed in the team meeting.
> Use new routing conventions for identity provider routes

- src/route-config.ts
- src/user-federation/routes.ts
- src/user-federation/routes/NewKerberosUserFederation.ts
- src/user-federation/routes/NewLdapUserFederation.ts
- src/user-federation/routes/UserFederation.ts
- src/user-federation/routes/UserFederationKerberos.ts
- src/user-federation/routes/UserFederationLdap.ts
- src/user-federation/routes/UserFederationLdapMapper.ts
- src/user-federation/routes/UserFederationsKerberos.ts
- src/user-federation/routes/UserFederationsLdap.ts
Aligns the routing for user federation routes with the conventions as discussed in the team meeting.
> Use new routing conventions for user federation routes

- src/dashboard/routes.ts
- src/dashboard/routes/Dashboard.ts
- src/route-config.ts
Aligns the routing for dashboard routes with the conventions as discussed in the team meeting.
> Use new routing conventions for dashboard routes 

- src/groups/routes.ts
- src/groups/routes/Groups.tsx
- src/groups/routes/GroupsSearch.tsx
- src/route-config.ts
Aligns the routing for groups routes with the conventions as discussed in the team meeting.
> Use new routing conventions for groups routes

- .eslintrc.js
- src/client-scopes/ClientScopesSection.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/scopes/ClientScopes.tsx
- src/components/group/GroupPath.tsx
- src/identity-providers/IdentityProvidersSection.tsx
- src/realm-settings/KeysListTab.tsx
- src/user-federation/UserFederationLdapWizard.tsx
- src/user/UserConsents.tsx
A leftover from trying to align our ESlint config with the recommended config from our plugins.
> Enable 'no-empty-function' ESlint rule

- .github/issue_template.md
> Add issue template to inform new contributors

- .github/workflows/cypress.yml
- cypress/integration/identity_providers.spec.ts
- cypress/support/index.js
- cypress/support/util/AdminClient.ts
- docker-compose.yml
Allows us to run the tests against the final product instead of our own dev server.
> Run Cypress tests on Keycloak theme

- src/components/download-dialog/DownloadDialog.tsx
> Hide details when adaptor config is download-only

- src/components/download-dialog/DownloadDialog.tsx
Addresses @yih-wang's feedback in #538
> Process UX feedback for DownloadDialog

- src/components/download-dialog/DownloadDialog.tsx
Fixes dropdown positioning mentioned in https://github.com/keycloak/keycloak-admin-ui/issues/538#issuecomment-893099974
> Place dropdown over DownloadDialog

- package-lock.json
- package.json
Update Patternfly to the latest releases so we stay current with the latest changes.
As part of the Patternfly release process, I perform sanity tests of the new proposed versions on the keycloak admin UI and file issues as needed. This occurs about every 3 weeks. As part of that process, we should update keycloak to the latest versions on a regular cadence.
Use the keycloak admin UI and verify that no visual or behavioral issues have been introduced, and that there are no new console warnings/errors.
In addition to manual sanity testing, the full cypress test suite was run and no new failures occurred as a result of the PF upgrade.
> Update to Patternfly 4.125.3 (latest release)

- cypress/integration/client_scopes_test.spec.ts
> re-enable crud test

- src/clients/ClientSettings.tsx
> make general settings the first item

- src/App.tsx
- src/PageNav.tsx
- src/realm-roles/routes/RealmRole.ts
- src/route-config.ts
> Allow multiple access for secured routes

- src/components/attribute-form/AttributeForm.tsx
- src/groups/GroupTable.tsx
> disable save when there are no changes

- .eslintrc.js
- src/realm-roles/RolesList.tsx
> changed render of link so search can find the text

- src/clients/advanced/AdvancedSettings.tsx
- src/clients/advanced/TokenLifespan.tsx
- src/clients/messages.ts
> added component to set lifespan of token

- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
> added test for adding service account role

- src/PageHeader.tsx
- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/details/MapperList.tsx
- src/client-scopes/routes/ClientScope.ts
- src/events/EventsSection.tsx
- src/groups/Members.tsx
- src/realm-roles/RolesList.tsx
- src/realm-roles/routes/RealmRole.ts
- src/realm-settings/RealmSettingsSection.tsx
- src/user/UsersSection.tsx
- src/user/routes/User.ts
> Convert more links to use new routes

- Dockerfile
- start.mjs
Keeps us up to date with the latest and greatest.
> Update Keycloak to version 15.0.1

- src/user-federation/ldap/LdapSettingsConnection.tsx
> Use correct default for 'Truststore SPI'

- src/clients/import/ImportForm.tsx
> keep imported json instead of only form fields

- src/realm-settings/LocalizationTab.tsx
using the proxy for local dev this call fails so added
try catch so you can still access the screen
> added try catch as this call fails locally

- src/clients/advanced/AdvancedSettings.tsx
- src/clients/advanced/AuthenticationOverrides.tsx
- src/clients/advanced/FineGrainOpenIdConnect.tsx
- src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
> changed save buttons from `tertiary` to `secondary`

- src/clients/advanced/TokenLifespan.tsx
- src/components/time-selector/TimeSelector.tsx
> fixed focus and min value

- src/components/bread-crumb/GroupBreadCrumbs.tsx
- src/groups/SearchGroups.tsx
> fixed breadcrumb for search and seach box distance

- package-lock.json
Fixes the reported CVEs from `npm audit`
> Fix CVEs from NPM audit

- src/client-scopes/ClientScopesSection.tsx
- src/client-scopes/details/ScopeForm.tsx
- src/client-scopes/messages.ts
> Process UXD review for Client Scopes

- Dockerfile
- start.mjs
Keeps us up-to-date with the latest and greatest.
> Update Keycloak to version 15.0.2

- src/realm-settings/JavaKeystoreModal.tsx
- src/realm-settings/KeysProvidersTab.tsx
- src/realm-settings/RSAGeneratedModal.tsx
- src/realm-settings/RSAModal.tsx
- src/realm-settings/RealmSettingsSection.css
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
- src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
- src/realm-settings/key-providers/hmac-generated/HMACGeneratedForm.tsx
- src/realm-settings/key-providers/java-keystore/JavaKeystoreForm.tsx
- src/realm-settings/key-providers/rsa-generated/RSAGeneratedForm.tsx
- src/realm-settings/key-providers/rsa/RSAForm.tsx
- src/realm-settings/messages.ts
- src/util.ts
Closes #603 
1. Go to Realm Settings -> Keys -> Providers list
2. Click and drag a provider to a new location
3. Inspect the network call and verify that the priority is changed based on the location in the providers list
> add priority attribute when dragging data list elements

- src/context/realm-context/RealmContext.tsx
- src/realm-settings/GeneralTab.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/TokensTab.tsx
- src/realm-settings/messages.ts
- src/realm/add/NewRealmForm.tsx
> made realm name editable

- src/clients/ClientsSection.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
> fixed logic when to show empty search result

- src/user-federation/UserFederationSection.tsx
- src/user-federation/kerberos/KerberosSettingsRequired.tsx
- src/user-federation/ldap/LdapSettingsGeneral.tsx
> use realm id instead of realm name

- src/authentication/DuplicateFlowModal.tsx
> fixed flow name

- src/realm-roles/RolesList.tsx
- src/realm-roles/routes/RealmRole.ts
> changed to append to url, for client role details

- .github/workflows/cypress.yml
- .github/workflows/node.js.yml
> Cache NPM dependencies in workflows

- cypress/support/pages/admin_console/manage/events/EventsPage.ts
Fixing events tests
Fixing dropdown selector used for accessing user events search form
1. Run events tests
> events: fixed dropdown selector in events tests

- src/identity-providers/add/DetailSettings.tsx
> fixed removed save buttons

- cypress/integration/realm_settings_test.spec.ts
- cypress/integration/user_fed_ldap_mapper_test.spec.ts
Cypress test suite fails too often.
Commented the two tests that often fail.  Hopefully, this will make the test suit more stable.
Run the Cypress tests
> Comment tests

- src/realm-settings/EmailTab.tsx
- src/realm-settings/KeysListTab.tsx
- src/realm-settings/LocalizationTab.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/RealmSettingsTabs.tsx
- src/realm-settings/SessionsTab.tsx
- src/realm-settings/TokensTab.tsx
> refactor realm settings

- src/groups/messages.ts
- src/realm-roles/UsersInRoleTab.tsx
- src/realm-roles/messages.ts
- src/realm-settings/KeysProvidersTab.tsx
- src/user/UserRoleMapping.tsx
- src/user/UsersTabs.tsx
- src/user/messages.ts
Part of the user details
Go to user details and see the new role mapping tab
> added user role mapping tab to user details

- src/realm-roles/RolesList.tsx
- src/realm-roles/routes/ClientRole.ts
- src/realm-roles/routes/RealmRole.ts
> Link to RealmRoleRoute using a static path

- cypress/integration/events_test.spec.ts
- cypress/support/pages/admin_console/manage/events/AdminEventsTab.ts
- src/events/AdminEvents.tsx
Enhance auth dialog on admin events tab and write cypress test.
1. Go to /events/adminEvents tab, select <more icon>, select 'Auth' option
2. Verify that Auth contains Attribute names as per https://marvelapp.com/prototype/7ca9dhf/screen/73036561
> Admin events auth dialog

- src/realm-settings/RealmSettingsTabs.tsx
- src/realm-settings/ThemesTab.tsx
> Remove internationalization from 'Themes' tab

- cypress/integration/clients_test.spec.ts
- src/clients/AdvancedTab.tsx
- src/clients/help.ts
> Process UXD feedback for client revocation

- src/realm-settings/security-defences/BruteForceDetection.tsx
> fixed missing fields

- src/client-scopes/add/RoleMappingForm.tsx
> multiple issues with this mapper

- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/events_test.spec.ts
- cypress/integration/group_test.spec.ts
- cypress/integration/realm_settings_test.spec.ts
- cypress/integration/users_test.spec.ts
- cypress/support/pages/admin_console/SidebarPage.ts
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/realm-settings/LocalizationTab.tsx
Somehow it was still showing the toolbar when there are no results, this fixes that
> don't show toolbar when not searching

- .eslintrc.js
- cypress/integration/user_fed_ldap_test.spec.ts
- cypress/plugins/index.js
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
- cypress/support/pages/admin_console/manage/realm_roles/CreateRealmRolePage.ts
- cypress/support/pages/admin_console/manage/users/UserDetailsPage.ts
- cypress/support/util/keycloak_before.ts
- jest.config.ts
- jest.setup.ts
- package-lock.json
- package.json
- postcss.config.js
- tsconfig.eslint.json
- types/import.d.ts
- types/static.d.ts
I kept running into some annoying errors when using the linting from the pre-commit hook (as this already lints all files). The configuration for the regular linting now matches that of the hook, preventing the aforementioned issues.
This PR also adds `eslint-plugin-cypress` which provides the globals and some sensible defaults for Cypress. All linting issues have been fixed as well.
> Lint all files in the project

- src/client-scopes/details/MappingDetails.tsx
fixes: https://github.com/keycloak/keycloak-admin-ui/issues/1099#issuecomment-924524293
> added description on new client scope screen

- cypress/integration/partial_import_test.spec.ts
- cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
- src/components/json-file-upload/JsonFileUpload.tsx
use the `<CodeEditor` on the `<JsonFileUpload` component
> changed to use code editor

- cypress/integration/realm_settings_test.spec.ts
- src/realm-settings/help.ts
- src/realm-settings/messages.ts
- src/realm-settings/security-defences/BruteForceDetection.tsx
- src/realm-settings/security-defences/Time.tsx
> fix the name of the fields introduced test

- cypress/integration/authentication_test.spec.ts
- cypress/support/pages/admin_console/manage/authentication/FlowDetail.ts
- src/authentication/EmptyExecutionState.tsx
- src/authentication/FlowDetails.tsx
- src/authentication/components/EditFlowDropdown.tsx
- src/authentication/components/FlowDiagram.tsx
- src/authentication/components/FlowRow.tsx
- src/authentication/components/modals/AddSubFlowModal.tsx
- src/authentication/execution-model.ts
- src/authentication/form/CreateFlow.tsx
- src/authentication/form/FlowType.tsx
- src/authentication/help.ts
- src/authentication/messages.ts
This PR adds the a way to add subflows to flow and also makes the create flow screen work.
And adds a delete button on each row
> added subflow and create flow to authentication

- cypress/integration/group_test.spec.ts
- cypress/support/pages/admin_console/manage/groups/GroupModal.ts
Group test is broken.
This is a temporary fix so we can get CI to pass.
> Temporary fix for group tests.

- src/components/role-mapping/AddRoleMappingModal.tsx
> fix select paging issue

- src/components/table-toolbar/KeycloakDataTable.tsx
- src/events/EventsSection.tsx
- src/events/messages.ts
* user details can be empty
* fix the number of rows displayed with collapse
> fixes some issue on the events tab

- src/client-scopes/add/MapperDialog.tsx
> Fixes missing text

- src/client-scopes/add/components/ScriptComponent.tsx
- src/client-scopes/messages.ts
> Added missing labels on the client scope mappers

- src/clients/ClientsSection.tsx
- src/realm-settings/messages.ts
> fixing messages

- cypress/integration/realm_settings_test.spec.ts
- src/realm-settings/LoginTab.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/RealmSettingsTabs.tsx
Closes #1158
1. Go to Realm Settings -> Login Tab
2. Verify that the all switches work as expected.
> Realm settings(login tab): fix switches

- cypress/integration/clients_test.spec.ts
- src/clients/ClientDetails.tsx
See the [design](https://marvelapp.com/prototype/5di1ce1/screen/81685254)
> Hide certain elements on the page if client is a realm 

- src/realm-settings/LocalizationTab.tsx
- src/realm-settings/help.ts
> Add help text to the realm localization fields

- src/realm-settings/help.ts
> Correct help text for XSS protection header

- .github/workflows/main.yml
Found out there is a recommended way to handle cache hits, this PR implements that.
> Improve caching logic of main workflow

- .eslintrc.js
- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/integration/identity_providers.spec.ts
- cypress/integration/login_test.spec.ts
- cypress/integration/realm_roles_test.spec.ts
- cypress/integration/realm_settings_test.spec.ts
- cypress/integration/sessions_test.spec.ts
- src/authentication/components/diagram/ConditionalNode.tsx
- src/authentication/components/diagram/SubFlowNode.tsx
Use arrow functions for all callbacks and enforce this as a rule. Came up as a point of discussion between me and @edewit and we thought this might be a good path.
> Prefer using arrow functions for callbacks

- src/client-scopes/add/MapperDialog.test.tsx
- src/client-scopes/add/MapperDialog.tsx
- src/common-messages.ts
- src/realm-settings/AddUserEmailModal.tsx
- src/realm-settings/EmailTab.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/messages.ts
> Updated the test ldap settings with second button

- cypress/integration/clients_test.spec.ts
- src/clients/ClientDetails.tsx
- src/clients/ClientSettings.tsx
- src/clients/add/CapabilityConfig.tsx
- src/components/scroll-form/ScrollForm.tsx
> Hide capability config for bearer-only clients

- src/clients/add/NewClientForm.tsx
> Normalize client attributes before saving

- cypress/integration/realm_settings_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
- src/realm-settings/ClientProfileForm.tsx
- src/realm-settings/ExecutorForm.tsx
- src/realm-settings/routes/ClientProfile.ts
Add tests for editing client profiles, creating and deleting executors.
Run realm-settings tests.
> Add tests for editing client profile, creating and deleting executors

- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
- src/App.tsx
- src/components/attribute-form/AttributeForm.tsx
- src/groups/GroupAttributes.tsx
- src/identity-providers/add/AddMapper.tsx
- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleForm.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/RoleAttributes.tsx
- src/realm-roles/RolesList.tsx
- src/realm-roles/routes/AddRole.ts
- src/realm-roles/routes/AddRoleToClient.ts
- src/realm-roles/routes/ClientRole.ts
- src/realm-roles/routes/RealmRole.ts
- src/route-config.ts
- src/user/UserAttributes.tsx
In master of keycloak there is a new composite role api that allows us to find composite roles more easy
> refactor + use new composite role api

- src/client-scopes/add/components/BooleanComponent.tsx
- src/client-scopes/add/components/ClientSelectComponent.tsx
- src/client-scopes/add/components/ListComponent.tsx
- src/client-scopes/add/components/MultivaluedListComponent.tsx
- src/client-scopes/add/components/MultivaluedStringComponent.tsx
- src/client-scopes/add/components/RoleComponent.tsx
- src/client-scopes/add/components/ScriptComponent.tsx
- src/client-scopes/add/components/StringComponent.tsx
- src/client-scopes/add/components/components.ts
- src/realm-settings/ClientProfileForm.tsx
- src/realm-settings/ExecutorForm.tsx
- src/realm-settings/NewClientPolicyCondition.tsx
- src/realm-settings/NewClientPolicyForm.tsx
- src/realm-settings/help.ts
- src/realm-settings/messages.ts
- src/realm-settings/routes/ClientProfile.ts
- src/realm-settings/routes/EditCondition.ts
- src/util.ts
https://issues.redhat.com/browse/CLUX-299
Adds functionality for the relevant configuration attributes for all policy condition types. 
1. Go to Client policies -> policies tab
2. Select a client policy or create a new one from the empty state. 
3. Click "Add a condition"
4. Verify that the correct fields and help text are showing for all condition types.
3. Add a condition 
4. Verify that you are able to save and submit successfully, and that the data is written correctly to the server
Builds on #1393 and #1357 - will rebase once merged to simplify review process
> Client policies(conditions): add correct form fields for all condition types

- src/realm-settings/LocalizationTab.tsx
- src/realm-settings/RealmSettingsTabs.tsx
- src/realm-settings/messages.ts
> can't remove english from supported locals

- src/identity-providers/add/AddMapper.tsx
> IDPs: go to edit form after save()

- src/user-federation/UserFederationKerberosSettings.tsx
- src/user-federation/kerberos/KerberosSettingsRequired.tsx
- src/user-federation/routes.ts
> removed useEffect data load instead uses fetch

- src/user-federation/UserFederationLdapSettings.tsx
- src/user-federation/messages.ts
> Ask for confirmation before unlinking users

- cypress/integration/realm_settings_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
- src/realm-settings/NewClientPolicyForm.tsx
- src/realm-settings/messages.ts
> Realm settings(Client policies -> policies): Add switch for enabling/disabling policy

- .github/dependabot.yml
Makes sure that Dependabot uses our new labels correctly.
> Add correct label for Dependabot PRs to config

- src/clients/keys/SamlKeys.tsx
- src/clients/keys/SamlKeysDialog.tsx
> Fixes some small issues with the SAML keys dialog

- src/components/json-file-upload/FileUploadForm.tsx
> don't call onchange when contents is empty

- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
- src/App.tsx
- src/authentication/RequiredActions.tsx
- src/client-scopes/form/ClientScopeForm.tsx
- src/clients/ClientDetails.tsx
- src/components/data-loader/DataLoader.tsx
- src/components/keycloak-spinner/KeycloakSpinner.tsx
- src/components/role-mapping/AddRoleMappingModal.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
- src/identity-providers/add/AddMapper.tsx
- src/identity-providers/add/DetailSettings.tsx
- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/RolesList.tsx
- src/realm-roles/messages.ts
- src/realm-roles/routes/ClientRole.ts
- src/realm-roles/routes/RealmRole.ts
- src/realm-settings/AddClientProfileModal.tsx
- src/realm-settings/PoliciesTab.tsx
- src/realm-settings/ProfilesTab.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/RealmSettingsTabs.tsx
- src/realm-settings/UserRegistration.tsx
- src/realm-settings/routes/RealmSettings.ts
- src/user-federation/ldap/mappers/LdapMapperHardcodedLdapRole.tsx
Also changed that the default role in realm tab now navigates to the user registration tab off the realm settings.
And introduced a `KeycloakSpinner` to remove some duplicate code.
> Added default role tab to realm settings

- src/user/UsersSection.tsx
- src/user/UsersTabs.tsx
> enable user management with limited permissions

- src/realm-roles/AssociatedRolesModal.tsx
- src/realm-roles/RealmRoleTabs.tsx
> Realm roles: fix issues from UX review

- .github/dependabot.yml
Keeps our Maven dependencies up-to-date.
> Add Dependabot configuration for Maven

- src/client-scopes/details/MapperList.tsx
> filter out unknown mappers

- src/clients/scopes/AddScopeDialog.tsx
- src/components/dynamic/DynamicComponents.tsx
- src/components/dynamic/MultivaluedChipsComponent.tsx
- src/components/group/GroupPickerDialog.tsx
- src/groups/GroupTable.tsx
- src/realm-settings/NewClientPolicyCondition.tsx
- src/realm-settings/RealmSettingsSection.css
- src/user/UserForm.tsx
- src/user/user-section.css
https://issues.redhat.com/browse/CLUX-331
https://marvelapp.com/prototype/2b3ghc06/screen/81619359
- Adds screen, correct fields, and functionality to client policies -> add condition -> client-updater-source-groups condition type
- Supports save and edit functionality
1. Go to Realm settings -> Client policies -> Policies subtab
2. Create a new client policy if one doesn't exist yet.
3. Click on the client policy and under Conditions, click "Add condition"
4. Select the "client-updater-source-groups" condition type.
5. Verify that the UI and functionality match the design and work as expected. 
6. Save the client-updater-source-groups condition.
7. Navigate back to the client-updater-source-groups condition type and verify that updating the data works as expected.
Dependent on #1532  - …
> Realm settings(client policies): add/edit client-updater-source-groups condition

- src/dashboard/Dashboard.tsx
- src/dashboard/messages.ts
Implements the Admin UI version as per @xianli123's design:
Actual implementation:
> Implement UXD feedback for Admin UI version

- src/components/dynamic/MultivaluedChipsComponent.tsx
- src/components/dynamic/labels.ts
- src/realm-settings/NewClientPolicyCondition.tsx
The PR was already merged so the points that I wanted to improve I added here myself.
> Added my PR review comments after the merge

- cypress/integration/authentication_test.spec.ts
- cypress/support/pages/admin_console/manage/authentication/PasswordPolicies.ts
- src/authentication/AuthenticationSection.tsx
- src/authentication/EmptyExecutionState.tsx
- src/authentication/messages.ts
- src/authentication/policies/PasswordPolicy.tsx
- src/authentication/policies/Policies.tsx
- src/authentication/policies/PolicyRow.tsx
- src/authentication/policies/policy-row.css
- src/authentication/policies/util.test.ts
- src/authentication/policies/util.ts
- src/common-messages.ts
- src/realm-settings/security-defences/Time.tsx
[marvel design](https://marvelapp.com/prototype/5ifgiai/screen/75687759)
> initial version of the password policies

- src/clients/authorization/ImportDialog.tsx
- src/clients/authorization/Settings.tsx
- src/clients/messages.ts
- src/components/json-file-upload/FileUploadForm.tsx
- src/realm-settings/PartialImport.tsx
added only [the screen](https://marvelapp.com/prototype/78j1b69/screen/82976116) without the import logic
> added import dialog for authorization resources

- src/groups/GroupsSection.tsx
> Wait for group to be deleted before navigating

- src/client-scopes/form/ClientScopeForm.tsx
> Trim name of client scope before saving

- src/clients/ClientDetails.tsx
- src/clients/add/NewClientForm.tsx
- src/groups/GroupsModal.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/user/UsersTabs.tsx
> Trim names of client, realm role, user and group before saving

- cypress/plugins/index.ts
- package-lock.json
- package.json
These are my review comments for #1628.
> Review comments for Cypress fixes PR

- cypress/fixtures/partial-import-test-data/multi-realm.json
- cypress/integration/partial_import_test.spec.ts
- cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
- package-lock.json
- package.json
- src/common-messages.ts
- src/realm-settings/PartialImport.tsx
- src/realm-settings/messages.ts
Completed Partial Import
The import button is now active and it calls the REST endpoint.  Then it displays the results as per:
https://marvelapp.com/prototype/fg26f9b/screen/75624798
1. Go to `Realm settings`.
2. Select Partial import form the Action dropdown.
3. Import a previously exported Keycloak json. (Samples test data at `/cypress/fixtures/partial-import-test-data/`. kcexport.json is a good one to look at)
4. Verify that modal presents the user with options as shown in the design, plus multi-realm functionality.
5. Press import and see results.
> Complete partial import functionality.

- src/components/dynamic/BooleanComponent.tsx
- src/components/dynamic/labels.ts
> fix client scopes mapper labels

- cypress/integration/authentication_test.spec.ts
- cypress/support/pages/admin_console/manage/authentication/OTPPolicies.ts
- src/authentication/help.ts
- src/authentication/messages.ts
- src/authentication/policies/OtpPolicy.tsx
- src/authentication/policies/Policies.tsx
- src/authentication/policies/otp-policy.css
Added otp policies screen according to [marvel](https://marvelapp.com/prototype/5ifgiai/screen/75687757)
> added otp policies screen

- src/authentication/policies/OtpPolicy.tsx
> fixed merge error

- .gitignore
- keycloak-theme/pom.xml
- release.sh
> Add nexus profile for releases

- src/client-scopes/add/MapperDialog.tsx
- src/client-scopes/messages.ts
> modal fixes for predefined mappers

- cypress/integration/clients_saml_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/Authentication.ts
- src/clients/ClientDetails.tsx
- src/clients/authorization/ResourceDetails.tsx
- src/clients/authorization/Settings.tsx
- src/clients/messages.ts
This finishes the resource settings tab under client authentication by adding the functionallity for save and import
> added import and save functions to resource tab

- src/user/UserCredentials.tsx
- src/user/user-section.css
> removed global css

- package-lock.json
- package.json
Update to latest PF versions.
Tested new PF versions manually and ran cypress tests against them last week.
> Update to Patternfly 4.164.2

- cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
- cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
- src/user/UserCredentials.tsx
- src/user/messages.ts
Also cleans up some interpolation for translations.
> Fix broken Cypress tests

- package-lock.json
- package.json
- src/clients/ClientDetails.tsx
- src/clients/authorization/DeleteScopeDialog.tsx
- src/clients/authorization/MoreLabel.tsx
- src/clients/authorization/ResourceDetails.tsx
- src/clients/authorization/Resources.tsx
- src/clients/authorization/ScopeDetails.tsx
- src/clients/authorization/Scopes.tsx
- src/clients/help.ts
- src/clients/messages.ts
- src/clients/routes.ts
- src/clients/routes/NewResource.ts
- src/clients/routes/NewScope.ts
- src/clients/routes/Resource.ts
- src/clients/routes/Scope.ts
[marvel](https://marvelapp.com/prototype/5fi097g/screen/83009424)
> initial version of the scopes screen

- cypress/integration/user_fed_kerberos_test.spec.ts
- cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts
- cypress/integration/user_fed_ldap_mapper_test.spec.ts
- cypress/integration/user_fed_ldap_test.spec.ts
- cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
- src/user-federation/UserFederationKerberosSettings.tsx
- src/user-federation/UserFederationLdapSettings.tsx
- src/user-federation/UserFederationSection.tsx
- src/user-federation/custom/CustomProviderSettings.tsx
- src/user-federation/custom/custom-provider-settings.css
- src/user-federation/messages.ts
- src/user-federation/routes.ts
- src/user-federation/routes/NewLdapUserFederation.ts
- src/user-federation/routes/NewProvider.ts
- src/user-federation/shared/ExtendedHeader.tsx
- src/user-federation/shared/Header.tsx
- src/user-federation/shared/SettingsCache.tsx
> Create custom user federation providers page

- cypress/integration/authentication_test.spec.ts
- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/clients_saml_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/integration/events_test.spec.ts
- cypress/integration/group_test.spec.ts
- cypress/integration/identity_providers_oidc_test.spec.ts
- cypress/integration/identity_providers_saml_test.spec.ts
- cypress/integration/identity_providers_test.spec.ts
- cypress/integration/login_test.spec.ts
- cypress/integration/masthead_test.spec.ts
- cypress/integration/partial_export_test.spec.ts
- cypress/integration/partial_import_test.spec.ts
- cypress/integration/realm_roles_test.spec.ts
- cypress/integration/realm_settings_client_policies_test.spec.ts
- cypress/integration/realm_settings_client_profiles_test.spec.ts
- cypress/integration/realm_settings_events_test.spec.ts
- cypress/integration/realm_settings_tabs_test.spec.ts
- cypress/integration/realm_test.spec.ts
- cypress/integration/sessions_test.spec.ts
- cypress/integration/user_fed_kerberos_test.spec.ts
- cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts
- cypress/integration/user_fed_ldap_mapper_test.spec.ts
- cypress/integration/user_fed_ldap_test.spec.ts
- cypress/integration/users_test.spec.ts
- cypress/support/util/keycloak_hooks.ts
future PR will change other integration tests to do the same
> now only logs in per test suite for client tests

- src/components/download-dialog/DownloadDialog.tsx
> removed look ahead / back regex for safari

- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/clients_saml_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/integration/user_profile_tab.spec.ts
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
- cypress/support/pages/admin_console/manage/clients/AdvancedTab.ts
- cypress/support/pages/admin_console/manage/clients/AuthenticationTab.ts
- cypress/support/pages/admin_console/manage/clients/ClientScopesTab.ts
- src/user-federation/UserFederationSection.tsx
Update Clients tests
- Standarize `goToTab` methods to include the tab name
- Add the type of element to the element names on PageObjects
- Add the suffix "Tab" to the `Authentication` PageObject
- Order the before, before each methods to clarify
- Remove "click" name in PageObject methods
- Uncomment and complete `assign` test in `clients_test.spec.ts`
- [x ] Code has been tested locally by PR requester
> Update Clients tests

- cypress/integration/client_authorization_test.spec.ts
- cypress/integration/clients_saml_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/AuthorizationTab.ts
- src/clients/ClientDetails.tsx
- src/clients/authorization/DetailCell.tsx
- src/clients/authorization/DetailDescription.tsx
- src/clients/authorization/EmptyPermissionsState.tsx
- src/clients/authorization/PermissionDetails.tsx
- src/clients/authorization/Permissions.tsx
- src/clients/authorization/ResourcesPolicySelect.tsx
- src/clients/authorization/Scopes.tsx
- src/clients/authorization/SearchDropdown.tsx
- src/clients/authorization/Settings.tsx
- src/clients/authorization/permissions.css
- src/clients/authorization/search-dropdown.css
- src/clients/help.ts
- src/clients/messages.ts
- src/clients/routes.ts
- src/clients/routes/NewPermission.ts
- src/clients/routes/PermissionDetails.ts
Permissions tab with create for resource based permssions scope-based comming in a sperate PR also search is still a work in progress
> Adds the permissions tab to the Authorization screen under clients

- src/realm-roles/RealmRoleTabs.tsx
Closes #1838 
Finishing up a PR that will add selectable functionality to [AttributeInput](https://github.com/keycloak/keycloak-admin-ui/blob/0bbd4ddad1b0fe3eeac9942b88539933f2e66c3a/src/components/attribute-input/AttributeInput.tsx) -- however while testing, I discovered the data could not be saved correctly due to this bug.
After a bunch of investigating, this seems like it's a timing issue.
> Realm roles: fixes bug that prevents fields from being populated

- src/components/routable-tabs/RoutableTabs.tsx
- src/realm-settings/routes.ts
- src/realm-settings/routes/UserProfile.ts
- src/realm-settings/user-profile/UserProfileTab.tsx
This will allow us to return to the correct path when navigating back from a nested form.
> Make 'User Profile' tabs routable

- src/clients/authorization/Resources.tsx
- src/clients/authorization/Scopes.tsx
> added links to permission create

- cypress/integration/realm_test.spec.ts
- cypress/support/pages/admin_console/CreateRealmPage.ts
- src/components/realm-selector/RealmSelector.tsx
- src/context/RealmsContext.tsx
> optimized realm loading and added current realm

- src/realm-settings/ClientProfileForm.tsx
- src/realm-settings/NewClientPolicyForm.tsx
- src/realm-settings/RealmSettingsSection.tsx
- src/realm-settings/RealmSettingsTabs.tsx
- src/realm-settings/messages.ts
- src/realm-settings/routes.ts
- src/realm-settings/routes/AddClientPolicy.ts
- src/realm-settings/routes/AesGeneratedSettings.ts
- src/realm-settings/routes/ClientPolicies.ts
- src/realm-settings/routes/ClientProfile.ts
- src/realm-settings/routes/EcdsaGeneratedSettings.ts
- src/realm-settings/routes/EditClientPolicy.ts
- src/realm-settings/routes/Executor.ts
- src/realm-settings/routes/HmacGeneratedSettings.ts
- src/realm-settings/routes/JavaKeystoreSettings.ts
- src/realm-settings/routes/KeysTab.ts
- src/realm-settings/routes/RealmSettings.ts
- src/realm-settings/routes/RsaGeneratedSettings.ts
- src/realm-settings/routes/RsaSettings.ts
> make all sub tabs routeable tabs

- cypress/integration/clients_saml_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
- cypress/support/pages/admin_console/manage/clients/AdvancedTab.ts
- cypress/support/pages/admin_console/manage/clients/AuthorizationTab.ts
- cypress/support/pages/admin_console/manage/clients/ClientScopesTab.ts
- cypress/support/pages/admin_console/manage/clients/KeysTab.ts
- src/clients/ClientDetails.tsx
- src/clients/authorization/PermissionDetails.tsx
- src/clients/authorization/ResourceDetails.tsx
- src/clients/authorization/ScopeDetails.tsx
- src/clients/authorization/policy/PolicyDetails.tsx
- src/clients/routes.ts
- src/clients/routes/AuthenticationTab.ts
- src/clients/routes/Client.ts
- src/clients/routes/ClientScopeTab.ts
Now uses the routable tabs so that we can bookmark the sub tabs.
> Changed to use routable tabs

- cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
fixed some of the failing tests...
> renamed tab and better detail click

- src/components/dynamic/labels.ts
> Fix message for access token response claim in new admin ui

- cypress/integration/masthead_test.spec.ts
- cypress/integration/partial_import_test.spec.ts
- cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
- src/context/RealmsContext.tsx
- src/context/server-info/ServerInfoProvider.tsx
- src/dashboard/Dashboard.tsx
> handle error code < 500 in error handler

- src/realm-settings/ClientProfileForm.tsx
- src/realm-settings/NewClientPolicyCondition.tsx
- src/realm-settings/NewClientPolicyForm.tsx
> changed to use route functions

- cypress/integration/users_test.spec.ts
- cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
- src/user/UserCredentials.tsx
- src/user/messages.ts
- src/user/user-credentials/CredentialDataDialog.tsx
- src/user/user-credentials/CredentialRow.tsx
- src/user/user-credentials/CredentialsResetActionMultiSelect.tsx
- src/user/user-credentials/InlineLabelEdit.tsx
- src/user/user-credentials/LifespanField.tsx
- src/user/user-credentials/ResetCredentialDialog.tsx
- src/user/user-credentials/ResetPasswordDialog.tsx
User credentials tab component was big, so I refactored it into seperate components
> Refactored user credentials into seperate components

- src/clients/authorization/PermissionDetails.tsx
- src/clients/authorization/ScopeSelect.tsx
- src/clients/help.ts
Prev. PR was missing ability to create scope typed permissions this PR adds that.
> Added scope typed permission screen

- src/clients/ClientDetails.tsx
- src/clients/authorization/AuthorizationEvaluate.tsx
- src/components/attribute-form/AttributeForm.tsx
- src/components/attribute-input/AttributeInput.tsx
- src/realm-roles/RealmRoleTabs.tsx
Extends work done on #1861 - these fixes are necessary in order to implement results screen https://marvelapp.com/prototype/5eg9ic7/screen/83188838
Fixes `evaluate` call which now POSTs successfully, adds 'revert' functionality to form, fixes bug in realm role attributes and  resolves some issues with data types in `AttributeInput`
1. Create a OIDC client with Client Authentication and Authorization switches enabled.
2. Go to the new client -> Authorization -> Evaluate
3. Fill in form data and verify that the `evaluate` call POSTs successfully
> Clients(Authorization): Evaluate tab updates

- src/identity-providers/add/DetailSettings.tsx
> fix mapper table bugs

- src/components/dynamic/BooleanComponent.tsx
- src/components/dynamic/ClientSelectComponent.tsx
- src/components/dynamic/DynamicComponents.tsx
- src/components/dynamic/ListComponent.tsx
- src/components/dynamic/MultivaluedChipsComponent.tsx
- src/components/dynamic/MultivaluedListComponent.tsx
- src/components/dynamic/MultivaluedRoleComponent.tsx
- src/components/dynamic/MultivaluedScopesComponent.tsx
- src/components/dynamic/MultivaluedStringComponent.tsx
- src/components/dynamic/RoleComponent.tsx
- src/components/dynamic/ScriptComponent.tsx
- src/components/dynamic/StringComponent.tsx
- src/components/dynamic/components.ts
- src/components/form-access/FormAccess.tsx
- src/realm-settings/ExecutorForm.tsx
The screen is now readonly for global profiles, but the breadcrumb is not fixed as this is a global issue
fixes: #1898
fixes: #1900
> Made form readonly and fixed initialisation

- src/clients/advanced/TokenLifespan.tsx
> fixed test if value is set

- src/authentication/FlowDetails.tsx
- src/authentication/components/FlowRow.tsx
> remove child of sub flow instead of flow itself

- src/identity-providers/add/DescriptorSettings.tsx
- src/identity-providers/add/SamlGeneralSettings.tsx
- src/identity-providers/add/saml-general-settings.css
- src/identity-providers/help.ts
- src/identity-providers/messages.ts
> added missing fields to saml details page

- src/clients/ClientSettings.tsx
> removed login settings section for baerer only

- src/identity-providers/component/DiscoveryEndpointField.tsx
- src/identity-providers/icons/FontAwesomeIcon.tsx
> fixed logo locations

- src/identity-providers/messages.ts
> removed unusable `providerId`

- cypress/integration/realm_settings_events_test.spec.ts
- src/realm-settings/KeysProvidersTab.tsx
- src/realm-settings/help.ts
- src/realm-settings/key-providers/rsa-enc-generated/RSAEncGeneratedForm.tsx
- src/realm-settings/key-providers/rsa-enc-generated/RSAEncGeneratedModal.tsx
- src/realm-settings/key-providers/rsa-generated/RSAGeneratedForm.tsx
- src/realm-settings/key-providers/rsa/RSAForm.tsx
- src/realm-settings/messages.ts
- src/realm-settings/routes.ts
- src/realm-settings/routes/RsaEncGeneratedSettings.ts
> Add screens for rsa-enc-generated type

- src/identity-providers/add/SamlConnectSettings.tsx
- src/identity-providers/component/DiscoveryEndpointField.tsx
> fixing labels in case of SAML

- src/clients/advanced/FineGrainOpenIdConnect.tsx
> fixed attribute name

- src/groups/GroupsSection.tsx
- src/groups/Members.tsx
- src/groups/SubGroupsContext.tsx
> async loading group can be undefined

- src/clients/ClientDetails.tsx
> remote client-scopes and mappers for bearer only

- src/clients/ClientDetails.tsx
- src/clients/advanced/FineGrainOpenIdConnect.tsx
- src/clients/authorization/ResourceDetails.tsx
- src/clients/help.ts
- src/clients/messages.ts
- src/components/multi-line-input/MultiLineInput.tsx
- src/components/multi-line-input/multi-line-convert.ts
- src/groups/GroupAttributes.tsx
- src/util.test.ts
- src/util.ts
> Added new / missing fields

- src/identity-providers/add/OpenIdConnectSettings.tsx
- src/identity-providers/add/SamlConnectSettings.tsx
- src/identity-providers/component/DiscoveryEndpointField.tsx
- src/identity-providers/messages.ts
> changed how errors are displayed

- src/client-scopes/ClientScopesSection.tsx
> remove export button in Client Scopes

- src/clients/authorization/PermissionDetails.tsx
> make permission name required

- src/clients/ClientSettings.tsx
- src/clients/help.ts
- src/clients/messages.ts
> Added missing fields

- cypress/integration/client_scopes_test.spec.ts
- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/util/AdminClient.ts
- cypress/support/util/ModalUtils.ts
- src/client-scopes/ChangeTypeDropdown.tsx
- src/client-scopes/ClientScopesSection.tsx
- src/clients/scopes/ClientScopes.tsx
Closes [#1966](https://github.com/keycloak/keycloak-admin-ui/issues/1966)
Amplify tests coverage for **Clients -> ClientScopes** and **ClientScopes** sections.
> new Client->details->ClientScopes and ClientScopes tests

- cypress/integration/sessions_test.spec.ts
- cypress/support/pages/admin_console/manage/sessions/SessionsPage.ts
- src/sessions/SessionsSection.tsx
> removed not working filter option

- cypress/integration/realm_roles_test.spec.ts
- cypress/support/pages/admin_console/Masthead.ts
- cypress/support/pages/admin_console/SidebarPage.ts
- cypress/support/pages/admin_console/manage/realm_roles/CreateRealmRolePage.ts
- cypress/support/util/AdminClient.ts
- src/realm-roles/RealmRoleForm.tsx
- src/realm-roles/RealmRoleTabs.tsx
fixes some of the testing checkboxes
> added better / more realm role tests

- src/client-scopes/details/ScopeForm.tsx
Closes #2110 
Added default value in the form
> fix new client scope default type value

- src/client-scopes/details/ScopeForm.tsx
- src/identity-providers/component/DisplayOrder.tsx
Display order should support blank as default
> changed to number input to allow for blank

- cypress/integration/users_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/manage/users/CreateUserPage.ts
- cypress/support/pages/admin_console/manage/users/UserGroupsPage.ts
- src/user/UsersSection.tsx
Adds Cypress tests for remaining rows in Users group:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=273:281
> Cypress tests: users

- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- src/clients/ClientDescription.tsx
- src/clients/ClientSettings.tsx
- src/clients/help.ts
- src/clients/messages.ts
> Add "always display" switch

- src/clients/add/SamlConfig.tsx
> added missing field

- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- src/clients/ClientSettings.tsx
- src/clients/add/CapabilityConfig.tsx
- src/clients/add/NewClientForm.tsx
- src/clients/add/capability-config.css
- src/clients/help.ts
- src/clients/messages.ts
> Add new capability configs and tests

- src/components/time-selector/TimeSelector.tsx
> fix for value === 0

- src/clients/ClientDetails.tsx
> remove authorization tab when  disabled

- src/common-messages.ts
- src/components/table-toolbar/KeycloakDataTable.tsx
> added a way to clear filters for non custom search

- src/realm-settings/ExecutorForm.tsx
> reset the form when the type is changed

- src/clients/AdvancedTab.tsx
> hide clustering section when not publicClient

- src/clients/ClientDetails.tsx
- src/clients/authorization/AuthorizationEvaluate.tsx
> change the way clients are stored in the form

- src/clients/authorization/policy/Group.tsx
- src/clients/help.ts
- src/clients/messages.ts
> added missing groups claim field

- src/clients/AdvancedTab.tsx
> removed 'revocation' section when client is SAML

- src/components/table-toolbar/KeycloakDataTable.tsx
> fixed getting text from jsx element

- cypress/integration/clients_test.spec.ts
- cypress/integration/realm_roles_test.spec.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/manage/clients/ClientRolesTab.ts
- cypress/support/pages/admin_console/manage/clients/RolesTab.ts
- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
- src/realm-roles/AssociatedRolesTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
- src/realm-roles/RolesList.tsx
Adds tests for "Roles" Section of Clients:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=95:112
> Clients -> Roles Tab: Adds Role Tests

- src/clients/authorization/PermissionDetails.tsx
- src/clients/authorization/Resources.tsx
- src/clients/authorization/Scopes.tsx
- src/clients/help.ts
> fixed title and link to page

- src/clients/add/NewClientForm.tsx
> remove capabities step from wizard for SAML

- src/clients/initial-access/InitialAccessTokenList.tsx
> catch 403 when only query-clients is allowed

- src/realm-settings/TokensTab.tsx
when sso session idle timeout is updated
fixes: #1778
> removed the need to refresh the page

- src/user/UserCredentials.tsx
> fixed dragging and dropping

- src/realm-settings/user-profile/AttributesGroupForm.tsx
> Fix Edit Attributes Group bug

- src/clients/authorization/AuthorizationEvaluate.tsx
> Fix(clients -> authorization): Evaluate results screen

- src/realm-settings/user-profile/AttributesGroupForm.tsx
> added hidden input to submit name when disabled

- src/realm-settings/messages.ts
- src/realm-settings/user-profile/AttributesTab.tsx
> added filter

- src/client-scopes/ClientScopesSection.tsx
> reset filter after change

- cypress/integration/realm_settings_tabs_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
- src/components/view-header/ViewHeader.tsx
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=410:412
> Add Realm settings -> realm actions tests

- src/realm-settings/PoliciesTab.tsx
> added confirm dialog on disable

- src/clients/authorization/policy/ClientScope.tsx
- src/clients/scopes/ClientScopes.tsx
- src/components/dynamic/MultivaluedScopesComponent.tsx
> sort client scope dialogs

- src/realm-settings/TokensTab.tsx
> remove "Revoke Refresh Token" when not revoke on

- src/client-scopes/form/ClientScopeForm.tsx
Also fixes a bug where one of the parameters was lost
> changed to use RoutableTabs

- src/components/alert/AlertPanel.tsx
- src/components/alert/Alerts.tsx
- src/user/UsersSection.tsx
- src/user/messages.ts
> added hint when no user found

- cypress/integration/client_authorization_test.spec.ts
- cypress/support/pages/admin_console/Masthead.ts
Ran these tests for 20 times and I think these now work again
> fixed broken tests

- cypress/integration/partial_import_test.spec.ts
- cypress/support/commands.ts
- cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
- cypress/tsconfig.json
- package-lock.json
- package.json
makes the import text more stable
> use file upload instead of typing large text

- src/groups/MembersModal.tsx
> remove add users button

- README.md
- cypress/WRITING_TESTS.md
As promised, initial version of writing tests document, feel free to add / discuss here futher.
> initial version of writing tests document

- src/clients/authorization/AuthorizationEvaluate.tsx
- src/clients/authorization/KeyBasedAttributeInput.tsx
- src/components/attribute-form/AttributeForm.tsx
- src/components/attribute-input/AttributeInput.tsx
- src/realm-roles/RealmRoleTabs.tsx
it's made it's base component to hard to reuse and was only used once
> split out the key based into a sperate component

- src/clients/keys/GenerateKeyDialog.tsx
- src/clients/keys/ImportKeyDialog.tsx
- src/clients/keys/Keys.tsx
- src/clients/keys/SamlImportKeyDialog.tsx
- src/clients/keys/SamlKeysDialog.tsx
- src/clients/keys/StoreSettings.tsx
> default value and required field for generate keys

- src/realm-settings/LocalizationTab.tsx
> Always keep DEFAULT_LOCAL selected

- src/clients/credentials/Credentials.tsx
> always enable regenerate button

- src/identity-providers/component/DisplayOrder.tsx
> assure that the value is either emtpy or 0

- src/clients/authorization/AuthorizationEvaluate.tsx
> Auth evaluate fix

- src/PageNav.tsx
> fixed link

- src/clients/authorization/DetailCell.tsx
- src/clients/authorization/DetailDescription.tsx
- src/clients/authorization/Permissions.tsx
- src/clients/authorization/Policies.tsx
- src/clients/authorization/Scopes.tsx
> Convert detail tab text to links

- src/clients/authorization/ScopeDetails.tsx
Fix title key of authorization scope create/details screen.
Create:
https://marvelapp.com/prototype/5fi097g/screen/83009422
Update:
https://marvelapp.com/prototype/5fi097g/screen/83009424
> fix scope details title key

- src/PageNav.tsx
Reverts keycloak/keycloak-admin-ui#2258
> Revert "fixed link"

- package-lock.json
- package.json
Reverts the upgrade of react-flow-renderer, which is causing issues for the build.
> Revert "Bump react-flow-renderer from 9.7.4 to 10.0.3"

- src/clients/authorization/PermissionDetails.tsx
- src/clients/authorization/ResourcesPolicySelect.tsx
> make resouce field required

- src/realm-settings/AddMessageBundleModal.tsx
fixes translation keys as well + some copy paste errors
fixes: #1180
> put focus on the right field

- src/components/table-toolbar/PaginatingTableToolbar.tsx
- src/components/table-toolbar/TableToolbar.tsx
fixes: #1348
but changes the look and feel a bit:
> changed to use the SearchInput

- src/clients/messages.ts
- src/clients/scopes/AddScopeDialog.tsx
- src/components/table-toolbar/KeycloakDataTable.tsx
> added empty state to add scope dialog

- cypress/support/pages/admin_console/manage/clients/AuthorizationTab.ts
> fix auth tests

- cypress/integration/client_authorization_test.spec.ts
These tests are broken and are preventing us from merging open PRs.
> Skip broken client authorization tests

- cypress/integration/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- cypress/support/pages/admin_console/manage/clients/InitialAccessTokenTab.ts
> Add Clients tests

- src/clients/ClientsSection.tsx
> show baseUrl when rootUrl is not set

- src/user/UserCredentials.tsx
> change button text to "set password"

- cypress/integration/realm_settings_tabs_test.spec.ts
- src/realm-settings/GeneralTab.tsx
- src/realm-settings/LoginTab.tsx
- src/realm-settings/PoliciesTab.tsx
- src/realm-settings/RealmSettingsTabs.tsx
Adds login tests: 
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=443:446
> Realm settings(login tab): Add login tests

- src/clients/ClientDetails.tsx
- src/clients/credentials/ClientSecret.tsx
- src/clients/credentials/Credentials.tsx
> Client credentials: "Regenerate" button fix

- src/clients/help.ts
- src/clients/messages.ts
- src/clients/service-account/ServiceAccount.tsx
- src/clients/service-account/service-account.css
> added service account user link

- src/components/table-toolbar/KeycloakDataTable.tsx
- src/realm-settings/keys/KeysListTab.tsx
> fixed the filter dropdown

- src/user-federation/ldap/mappers/LdapMapperList.tsx
> sort mappers in alphabetical order

- src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
- src/user-federation/kerberos/KerberosSettingsRequired.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/ldap/LdapSettingsGeneral.tsx
- src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
- src/user-federation/ldap/LdapSettingsSearching.tsx
- src/user-federation/user-federation.css
> don't test ldap when form isn't valid

- src/clients/ClientDetails.tsx
- src/clients/advanced/AdvancedSettings.tsx
- src/clients/help.ts
- src/clients/messages.ts
> added more missing fields

- src/realm-settings/RealmSettingsTabs.tsx
fixes: https://github.com/keycloak/keycloak-admin-ui/pull/2241#issuecomment-1070352989
> override when already set with default

- cypress/integration/clients_test.spec.ts
- cypress/integration/realm_roles_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=259:270
> Realm roles: Adds tests for composite realm roles

- src/realm-roles/RealmRoleForm.tsx
- src/realm-roles/RolesList.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1851.
Added header and fixed cancel button on create realm role form.
See the linked issue for specifics including how to reproduce.
None
> Fixes header and cancel when adding realm roles

- cypress/integration/user_fed_kerberos_test.spec.ts
- cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
- src/user-federation/messages.ts
- src/user-federation/shared/SettingsCache.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1810.
Changed Max Lifespan from text field to number input.
Verify that implementation matches design outlined in https://github.com/keycloak/keycloak-admin-ui/issues/1810 and that you can still save/retrieve values correctly.
None
> Use number input for max lifespan

- cypress/integration/clients_test.spec.ts
- cypress/integration/events_test.spec.ts
- cypress/integration/masthead_test.spec.ts
- cypress/integration/sessions_test.spec.ts
Skip the tests that are broken due to changes in https://github.com/keycloak/keycloak/pull/10887
> Skip broken tests related to logout

- cypress/integration/realm_settings_general_tab_test.spec.ts
- cypress/integration/realm_settings_tabs_test.spec.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
- src/realm-settings/GeneralTab.tsx
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=429:438
> Adds Realm Settings tests for general tab

- cypress/integration/clients_test.spec.ts
- cypress/integration/realm_test.spec.ts
- cypress/support/pages/admin_console/CreateRealmPage.ts
- cypress/support/pages/admin_console/SidebarPage.ts
- src/components/json-file-upload/FileUploadForm.tsx
Adds tests for Realm Selector: 
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=26:39
> Add realm selector tests

- src/user-federation/UserFederationLdapSettings.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/ldap/LdapSettingsGeneral.tsx
> add id to the form

- cypress/integration/client_authorization_test.spec.ts
- src/clients/authorization/PermissionDetails.tsx
> WIP: enabled more tests

- cypress/integration/clients_test.spec.ts
- cypress/integration/realm_test.spec.ts
- cypress/support/pages/admin_console/CreateRealmPage.ts
- cypress/support/pages/admin_console/ListingPage.ts
- cypress/support/pages/admin_console/Masthead.ts
- cypress/support/pages/admin_console/manage/clients/ClientRolesTab.ts
- cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts
- cypress/support/pages/admin_console/manage/identity_providers/CreateProviderPage.ts
- cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
- cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
An attempt at fixing/improving the "should create Test Disabled realm" test detected by Cypress Dashboard as flaky.
realm_test suit is passing locally:
1. Run tests in `realm_test.spec.ts` locally.
> wip: realm_test fix/improvement attempt

- cypress/integration/clients_test.spec.ts
- src/clients/ClientDetails.tsx
- src/clients/help.ts
- src/clients/messages.ts
- src/clients/permissions/PermissionTab.tsx
- src/clients/permissions/permissions-tab.css
- src/clients/routes/Client.ts
> added initial version of the client permission tab

- src/authentication/components/ExecutionConfigModal.tsx
- src/components/dynamic/labels.ts
> added labels for loa properties

- src/clients/authorization/KeyBasedAttributeInput.tsx
> fixed error when data not found

- cypress/integration/client_authorization_test.spec.ts
- cypress/support/pages/admin_console/components/TabPage.ts
- cypress/support/pages/admin_console/manage/clients/client_details/tabs/AuthorizationTab.ts
Problem was that there where 2 permissions tabs one in the main
and one in the subtab
> re-enable permissions test and fixed sub tabs

- cypress/integration/identity_providers_oidc_test.spec.ts
- cypress/integration/identity_providers_saml_test.spec.ts
- cypress/integration/identity_providers_test.spec.ts
- cypress/support/pages/admin_console/Masthead.ts
Fix for the following tests.
1. Run tests locally, all should pass.
> Extra fixes

- cypress/integration/realm_roles_test.spec.ts
seems it sometimes misses one `@load`
> Skip tests that are constantly flaky

- src/sessions/SessionsSection.tsx
> fixed link to client

- src/user-federation/UserFederationLdapSettings.tsx
- src/user-federation/ldap/LdapSettingsAdvanced.tsx
- src/user-federation/ldap/LdapSettingsConnection.tsx
- src/user-federation/messages.ts
> Added ability to query ldap capabilities

- cypress/integration/partial_import_test.spec.ts
Try to get the partial import tests to run more consistently in CI.
Changed to use admin client to create the new realm(s) instead of using the UI.
Run the tests
> Fix partial import tests

- src/util.test.ts
- src/util.ts
> convert single array values to values

- public/resources/en/common.json
- src/components/permission-tab/PermissionTab.tsx
- src/groups/GroupsSection.tsx
part of the fine grained permissions
> initial version of the group permissions tab

- public/resources/en/users.json
- src/user/UsersSection.tsx
> no spinner when no have rights for realm load

- src/clients/scopes/AddScopeDialog.tsx
this also makes the re-render better
fixes: #2521
> small fix to prevent empty dialog

- package-lock.json
- package.json
- public/resources/en/common.json
- src/components/permission-tab/PermissionTab.tsx
- src/realm-roles/RealmRoleTabs.tsx
> added role permission tab

- src/clients/credentials/ClientSecret.tsx
- src/clients/scopes/CopyToClipboardButton.tsx
- src/clients/scopes/GeneratedCodeTab.tsx
> use password field + copy to clipboard button

- package-lock.json
- package.json
- public/resources/en/dashboard.json
- src/dashboard/Dashboard.tsx
- src/dashboard/ProviderInfo.tsx
> added search and operational info

- public/resources/en/common.json
- public/resources/en/users.json
- src/components/role-mapping/RoleMapping.tsx
- src/user/UserRoleMapping.tsx
> Made inherited column "true" or "false"

- public/resources/en/authentication.json
- src/authentication/AuthenticationSection.tsx
- src/authentication/components/UsedBy.tsx
- src/authentication/components/used-by.css
based on how many idps or clients it's used either
a popup or a modal dialog
fixes: #2509
> changed to know where flow is used

- src/clients/add/SamlSignature.tsx
- src/realm-settings/security-defences/HeadersForm.tsx
> Update outdated links with redirects

- src/components/realm-selector/realm-selector.css
> added second class to override patternfly default

- src/components/permission-tab/PermissionTab.tsx
> fixed client lookup for non master realm

- cypress/integration/client_authorization_test.spec.ts
- src/clients/authorization/ResourcesPolicySelect.tsx
Without this the policy endpoint will return policies and permissions we only want policies in this dropdown.
fixes: #2528
> add permission: false to policy query

- src/authentication/__tests__/ExecutionList.test.ts
- src/authentication/execution-model.ts
> skip already processed lines

- src/clients/authorization/DecisionStragegySelect.tsx
- src/clients/authorization/Settings.tsx
Fix for #2372
1. Navigate to Clients and create a new client
2. Selected created client, navigate to the Authorization tab, select a different decision strategy and click "Save"
3. Navigate to a different page and back to Clients and selected edited client
4. Verify that the decision strategy is showing the last selected strategy
> Client -> Authorization -> Decision Strategy Fix

- public/resources/en/authentication.json
- src/authentication/AuthenticationSection.tsx
- src/authentication/components/UsedBy.tsx
Should have been part of the initial change, but it seems I didn't test this enough
> use flow type instead of flow name

- src/clients/authorization/PermissionDetails.tsx
> added permission type to scope based permissions

- src/clients/authorization/Scopes.tsx
> added dash when there is no data

- package-lock.json
- package.json
- public/resources/en/common.json
- src/components/alert/Alerts.tsx
- src/components/permission-tab/PermissionTab.tsx
- src/identity-providers/add/DetailSettings.tsx
> added permissions tab for idp

- src/user-federation/shared/ExtendedHeader.tsx
> disable sync when import users is off

- src/identity-providers/add/AddMapper.tsx
> added delete action

- src/user-federation/ldap/mappers/LdapMapperDetails.tsx
- src/user-federation/routes/UserFederationLdap.ts
> Added delete action on LDAP mapper details

- src/user-federation/UserFederationLdapSettings.tsx
> removed additional white space

- public/resources/en/groups.json
- src/components/role-mapping/RoleMapping.tsx
- added missing translations
- small wait in between load and delete query
fixes: #2580
> issue 2580

- src/identity-providers/add/DetailSettings.tsx
> use display name instead of alias if set

- public/resources/en/common.json
- src/App.tsx
- src/ForbiddenSection.tsx
- added the needed permission to view current "page"
fixes: #2618
> issue 2618

- cypress/integration/clients_test.spec.ts
- cypress/integration/realm_settings_client_policies_test.spec.ts
- cypress/support/pages/admin_console/Masthead.ts
- cypress/support/pages/admin_console/manage/RoleMappingTab.ts
- src/clients/scopes/ClientScopes.tsx
Add Service Account Tests, fix skipped test and alert notification message
> Add Service Account Tests

- cypress/integration/group_test.spec.ts
- src/clients/authorization/policy/Group.tsx
- src/components/dynamic/GroupComponent.tsx
- src/components/group/GroupPickerDialog.tsx
- src/groups/GroupTable.tsx
- src/realm-settings/DefaultGroupsTab.tsx
- src/user/UserForm.tsx
- src/user/UserGroups.tsx
There was a comment on the group move test that the test didn't work.
In fact, the app didn't work fixed the test and the app.
Now it tests 2 scenarios moving a group to the root and moving it back.
> fixed the group move test by fixing the app

- src/realm-settings/user-profile/AttributesGroupTab.tsx
> fixed translations

- src/identity-providers/IdentityProvidersSection.tsx
> change to only use alias in list

- src/realm-settings/SessionsTab.tsx
> Fixes the hiding of offline session max

- src/realm-settings/NewAttributeSettings.tsx
> value can be undefined see "local-date"

- src/App.tsx
- src/context/server-info/ServerInfoProvider.tsx
- src/i18n.ts
> throw error when server context can't be loaded

- src/i18n.ts
> added missing namespace

- cypress/integration/authentication_test.spec.ts
- cypress/support/pages/admin_console/manage/authentication/DuplicateFlowModal.ts
- cypress/support/pages/admin_console/manage/authentication/FlowDetail.ts
- src/authentication/DuplicateFlowModal.tsx
- src/authentication/FlowDetails.tsx
- src/authentication/components/FlowRequirementDropdown.tsx
- src/authentication/components/FlowRow.tsx
> created more tests for the authentication flow

- cypress/integration/authentication_test.spec.ts
- src/authentication/FlowDetails.tsx
moved button to top toolbar
fixes: #2313
> issue 2313

- src/clients/advanced/SaveReset.tsx
> removed console.log

- src/groups/SearchGroups.tsx
> removed unnessary `/search` from url

- public/resources/en/clients-help.json
- public/resources/en/clients.json
- src/clients/ClientDetails.tsx
- src/clients/advanced/AdvancedSettings.tsx
> added missing default field

- src/clients/ClientSettings.tsx
> removed logout settings for saml

- src/sessions/SessionsTable.tsx
added ipAddress column
fixes: #2674
> issue 2674

- public/resources/en/sessions.json
- src/sessions/SessionsTable.tsx
- src/user/UserSessions.tsx
> added logout all sessions to user session tab

- public/resources/en/dynamic.json
- src/identity-providers/add/AddMapper.tsx
- src/identity-providers/add/AddMapperForm.tsx
> mappers are now sorted

- src/realm-settings/EmailTab.tsx
> Use correct field for authentication of e-mail server

- src/clients/AdvancedTab.tsx
- src/clients/ClientSettings.tsx
- src/clients/add/AccessSettings.tsx
- src/clients/add/LoginSettingsPanel.tsx
- src/clients/add/LogoutPanel.tsx
- src/clients/advanced/ClusteringPanel.tsx
- src/clients/advanced/RevocationPanel.tsx
- src/components/alert/Alerts.tsx
- src/components/scroll-form/ScrollForm.tsx
- src/identity-providers/add/DetailSettings.tsx
- src/realm-settings/NewAttributeSettings.tsx
- src/user-federation/UserFederationLdapSettings.tsx
as a consequence fixed issue:
fixes: #2686
> refactored scroll form so to easier hide section

- src/components/bread-crumb/GroupBreadCrumbs.tsx
- src/groups/GroupsSection.tsx
- src/groups/SearchGroups.tsx
> improved search sub links / breadcrumbs

- src/components/routable-tabs/RoutableTabs.tsx
- src/groups/GroupsSection.tsx
> fixed insets

- src/clients/ClientDetails.tsx
> Move 'Sessions' tab before 'Permissions' tab

- src/components/scroll-form/form-panel.css
- src/index.css
> Remove arbitrary margin from bottom of forms

- src/authentication/components/DraggableTable.tsx
- src/realm-settings/user-profile/AttributesTab.tsx
> Disallow deletion of restricted user attributes

- src/client-scopes/add/MapperDialog.tsx
> only select items from the list not rows

- src/realm-settings/security-defences/HeadersForm.tsx
> Link security header help text to MDN

- public/resources/en/events.json
- src/events/AdminEvents.tsx
- src/events/EventsSection.tsx
> Add a 'Reset' button the the events search form

- src/i18n.ts
Relates to https://github.com/keycloak/keycloak/issues/11851
> #11851 Use new parameter useRealmDefaultLocaleFallback when fetching the realm localization texts

- src/components/help-enabler/HelpHeader.tsx
- src/components/help-enabler/help-header.css
> added tag to make sure we override

- public/resources/fr/users.json
> update french translations

- src/clients/add/LogoutPanel.tsx
> added padding to scroll under save button

- src/PageNav.tsx
> Changed to use NavLink to fix urls based on router

- public/resources/en/realm-settings.json
- src/realm-settings/LoginTab.tsx
> changed error and success message

- public/resources/en/realm-settings.json
- src/realm-settings/NewAttributeSettings.tsx
- src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> fixed required for + localization

- src/authentication/components/AddFlowDropdown.tsx
- src/authentication/components/EditFlow.tsx
- src/authentication/components/FlowRow.tsx
> added way to edit flow name and description

- src/realm-settings/NewAttributeSettings.tsx
- src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> added groups to dropdown menu

- snowpack.config.mjs
> added some production build options

- src/user-federation/custom/CustomProviderSettings.tsx
fixes creating custom providers
> use realm id instead of realm name as parentId

- src/client-scopes/details/ScopeForm.tsx
> added missing id attribute

- src/components/group/GroupPickerDialog.tsx
- src/components/view-header/ViewHeader.tsx
- src/realm-settings/AddMessageBundleModal.tsx
- src/realm-settings/NewClientPolicyForm.tsx
> fixed ids for axa

- src/authentication/RequiredActions.tsx
- src/authentication/components/AddFlowDropdown.tsx
- src/authentication/components/FlowHeader.tsx
- src/authentication/components/FlowRow.tsx
- src/authentication/components/FlowTitle.tsx
- src/authentication/policies/Policies.tsx
- src/authentication/policies/PolicyRow.tsx
- src/authentication/policies/WebauthnPolicy.tsx
- src/util.ts
> added aria-labels

- cypress/e2e/partial_import_test.spec.ts
- cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts
> added test for partial import clear button

- src/components/group/GroupPickerDialog.tsx
> added aria-label

- src/clients/add/LogoutPanel.tsx
This is what I meant @ssilvert
> fixed type

- cypress/e2e/user_fed_ldap_test.spec.ts
> changed public ldap to one that is still works

- package-lock.json
- package.json
- public/resources/en/clients-help.json
- public/resources/en/dynamic.json
- src/clients/authorization/AuthorizationDataModal.tsx
- src/clients/authorization/AuthorizationEvaluate.tsx
- src/clients/authorization/evaluate/Results.tsx
- src/clients/authorization/policy/User.tsx
- src/components/client/ClientSelect.tsx
- src/components/dynamic/ClientSelectComponent.tsx
- src/components/users/UserSelect.tsx
> refactored a little and fixed bug

- src/identity-providers/IdentityProvidersSection.tsx
- src/identity-providers/ManageOrderDialog.tsx
- src/user-federation/ManagePriorityDialog.tsx
> fix order dialogs

- src/PageNav.tsx
> added `<li>`

- package-lock.json
- package.json
> Lock Snowpack to older version to prevent compilation issues

- src/realm-settings/NewClientPolicyForm.tsx
- src/realm-settings/PoliciesTab.tsx
Close #1879 and Close #1903
See #1879 and #1903
Realm Settings -> Client Policies -> Policies
#1879 configure via JSON Editor 
#1903 click on existing client policy
> Button Styling changes (Issue 1879 and Issue 1903)

- cypress/e2e/authentication_test.spec.ts
- cypress/support/pages/admin_console/components/ActionToolbarPage.ts
- cypress/support/pages/admin_console/manage/authentication/DuplicateFlowModal.ts
- cypress/support/pages/admin_console/manage/authentication/FlowDetail.ts
- src/authentication/components/FlowRow.tsx
- src/authentication/components/FlowTitle.tsx
- src/authentication/form/NameDescription.tsx
> added flow edit details test

- package-lock.json
- package.json
- scripts/import-client.mjs
Updates to the latest version of the Admin Client, which is now distributed in the ES module format.
> Use ES module version of the Admin Client

- src/components/alert/AlertPanel.tsx
- src/components/alert/Alerts.tsx
> made automatic removal of alerts more robust

- src/realm-settings/realm-settings-section.css
Close #1774
See #1774
Realm settings -> Email
> Realm settings > email: layout issues fixed (Issue 1774)

- src/clients/authorization/policy/ClientScope.tsx
- src/clients/authorization/policy/Group.tsx
- src/clients/authorization/policy/PolicyDetails.tsx
- src/clients/authorization/policy/Role.tsx
- src/clients/authorization/policy/policy-details.css
Close #2114
See #2114
Clients -> Choose Client -> Enable Permissions -> Choose scope-name -> Cancel -> Authorization Policies -> Create Policy -> Choose Client Scope/ Role/ Group -> Add Client Scope/ Role/ Group
> fine-tuning in policy details page (issue 2114)

- README.md
Add a section with the policy statement mentioned under the Transparency section in https://source.redhat.com/departments/it/it-information-security/data_privacy/pia_wiki/cypressio_dashboard_privacy_impact_recommendations
1. Text is present in the README.
> README update (project policy)

- cypress/e2e/clients_test.spec.ts
- cypress/support/pages/admin_console/manage/clients/client_details/tabs/AdvancedTab.ts
Add missing tests for the clustering nodes
> Add clustering nodes tests

- src/clients/scopes/ClientScopes.tsx
> added confirm dialog

- src/components/keycloak-card/KeycloakCard.tsx
- src/identity-providers/IdentityProvidersSection.tsx
- src/user-federation/UserFederationSection.tsx
> make sure cards are clickable by screen readers

- src/authentication/BindFlowDialog.tsx
> fixed selections values

- public/resources/en/realm-settings.json
> Fix forgotPassword label in realm settings

- src/identity-providers/add/OIDCAuthentication.tsx
> default values, it used id instead of value

- src/components/dynamic/PasswordComponent.tsx
- src/components/dynamic/components.ts
- src/user-federation/custom/CustomProviderSettings.tsx
> added dynamic properties to custom provider

- public/resources/en/clients.json
- public/resources/en/common-help.json
- src/clients/import/ImportForm.tsx
- src/i18n.ts
- src/identity-providers/add/OpenIdConnectSettings.tsx
- src/identity-providers/add/SamlConnectSettings.tsx
- src/utils/getAuthorizationHeaders.ts
> added posibilty to import saml xml

- src/clients/ClientSettings.tsx
- src/identity-providers/add/AdvancedSettings.tsx
Close #2983 
See #2983
Identity Providers ->Provider Details -> Settings, scroll to bottom
> content is no longer blocked by toolbar (Issue 2983)

- src/realm/add/NewRealmForm.tsx
> fixed realm import file

- src/clients/routes/Client.ts
- src/clients/scopes/ClientScopes.tsx
> changed the access to the page to query

- src/components/multi-line-input/MultiLineInput.tsx
> only make first button disabled

- src/utils/joinPath.test.ts
- src/utils/joinPath.ts
Adds a utility function to join paths, which is need for another future PR.
> Add utility function to join paths

- src/components/key-value-form/key-value-convert.test.ts
- src/components/key-value-form/key-value-convert.ts
> now saves duplicate keys as arrays

- src/realm-settings/LocalizationTab.tsx
- removed the constrained of always having English
> removed the constrained of always having English

- src/realm-settings/ClientProfileForm.tsx
> fixed button variant

- src/i18n.ts
> fixed path for loading resource bundles

- src/user/UserCredentials.tsx
> fix spacing table & navigation

- cypress/e2e/clients_saml_test.spec.ts
- cypress/e2e/group_test.spec.ts
- cypress/e2e/realm_test.spec.ts
- cypress/e2e/user_fed_ldap_hardcoded_mapper_test.spec.ts
- cypress/e2e/user_fed_ldap_test.spec.ts
- cypress/e2e/users_test.spec.ts
- cypress/support/pages/admin_console/Masthead.ts
- cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
Fixes some failing and flaky tests. Also some fixed some skipped tests. Related to #2664
> Fix failing and flaky tests

- src/clients/advanced/ApplicationUrls.tsx
- src/clients/advanced/FineGrainOpenIdConnect.tsx
- src/clients/advanced/FineGrainSamlEndpointConfig.tsx
> adding application urls to saml advanced tab

- cypress.config.mjs
- cypress/component/ConfirmDialogModal.cy.tsx
- cypress/support/component-index.html
- cypress/support/component.ts
> initial version of cypress component test

- src/clients/add/AccessSettings.tsx
> root url hint text appears (issue 3096)

- src/clients/ClientsSection.tsx
> Fix homepage URL rendering in client list

- src/components/view-header/ViewHeader.tsx
See #3108. Not sure if is the most right solution, but it works.
> changed header translation

- public/resources/en/users.json
- src/user/UserIdentityProviderLinks.tsx
- src/user/user-section.css
Fixes for #1756 , #1754 & #1753
> Fixes identity provider section

- src/authentication/AuthenticationSection.tsx
- src/authentication/FlowDetails.tsx
> show name as it is stored

- .github/workflows/cypress.yml
> faster maven execution

- cypress/e2e/clients_saml_test.spec.ts
- src/clients/keys/SamlKeys.tsx
> converts attribute names

- cypress/e2e/clients_test.spec.ts
- cypress/e2e/realm_roles_test.spec.ts
- keycloak-theme/pom.xml
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AdminUIExtendedResource.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AdminUIRestEndpointProvider.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/ClientRole.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/ClientRoleRepresentation.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.kt
- keycloak-theme/src/main/resources/META-INF/services/org.keycloak.services.resources.admin.ext.AdminRealmResourceProviderFactory
- src/components/role-mapping/AddRoleMappingModal.tsx
- src/components/role-mapping/queries.ts
- src/components/role-mapping/resource.ts
> initial version of an endpoint

- src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
> small fix in attribute naming

- src/clients/ClientsSection.tsx
- src/utils/client-url.test.ts
- src/utils/client-url.ts
> refactored and introduced test for client url

- cypress/e2e/users_test.spec.ts
- cypress/support/pages/admin_console/manage/users/UsersPage.ts
- cypress/support/pages/admin_console/manage/users/user_details/UserDetailsPage.ts
- cypress/support/pages/admin_console/manage/users/user_details/tabs/IdentityProviderLinksTab.ts
- cypress/support/util/AdminClient.ts
> New Users IdP linking account tests

- cypress/e2e/client_scopes_test.spec.ts
- cypress/support/pages/admin_console/manage/client_scopes/CreateClientScopePage.ts
- src/client-scopes/details/ScopeForm.tsx
- src/clients/add/LoginSettingsPanel.tsx
> Enable client consent text when client consent is enabled

- public/resources/en/identity-providers-help.json
- public/resources/en/identity-providers.json
- src/identity-providers/add/AddIdentityProvider.tsx
- src/identity-providers/add/DetailSettings.tsx
- src/identity-providers/component/ExtendedFieldsForm.tsx
> Add extended fields for identity providers

- src/realm-roles/RealmRoleTabs.tsx
Closes https://github.com/keycloak/keycloak-ui/issues/3157
Replace in URL after deletion was not correct
1. Go to Realm Roles.
2. Add some associated roles.
3. Remove all associated roles.
> Fix redirection on remove all associated roles

- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingProvider.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AvailableRoleMappingResource.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingProvider.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/ClientRole.kt
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.kt
- keycloak-theme/src/main/resources/META-INF/services/org.keycloak.services.resources.admin.ext.AdminRealmResourceProviderFactory
- src/components/role-mapping/AddRoleMappingModal.tsx
- src/components/role-mapping/RoleMapping.tsx
- src/components/role-mapping/queries.ts
- src/components/role-mapping/resource.ts
> created endpoint for effective client roles

- .gitignore
> fix ignore cypress downloads

- apps/admin-ui/cypress/e2e/authentication_test.spec.ts
- apps/admin-ui/src/authentication/DuplicateFlowModal.tsx
Close #2833
Add redirection to new flow detail after duplicate
1. Go to Authentication.
2. Duplicate a flow.
3. Once save is done you are redirected to new flow detail.
> Redirect to flow detail after duplicate

- apps/admin-ui/src/authentication/components/DraggableTable.tsx
- apps/admin-ui/src/components/alert/Alerts.tsx
- apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
- apps/admin-ui/src/util.ts
- package-lock.json
- package.json
Upgrades TypeScript to the latest version and applies the necessary migrations.
> Upgrade TypeScript to latest version

- apps/admin-ui/src/sessions/RevocationModal.tsx
- apps/admin-ui/src/sessions/SessionsSection.tsx
> removed unused code

- apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/ProviderBaseGeneralSettingsPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderFacebookGeneralSettings.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderGithubGeneralSettings.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderGoogleGeneralSettings.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderOpenshiftGeneralSettings.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderPaypalGeneralSettings.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderStackoverflowGeneralSettings.ts
> new custom identity providers tests

- apps/admin-ui/public/resources/en/clients.json
- apps/admin-ui/src/clients/authorization/Permissions.tsx
> Add explainer for disabled 'Create permission' dropdown

- apps/admin-ui/src/user-federation/UserFederationSection.tsx
> added fix for missing enabled flag

- apps/admin-ui/src/user/UsersSection.tsx
> change button style for better visibility

- apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
Searching for providers/ non existent providers
Deleting provider from item details
Fail to add more than one github provider
> idp testing

- apps/admin-ui/public/resources/en/realm-settings.json
Fixed #2735 
See #2735 
Go to the events section user events tab and search on `eventTypes`
> added name and description for certain event types

- apps/admin-ui/cypress/e2e/group_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/groups/group_details/GroupDetailPage.ts
- apps/admin-ui/src/components/permission-tab/PermissionTab.tsx
groups -> permissions, enabling and disabling permissions
> group -> permission tests

- apps/admin-ui/src/events/AdminEvents.tsx
- apps/admin-ui/src/events/EventsSection.tsx
> Use date picker for events filtering

- apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
- apps/admin-ui/src/realm-settings/ExecutorForm.tsx
> changed to use form to store executors

- apps/admin-ui/src/components/keycloak-card/ClickableCard.tsx
- apps/admin-ui/src/components/keycloak-card/KeycloakCard.tsx
- apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
- apps/admin-ui/src/identity-providers/icons/FontAwesomeIcon.tsx
- apps/admin-ui/src/user-federation/UserFederationSection.tsx
> new clickable card that behaves like a button

- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
- apps/admin-ui/src/components/dynamic/RoleComponent.tsx
- apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
> the role picker no longer queries all clients

- apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
> do not convert empty object acr.loa.map to array

- apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
- apps/admin-ui/src/realm-settings/event-config/EventConfigForm.tsx
- apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
> added adminEventsExpiration to the form

- apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
> remove 2 char restriction

- apps/admin-ui/src/clients/ClientDetails.tsx
- apps/admin-ui/src/components/download-dialog/DownloadDialog.tsx
> use arrayBuffer for zip files

- apps/admin-ui/src/clients/authorization/policy/Time.tsx
> made begin and end date required

- apps/admin-ui/public/resources/en/clients.json
- apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx
> Show policy type in form title

- apps/admin-ui/public/resources/en/authentication-help.json
- apps/admin-ui/public/resources/en/authentication.json
- apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
DRAFT: Changes can be merged after merging https://github.com/keycloak/keycloak/pull/13867
> Reuse of token in TOTP is possible

- apps/admin-ui/public/resources/en/authentication.json
- apps/admin-ui/src/authentication/AuthenticationSection.tsx
- apps/admin-ui/src/authentication/BindFlowDialog.tsx
- apps/admin-ui/src/authentication/FlowDetails.tsx
- apps/admin-ui/src/authentication/components/UsedBy.tsx
- apps/admin-ui/src/components/role-mapping/resource.ts
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementProvider.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/Authentication.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/AuthenticationMapper.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/ClientRole.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/RoleMapper.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/UsedBy.java
- keycloak-theme/src/main/resources/META-INF/services/org.keycloak.services.resources.admin.ext.AdminRealmResourceProviderFactory
> created endpoint to query authentication section with used by information

- keycloak-theme/pom.xml
> Add release profile attaching javadoc and sources

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/src/clients/AdvancedTab.tsx
- apps/admin-ui/src/clients/advanced/FineGrainSamlEndpointConfig.tsx
fixes: #3308
Co-authored-by: Jon Koops <jonkoops@gmail.com>
> fixed how we reset the fields on advanced tab

- apps/admin-ui/cypress/e2e/group_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/ListingPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/groups/group_details/GroupDetailPage.ts
- apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
check empty state
assign role from empty state
show and search roles
check/uncheck "Inherited roles" option
remove role
> group role mapping tests

- apps/admin-ui/public/resources/en/identity-providers-help.json
- apps/admin-ui/public/resources/en/identity-providers.json
- apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
> added pass max age field

- apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
- apps/admin-ui/src/components/users/UserSelect.tsx
> fixed to use field that exists

- apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
> removed validation of form

- apps/admin-ui/public/resources/en/user-federation-help.json
- apps/admin-ui/public/resources/en/user-federation.json
- apps/admin-ui/src/user-federation/ldap/LdapSettingsSynchronization.tsx
> added sync registrations field

- apps/admin-ui/src/components/role-mapping/resource.ts
- apps/admin-ui/src/user/UsersSection.tsx
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersProvider.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/model/BruteUser.java
- keycloak-theme/src/main/resources/META-INF/services/org.keycloak.services.resources.admin.ext.AdminRealmResourceProviderFactory
> added brute force status to user search

- apps/admin-ui/src/authentication/components/modals/AddStepModal.tsx
> added search bar

- apps/admin-ui/src/clients/authorization/policy/Role.tsx
> fixed showing realm roles

- apps/admin-ui/public/resources/en/clients.json
- apps/admin-ui/src/clients/authorization/Resources.tsx
> added empty state

- apps/admin-ui/src/components/dynamic/PasswordComponent.tsx
- apps/admin-ui/src/user-federation/custom/CustomProviderSettings.tsx
> convert config strings into string[]

- apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
> use alias for title name

- apps/admin-ui/src/clients/authorization/ScopePicker.tsx
- apps/admin-ui/src/clients/authorization/ScopeSelect.tsx
> keep selected policies not just ids

- apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
> changed unspecified to ""

- apps/admin-ui/src/identity-providers/add/AddMapper.tsx
> convert claims back to object

- apps/admin-ui/src/authentication/AuthenticationSection.tsx
- apps/admin-ui/src/authentication/FlowDetails.tsx
> `client-flow` can also be bound

- apps/admin-ui/cypress/e2e/identity_providers_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts
github provider details testing
> github provider details testing

- apps/admin-ui/src/components/json-file-upload/patternfly/FileUpload.tsx
> added null check for chrome

- apps/admin-ui/src/clients/add/SamlSignature.tsx
> convert attribute name to form

- apps/admin-ui/src/realm-settings/realm-settings-section.css
- apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
> added some css to fix alignment

- apps/admin-ui/cypress/support/pages/admin_console/manage/users/user_details/UserDetailsPage.ts
- apps/admin-ui/src/user/UserForm.tsx
- apps/admin-ui/src/user/UsersTabs.tsx
> move enable / disable to header

- apps/admin-ui/src/client-scopes/routes/Mapper.ts
> fixed route

- apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> is paginated in for both types

- apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
- apps/admin-ui/src/dashboard/Dashboard.tsx
- apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
> remove first char upper case for realm

- apps/admin-ui/src/groups/Members.tsx
> add option to include subgroup users to empty

- apps/admin-ui/cypress/e2e/authentication_test.spec.ts
- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
- apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
- apps/admin-ui/cypress/e2e/users_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/Masthead.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/AttributesTab.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/ClientRolesTab.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesMappersTab.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/tabs/ClientScopesTab.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
Fixes flaky and some failing tests.
> Fix flaky tests

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts
- apps/admin-ui/cypress/e2e/users_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesMappersTab.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
Remaining fixes for failing tests
> Additional test fixes

- apps/admin-ui/src/realm-settings/LocalizationTab.tsx
> use combined locales of all themes

- apps/admin-ui/cypress/e2e/group_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/groups/GroupPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/groups/SearchGroupPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/groups/group_details/GroupDetailPage.ts
- apps/admin-ui/public/resources/en/groups.json
- apps/admin-ui/src/components/bread-crumb/PageBreadCrumbs.tsx
- apps/admin-ui/src/components/group/GroupPickerDialog.tsx
- apps/admin-ui/src/components/table-toolbar/TableToolbar.tsx
- apps/admin-ui/src/context/auth/admin-ui-endpoint.ts
- apps/admin-ui/src/groups/GroupTable.tsx
- apps/admin-ui/src/groups/GroupsSection.tsx
- apps/admin-ui/src/groups/components/GroupToolbar.tsx
- apps/admin-ui/src/groups/components/GroupTree.tsx
> combine tree view and list for groups

- apps/admin-ui/src/components/dynamic/FileComponent.tsx
> the missing type attribute broke the component

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/tabs/AdvancedTab.ts
- apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
- apps/admin-ui/src/clients/advanced/AuthenticationOverrides.tsx
- apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
Certain parts of testing has been commented out as I ran into issue #3475 while writing tests.
> advanced client details testing

- apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
as this form is dynamic we should unregister the controls
> added missing shouldn't unregister

- apps/admin-ui/src/client-scopes/routes.ts
- apps/admin-ui/src/client-scopes/routes/ClientScope.ts
Last review I reverted part of the fix, but that part was crucial. This is a better fix
> issue 3406

- apps/admin-ui/src/user/user-credentials/ResetPasswordDialog.tsx
> when ldap there are no credentials in keycloak

- apps/admin-ui/src/components/client/ClientSelect.tsx
> added "none" option to client select

- apps/admin-ui/src/user/UsersSection.tsx
> fixed defaults

- .github/ISSUE_TEMPLATE/bug.yml
It can be useful to know what browser a user used to reproduce the issue @stianst
> added browser field to the issue template

- apps/admin-ui/src/clients/keys/Keys.tsx
> added refresh after generate and update

- apps/admin-ui/package.json
- apps/admin-ui/src/components/help-enabler/HelpHeader.tsx
- apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
- package-lock.json
so users don't have to set it each time
> help toggle and page default in local storage

- apps/admin-ui/src/clients/add/LogoutPanel.tsx
- apps/admin-ui/src/index.css
> added padding on forms so action buttons don't overlap

- apps/admin-ui/public/resources/en/identity-providers-help.json
- apps/admin-ui/public/resources/en/identity-providers.json
- apps/admin-ui/src/identity-providers/component/ExtendedFieldsForm.tsx
> added missing profileProjection field

- apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
- apps/admin-ui/cypress/e2e/realm_settings_tabs_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
- apps/admin-ui/src/realm-settings/EmailTab.tsx
Making a new PR based on #3516 
Made this PR so commit history won't be messy.
EDIT:
Test passes locally but seems to fail in the dashboard
> tests for realm setting tabs

- apps/admin-ui/public/resources/en/common.json
- apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> added empty state for assign roles

- .github/issue_template.md
This might reduce the amount of reported issues that have already been fixed, but not released.
> Ask users to test nightly before reporting issue

- apps/admin-ui/src/clients/authorization/NewPolicyDialog.tsx
Closes https://github.com/keycloak/keycloak-ui/issues/2032
1. Go to `Clients > Client details > Authorization > Policies > Create policy`.
2. Verify that the policies are sorted alphabetically.
> Added alphabetically listing the policies - Issue-2032

- apps/admin-ui/public/resources/en/realm-settings.json
- apps/admin-ui/src/realm-settings/LocalizationTab.tsx
> added missing delete action

- apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
> keep existing config we don't have fields for

- apps/admin-ui/src/clients/authorization/AuthorizationEvaluateResourcePolicies.tsx
> fixed cannot read from undefined

- apps/admin-ui/public/resources/en/realm-settings.json
- apps/admin-ui/src/realm-settings/EmailTab.tsx
> added progress spinner to email test button

- apps/admin-ui/cypress/support/pages/admin_console/ListingPage.ts
- apps/admin-ui/public/resources/en/client-scopes.json
> changed label text to OpenID Connect

- apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
- apps/admin-ui/src/clients/keys/SamlImportKeyDialog.tsx
> added PEM format for SAML

- apps/admin-ui/public/resources/en/dynamic.json
see: https://github.com/keycloak/keycloak/issues/9364
> added translations in new console

- apps/admin-ui/src/clients/authorization/Policies.tsx
fixes: #3602
https://github.com/keycloak/keycloak-nodejs-admin-client/pull/572 will fix the type
> added check for nothing found

- apps/admin-ui/src/context/auth/AdminClient.tsx
This reverts #3471. See https://github.com/keycloak/keycloak-ui/pull/3471#issuecomment-1265835434 for motivation.
> Stop using Keycloak config endpoint for Admin Client

- apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> sort client roles based on clientId and role name

- apps/admin-ui/public/resources/en/groups.json
- apps/admin-ui/src/groups/GroupTable.tsx
- apps/admin-ui/src/groups/components/GroupTree.tsx
> added more options in the context menu

- apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
> escape internal output

- apps/admin-ui/cypress/e2e/identity_providers_saml_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/identity_providers/social/ProviderSAMLSettings.ts
- apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
Skipped over some functionality as it is already being tested in IDP OIDC
> IDP SAML testing

- apps/admin-ui/public/resources/en/groups.json
- apps/admin-ui/src/groups/components/GroupTree.tsx
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/GroupsResource.java
> added exact search checkbox

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/EffectiveRoleMappingResource.java
> we want all roles not just the direct roles

- apps/admin-ui/src/components/dynamic/MapComponent.tsx
- apps/admin-ui/src/identity-providers/add/AddMapper.tsx
- updated Map Component to work with JSON
- fixed tests
- 
fixes: #3604
> issue 3604

- apps/admin-ui/src/user-federation/custom/CustomProviderSettings.tsx
- apps/admin-ui/src/user-federation/custom/SyncSettings.tsx
> added sync period settings to custom ui

- apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> added pagination for realm roles

- apps/admin-ui/cypress/e2e/realm_settings_user_profile_tab.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/realm_settings/UserProfile.ts
- apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AddValidatorDialog.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
> do not show enabled and required for email and username

- apps/admin-ui/src/authentication/components/modals/AddSubFlowModal.tsx
> use provider id instead of object

- apps/admin-ui/src/authentication/components/ExecutionConfigModal.tsx
> fixed merging the config

- apps/admin-ui/src/authentication/components/EditFlow.tsx
Refactors the flow form to use v7 of `react-hook-form`, and cleans up the code a little.
> Use `react-hook-form` v7 for edit flow modal

- apps/admin-ui/src/user-federation/UserFederationLdapSettings.tsx
> config can be empty

- apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx
> changed to use the right handler

- apps/admin-ui/src/util.ts
- apps/admin-ui/src/utils/types.ts
Makes the conversion of attribute names (beers) type-safe.
> Make form attribute conversion type-safe

- apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
- apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
- apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
- apps/admin-ui/src/clients/keys/Keys.tsx
> Use cryptoInfo to populate key type dropdowns.

- libs/keycloak-admin-client/src/resources/users.ts
Reopening https://github.com/keycloak/keycloak-nodejs-admin-client/pull/587 
Closes: https://github.com/keycloak/keycloak-ui/issues/3829
> Add pagination typing for listGroups

- apps/admin-ui/src/authentication/components/modals/AddSubFlowModal.tsx
Refactors the sub-flow modal form to use v7 of `react-hook-form`, and cleans up the code a little.
> Use `react-hook-form` v7 for add sub-flow modal

- apps/admin-ui/src/clients/advanced/AddHostDialog.tsx
Refactors the add host dialog form to use v7 of `react-hook-form`, and cleans up the code a little.
> Use `react-hook-form` v7 for add host dialog form

- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/CreateResourcePage.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/tabs/SettingsTab.ts
- apps/admin-ui/src/clients/ClientDetails.tsx
- apps/admin-ui/src/clients/add/AccessSettings.tsx
- apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
- apps/admin-ui/src/clients/advanced/FineGrainOpenIdConnect.tsx
- apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
- apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
- apps/admin-ui/src/components/multi-line-input/multi-line-convert.ts
> added way to convert multi line to string

- apps/admin-ui/src/user/UserProfileFields.tsx
> fixed typo in attribute name

- .github/workflows/cypress.yml
- .github/workflows/main.yml
> Run CI on release branches

- apps/admin-ui/package.json
- apps/admin-ui/public/resources/en/users.json
- apps/admin-ui/src/user/UsersSection.tsx
> Changed `temporarily disabled` to `temporarily locked` status - #1705

- apps/admin-ui/src/user/UsersTabs.tsx
- apps/admin-ui/src/user/user-section.css
Closes #1189 
1. Go to `Users > Add user` and create a new user with a very long username.
2. Select created user from the table.
3. Verify that the username is now wrapping.
> Fixed username not wrapping in `User details` - #1189

- apps/admin-ui/src/clients/keys/Keys.tsx
> convert attribute name in watch

- apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
Close #1897 
Changed the badge into a label
Realm settings -> Client policies -> fapi-1-baseline client profile details
> Added label in Client policies > global profile details heading

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/cypress/e2e/group_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/AttributesTab.ts
Refactoring `asseertRowItemsEqualTo` to `assertRowItemsEqualTo`
> Refactoring `asseertRowItemsEqualTo` to `assertRowItemsEqualTo`

- apps/admin-ui/src/authentication/policies/PasswordPolicy.tsx
- apps/admin-ui/src/authentication/policies/PolicyRow.tsx
* use form state to check dirty
* convert to v7 of react hook form
fixes: #3908
> convert string value to number

- apps/admin-ui/cypress/e2e/users_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin_console/manage/users/UserGroupsPage.ts
Testing search bar and leave groups button
> user groups testing

- apps/admin-ui/src/authentication/AuthenticationSection.tsx
Closes #2765
1. Go to `Authentication >> Flows`.
2. Verify that the items in addition to being listed by type (previous implementation) are now also listed alphabetically as requested in #2765
> Fixed listing flows alphabetically in addition to by type - #2765

- apps/admin-ui/src/clients/authorization/policy/Group.tsx
- apps/admin-ui/src/components/dynamic/GroupComponent.tsx
- apps/admin-ui/src/components/group/GroupPickerDialog.tsx
- apps/admin-ui/src/groups/components/MoveDialog.tsx
- apps/admin-ui/src/user/UserForm.tsx
> use id instead of name to disable

- apps/admin-ui/src/realm-settings/LocalizationTab.tsx
> added fallback for invalid locale

- apps/admin-ui/public/resources/en/clients.json
- apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
- apps/admin-ui/src/clients/advanced/TokenLifespan.tsx
- apps/admin-ui/src/components/time-selector/TimeSelector.tsx
> added inherited option

- apps/admin-ui/src/clients/keys/SamlKeysDialog.tsx
> Wrap `SamlKeysDialog` in `FormProvider`

- apps/admin-ui/src/client-scopes/ClientScopesSection.tsx
- apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
- apps/admin-ui/src/client-scopes/form/ClientScopeForm.tsx
- apps/admin-ui/src/client-scopes/routes/ClientScope.ts
- apps/admin-ui/src/client-scopes/routes/Mapper.ts
> removed type from url, query it

- apps/admin-ui/src/clients/scopes/EvaluateScopes.tsx
- apps/admin-ui/src/components/users/UserSelect.tsx
> changed to use user select component

- apps/admin-ui/cypress/e2e/realm_settings_user_profile_tab.spec.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/UserProfile.ts
- apps/admin-ui/src/realm-settings/user-profile/JsonEditorTab.tsx
> added json test

- apps/admin-ui/src/clients/credentials/ClientSecret.tsx
- apps/admin-ui/src/clients/credentials/Credentials.tsx
> Use `react-hook-form` v7 for client credentials form

- apps/admin-ui/src/components/key-value-form/KeyValueInput.tsx
> added extra null check

- apps/admin-ui/cypress/e2e/identity_providers_saml_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/social/ProviderSAMLSettings.ts
- apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
- apps/admin-ui/src/identity-providers/add/ExtendedNonDiscoverySettings.tsx
> use `NumberInput` instead of input

- apps/admin-ui/vite.config.ts
> activate source maps

- apps/admin-ui/src/user/user-section.css
Closes #1702 
Fixed page:
1. Instruction for setting up the User's consent page is [here](https://docs.google.com/document/d/1lo1nkBG83Qhy4-DHQdka6bLRjK-0-gEK1mxkBRZhWu0/edit#heading=h.vxwf4bh0icng)
2. Once setup is completed, go to `Users >> Select `admin` >> Consents`.
4. Verify that the items display as expected.
> Fine-tuning of User consents page - #1702

- .gitignore
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/AuthenticationManagementResource.java
- keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/BruteForceUsersResource.java
Closes #4073
See #4073
See #4073
N/A
N/A
> Add a META-INF/beans.xml file to enable support for JAX-RS

- apps/admin-ui/public/resources/ca/common.json
- apps/admin-ui/public/resources/de/common.json
- apps/admin-ui/public/resources/en/common.json
- apps/admin-ui/public/resources/es/common.json
- apps/admin-ui/public/resources/ja/common.json
- apps/admin-ui/public/resources/lt/common.json
- apps/admin-ui/public/resources/no/common.json
- apps/admin-ui/public/resources/pt-BR/common.json
- apps/admin-ui/public/resources/ru/common.json
- apps/admin-ui/public/resources/zh-CN/common.json
- apps/admin-ui/src/clients/ClientsSection.tsx
> Added the client name to the client list view to make it easier to read the list

- apps/admin-ui/src/clients/keys/ExportSamlKeyDialog.tsx
- libs/keycloak-admin-client/src/resources/agent.ts
- libs/keycloak-admin-client/src/resources/clients.ts
> generate array buffer for binary

- apps/admin-ui/cypress/e2e/clients_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/tabs/KeysTab.ts
- apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx
- apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx
Removed default values.
Closes #3977
> JKS keystore type available as default option in FIPS mode

- apps/admin-ui/src/clients/import/ImportForm.tsx
> use default attributes in import form

- apps/admin-ui/public/resources/en/dashboard.json
- apps/admin-ui/src/dashboard/Dashboard.tsx
> added memory info and renamed tab

- apps/admin-ui/src/groups/components/GroupTree.tsx
- apps/admin-ui/src/groups/components/group-tree.css
> added tooltip and css to group name

- apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
> only load realms once not onfocus

- apps/admin-ui/src/realm-settings/user-profile/attribute/AddValidatorDialog.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AddValidatorRoleDialog.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeValidations.tsx
> fixed type of validator

- apps/admin-ui/src/realm-settings/NewClientPolicyForm.tsx
> fixed logic

- apps/admin-ui/src/PageNav.tsx
Refactors the `PageNav` component to use the React Router v6 API.
> Upgrade `PageNav` component to React Router v6

- apps/admin-ui/src/clients/keys/SamlKeysDialog.tsx
> changed to react hook form v7

- apps/admin-ui/cypress/support/pages/admin-ui/manage/KeyValueInput.ts
Realm roles intermittent test failure.
https://cloud.cypress.io/projects/j4yhox/runs/5015/test-results/c9d269d5-43af-42fc-bf50-36b36f552f27
I believe the problem is due to this code:
`` cy.findByTestId(`${[this.name](http://this.name/)}[${index}].key`).clear().type(key);``
According to Cypress docs, you can't reliably use an action like `clear()` in the middle of a chain.
See https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried
Just need to run CI many times to see if tests pass.  I can't reliably recreate the problem on its own.
> Try to fix intermittent test failure

- apps/admin-ui/src/identity-providers/add/AdvancedSettings.tsx
- apps/admin-ui/src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
- added none option
- small refactor
fixes: #4085
> added none option to attribute group

- apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Cleans up the `RealmRoleTabs` component  a little by re-using the `toTabs()` function in several places. Also converts the last component to React Router v6.
> Re-use `toTabs()` function in `RealmRoleTabs` component

- apps/admin-ui/src/user/CreateUser.tsx
- apps/admin-ui/src/user/EditUser.tsx
- apps/admin-ui/src/user/UserForm.tsx
> added email verified when user profile enabled

- apps/admin-ui/src/clients/advanced/SaveReset.tsx
- apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
- apps/admin-ui/src/clients/authorization/DecisionStrategySelect.tsx
- apps/admin-ui/src/clients/authorization/Settings.tsx
- apps/admin-ui/src/clients/authorization/policy/Aggregate.tsx
- apps/admin-ui/src/clients/authorization/policy/Client.tsx
- apps/admin-ui/src/clients/authorization/policy/ClientScope.tsx
- apps/admin-ui/src/clients/authorization/policy/Group.tsx
- apps/admin-ui/src/clients/authorization/policy/JavaScript.tsx
- apps/admin-ui/src/clients/authorization/policy/LogicSelector.tsx
- apps/admin-ui/src/clients/authorization/policy/NameDescription.tsx
- apps/admin-ui/src/clients/authorization/policy/PolicyDetails.tsx
- apps/admin-ui/src/clients/authorization/policy/Regex.tsx
- apps/admin-ui/src/clients/authorization/policy/Role.tsx
- apps/admin-ui/src/clients/authorization/policy/Time.tsx
- apps/admin-ui/src/clients/authorization/policy/User.tsx
- apps/admin-ui/src/components/users/hook-form-v7/UserSelect.tsx
> migrated authenticate settings and policy detail

- libs/keycloak-admin-client/README.md
Some links weren't working, others were linking to older keycloak documentatio
links updated
> fix broken links and update old ones

- apps/admin-ui/src/clients/keys/SamlKeys.tsx
> only open the right dialog and not both

- apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
- apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
- apps/admin-ui/src/components/multi-line-input/hook-form-v7/MultiLineInput.tsx
> small optimization for better performance

- apps/admin-ui/public/resources/en/clients-help.json
- apps/admin-ui/public/resources/en/identity-providers-help.json
> Update tooltips for 'Signature algorithm' for SAML client and SAML Identity provider

- apps/admin-ui/public/resources/en/realm-settings-help.json
- apps/admin-ui/public/resources/en/realm-settings.json
- apps/admin-ui/src/realm-settings/TokensTab.tsx
Related to [Keycloak PR](https://github.com/keycloak/keycloak/pull/16156)
> Short verification_uri for Device Authorization Request

- apps/admin-ui/src/components/alert/AlertPanel.tsx
- apps/admin-ui/src/user/CreateUser.tsx
- apps/admin-ui/src/user/EditUser.tsx
- apps/admin-ui/src/user/UserProfileFields.tsx
> parse multiple user profile errors

- apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts
- apps/admin-ui/src/components/role-form/RoleForm.tsx
- apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
> reduced state held and fixed reset

- apps/admin-ui/src/clients/import/ImportForm.tsx
> more robust xml check

- apps/admin-ui/public/resources/en/realm-settings.json
- apps/admin-ui/src/components/dynamic/BooleanComponent.tsx
- apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
> added use column and fixed boolean check

- apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
- apps/admin-ui/src/events/EventsSection.tsx
> always add the detail row to prevent wrong index

- apps/admin-ui/package.json
- apps/admin-ui/src/authentication/components/FlowDiagram.tsx
- apps/admin-ui/src/authentication/components/diagram/ButtonEdge.tsx
- apps/admin-ui/src/authentication/components/diagram/auto-layout.ts
- apps/admin-ui/src/utils/useUpdateEffect.ts
- package-lock.json
See the [migration guide](https://reactflow.dev/docs/guides/migrate-to-v10/) for more information.
> Upgrade `react-flow-renderer` to version 10

- apps/admin-ui/public/resources/en/identity-providers-help.json
- apps/admin-ui/public/resources/en/identity-providers.json
- apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
> Add "Encryption algorithm" option of SAML IDP

- apps/admin-ui/src/user-federation/UserFederationLdapForm.tsx
- apps/admin-ui/src/user-federation/UserFederationLdapWizard.tsx
> Align new admin console with the 'KERBEROS' feature

- apps/admin-ui/src/groups/routes/Groups.tsx
> fixed warning in console

- apps/admin-ui/cypress/e2e/realm_test.spec.ts
- apps/admin-ui/public/resources/en/realm.json
- apps/admin-ui/src/realm-settings/GeneralTab.tsx
- apps/admin-ui/src/realm/add/NewRealmForm.tsx
> added validation on realm name

- apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
> added missing id

- apps/admin-ui/cypress/component/KeyValueInput.cy.tsx
- apps/admin-ui/cypress/e2e/client_authorization_test.spec.ts
- apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
- apps/admin-ui/src/util.ts
> added null check

- apps/account-ui/package.json
- apps/admin-ui/package.json
- libs/keycloak-masthead/package.json
- package-lock.json
Updates to latest versions for PatternFly. Followup to #4248
> Update PatternFly to latest versions

- apps/admin-ui/cypress/e2e/sessions_test.spec.ts
- apps/admin-ui/src/sessions/SessionsSection.tsx
> don't logout current user

- apps/admin-ui/cypress/e2e/authentication_policies_ciba.spec.ts
- apps/admin-ui/cypress/support/forms/Form.ts
- apps/admin-ui/cypress/support/forms/FormValidation.ts
- apps/admin-ui/cypress/support/forms/Select.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/authentication/CIBAPolicyPage.ts
- apps/admin-ui/src/authentication/policies/Policies.tsx
> Add Cypress tests for CIBA policy

- apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx
> changed cert to text-area

- apps/admin-ui/src/authentication/components/FlowDiagram.tsx
> removed empty panel

- apps/admin-ui/public/resources/en/client-scopes-help.json
- apps/admin-ui/src/client-scopes/EditClientScope.tsx
> added help text on role mapping

- apps/account-ui/src/account-security/SigningIn.tsx
Fixes the issues on CI where some imports are no longer resolving as the files that are being imported have been moved.
> Fix broken imports by importing from `ui-shared`

- apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
> added paging slice to filtered table

- apps/admin-ui/src/context/RealmsContext.tsx
Fixes an issue in the `RealmsContext` where the logic inside of the `useFetch` was never executed, and instead circumvented in the `refresh()` method.
> Fix realms fetching in `RealmsContext`

- apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
Immediately closes realm selector when navigation starts (a link is clicked), instead of responding to navigation events. This fixes an issue where the realm selector closes at the wrong time, causing the tests to fail intermittently.
> Immediately close realm selector when navigation starts

- apps/admin-ui/public/resources/en/common.json
- apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
Attempts to improve the performance of the realm selector by memoizing possibly expensive operations such as searching. Also adds a missing label for the loading state.
> Memoize possibly expensive operations in realm selector

- apps/admin-ui/src/PageHeader.tsx
- apps/admin-ui/src/PageNav.tsx
- apps/admin-ui/src/authentication/AuthenticationSection.tsx
- apps/admin-ui/src/client-scopes/ClientScopesSection.tsx
- apps/admin-ui/src/client-scopes/details/MapperList.tsx
- apps/admin-ui/src/clients/ClientsSection.tsx
- apps/admin-ui/src/clients/add/NewClientForm.tsx
- apps/admin-ui/src/clients/authorization/Policies.tsx
- apps/admin-ui/src/clients/authorization/Resources.tsx
- apps/admin-ui/src/clients/authorization/Scopes.tsx
- apps/admin-ui/src/clients/scopes/ClientScopes.tsx
- apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx
- apps/admin-ui/src/events/AdminEvents.tsx
- apps/admin-ui/src/realm-settings/PartialImport.tsx
- apps/admin-ui/src/realm-settings/event-config/AddEventTypesDialog.tsx
- apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx
- apps/admin-ui/src/realm-settings/event-config/EventsTypeTable.tsx
- apps/admin-ui/src/realm-settings/keys/KeysListTab.tsx
- apps/admin-ui/src/sessions/SessionsTable.tsx
- apps/admin-ui/src/user/UserGroups.tsx
> moved components out of body

- apps/admin-ui/src/realm-settings/keys/KeysProvidersTab.tsx
- apps/admin-ui/src/realm-settings/keys/key-providers/KeyProvidersPicker.tsx
> introduced picker dialog

- apps/admin-ui/public/resources/en/identity-providers-help.json
A part of keycloak/keycloak#16762
> feat: support multi hd in GoogleIdentityProvider

- apps/admin-ui/src/realm-settings/keys/key-providers/KeyProviderForm.tsx
> use the form value instead

- apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin-ui/components/TablePage.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/RoleMappingTab.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/ClientScopesPage.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/ClientScopeDetailsPage.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/tabs/MappersTab.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/tabs/ScopeTab.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/tabs/SettingsTab.ts
- apps/admin-ui/cypress/support/pages/admin-ui/manage/client_scopes/client_scope_details/tabs/mappers/MapperDetailsPage.ts
Add Client Scopes mappers tests
> Add Client Scopes mappers tests

- apps/admin-ui/public/resources/en/common.json
- apps/admin-ui/src/components/role-mapping/AddRoleMappingModal.tsx
> always use pagination

- apps/admin-ui/src/clients/authorization/Scopes.tsx
moved loading of resources to expand action
fixes: #4383
> moved loading of resources to row expand

- apps/admin-ui/src/realm-settings/keys/key-providers/KeyProviderForm.tsx
> added onclose to go back to provider list

- apps/admin-ui/src/authentication/components/modals/AddStepModal.tsx
> only show page size amount of items

- apps/admin-ui/src/user/user-credentials/CredentialsResetActionMultiSelect.tsx
> added max height

- apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
- apps/admin-ui/src/clients/authorization/KeyBasedAttributeInput.tsx
> resource no longer required implemented filtering on scope

- apps/admin-ui/public/resources/en/dashboard.json
- apps/admin-ui/src/dashboard/Dashboard.tsx
- apps/admin-ui/src/environment.ts
- keycloak-theme/pom.xml
> remove commit hash from production build

- apps/admin-ui/cypress/e2e/masthead_test.spec.ts
- apps/admin-ui/cypress/support/pages/admin-ui/Masthead.ts
Added some new testcases of masthead section. Also was done some slight refactoring of existing tests and common methods.
> Masthead new tests & refactoring

- apps/admin-ui/src/clients/authorization/KeyBasedAttributeInput.tsx
- apps/admin-ui/src/clients/authorization/ScopePicker.tsx
- apps/admin-ui/src/clients/keys/Certificate.tsx
- apps/admin-ui/src/clients/scopes/GeneratedCodeTab.tsx
- apps/admin-ui/src/components/client/ClientSelect.tsx
- apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
> added labels and ids

- apps/admin-ui/src/user/UserForm.tsx
> fixed `fieldId`

- apps/admin-ui/src/groups/components/GroupTree.tsx
> added label to checkbox

- apps/admin-ui/src/realm-settings/ClientProfileForm.tsx
> added button label

- .github/pull_request_template.md
Closes https://github.com/keycloak/keycloak-ui/issues/4525
N/A
> Updated pull request template to include manual and screen reader checks

- apps/admin-ui/src/components/permission-tab/PermissionTab.tsx
> update permissions tab on switch

- apps/admin-ui/public/resources/en/clients.json
- apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
> added alert to when evaluate fails

- apps/admin-ui/src/clients/authorization/AuthorizationEvaluate.tsx
- apps/admin-ui/src/components/users/UserSelect.tsx
> either roles or user is required

- apps/admin-ui/src/components/group/GroupPickerDialog.tsx
- apps/admin-ui/src/groups/components/GroupTree.tsx
> made groups "browsable" after a search

- apps/admin-ui/src/components/alert/AlertPanel.tsx
- apps/admin-ui/src/components/alert/Alerts.tsx
- apps/admin-ui/src/components/dynamic/MapComponent.tsx
- apps/admin-ui/src/util.ts
- libs/ui-shared/src/alerts/Alerts.tsx
> revert use of randomUUID

- README.md
Add warning about UI repo moving to keycloak/keycloak.
> Add warning about UI repo moving to keycloak/keycloak.

- apps/admin-ui/cypress/support/pages/admin-ui/manage/users/CredentialsPage.ts
- apps/admin-ui/public/resources/en/users.json
- apps/admin-ui/src/clients/add/__tests__/mock-serverinfo.json
- apps/admin-ui/src/context/server-info/__tests__/mock.json
- libs/keycloak-admin-client/src/defs/requiredActionProviderRepresentation.ts
This is UI part backport for https://github.com/keycloak/keycloak/issues/17277
> Change terms_and_condition alias to TERMS_AND_CONDITIONS
