keycloak/keycloak-ui

package.json, public/img_avatar.svg, public/index.css, src/App.tsx, src/PageHeader.tsx, src/auth/keycloak.service.ts, src/components/data-loader/DataLoader.tsx, src/forms/realm/NewRealmForm.tsx, src/messages.json, yarn.lock
This PR implements the following in masthead:
- Adds hamburger icon to show/hide left nav menu
- Hamburger menu replaces nav on smaller screen widths
- Adds regular dropdown for Manage Account/Server Info/Signout
- Adds kabab menu for Manage Account/Server Info/Help/Signout
- Kabab replaces regular menu and help menu on smaller screen widths
- User Avatar
- Change the way brand gets its height
PR also makes changes not really related to masthead:
- Update all patternfly dependencies
- Fix linting errors
=> Implement masthead

yarn.lock
Not sure why this happened, but when I refreshed the code from master and did `yarn install`, it upgraded the yarn.lock as shown.
=> yarn.lock was updated with yarn install

src/client-scopes/add/NewClientScopeForm.tsx, src/clients/add/CapabilityConfig.tsx
Adds `hasNoPaddingTop` to the `FormGroup` of items with a switch or the grid of checkboxes. Fixes are in the new Client (CapabilityConfig step of the wizard) and new Client Scope forms.
Fixes #113
=> Fixes vertical alignment of forms with switches

src/components/list-empty-state/ListEmptyState.tsx
Secondary actions in ListEmptyState.tsx is an optional prop.  This fix updates the code to make it optional, so that secondary actions are available when they are needed on specific pages.
Here's an example:
https://marvelapp.com/prototype/f0e8fih/screen/72043135
=> Fixed build by making secondaryActions optional

src/components/view-header/ViewHeader.tsx, src/stories/ViewHeader.stories.tsx
This adds props to the ViewHeader to pass in link text and a url, which will be appended to the subKey text.
Added to allow for a link in the help text of a header, as shown here: https://marvelapp.com/prototype/ecjc94b/screen/72071043
=> adds optional link to the subkey of a view header

src/clients/ClientSettings.tsx, src/components/view-header/ViewHeader.tsx, src/stories/ViewHeader.stories.tsx
Fixes #171 
The action menu should have been a dropdown rather than select, and a dropdown allows a right alignment, so this fixes the overflow off the right side as well as correcting the semantics of the element.
To verify, look at the ViewHeader story and also the Client settings page (actions menu in the header)
=> Change list view header action menu from select to dropdown

public/keycloak.json, src/components/realm-selector/RealmSelector.tsx, src/context/auth/keycloak.ts
Need to be able to develop and test when user logs in using a realm other than master.
The mechanism for determining the realm and the auth URL will need to change as we figure out how this is going to be deployed.  So this is a temporary fix.
You can now go to admin console with http://localhost:8080/?realm=test
1. Create a realm called "test"
2. Add a user to test realm
3. Give the user permissions using realm-management client roles
4. Optional step: Set up fine grained permissions
5. http://localhost:8080/?realm=test
6. Log in.
=> Allow login to different realms using query param

jest.setup.js, package.json, src/PageNav.tsx, src/clients/ClientDescription.tsx, src/clients/ClientSettings.tsx, src/clients/add/CapabilityConfig.tsx, src/components/form-access/FormAccess.tsx, src/components/form-access/__tests__/FormAccess.test.tsx, src/components/form-access/__tests__/__snapshots__/FormAccess.test.tsx.snap, src/components/multi-line-input/MultiLineInput.tsx, src/context/whoami/__tests__/WhoAmI.test.tsx, src/context/whoami/__tests__/mock-whoami.json, src/route-config.ts, yarn.lock
Possible way to implement how to change the input fields based on access rights
This is a poc to get some feedback it's not intented to merge as is
Have a look at the client settings screen when you don't hve the "manage-clients" role 3 field should be disabled
=> Change the input fields based on access rights

src/clients/ClientDetails.tsx, src/clients/ClientSettings.tsx, src/clients/credentials/ClientSecret.tsx, src/clients/credentials/Credentials.tsx, src/clients/credentials/SignedJWT.tsx, src/clients/credentials/X509.tsx, src/clients/help.json, src/clients/messages.json, src/common-messages.json, src/components/confirm-dialog/ConfirmDialog.tsx, src/components/confirm-dialog/__tests__/__snapshots__/ConfirmDialog.test.tsx.snap, src/components/multi-line-input/MultiLineInput.tsx, src/context/server-info/ServerInfoProvider.tsx, src/route-config.ts, src/util.ts
Added credentials tab [marvel](https://marvelapp.com/prototype/695h94c/screen/72265889)
1. Go to client details
1. Make the client "public"
1. The new credentials tab will appear
-->
Setting the client to see the credentials tab:
=> Added the credentials tab

src/client-scopes/messages.json, src/clients/__tests__/__snapshots__/ClientList.test.tsx.snap, src/clients/messages.json, src/components/bread-crumb/PageBreadCrumbs.tsx, src/components/bread-crumb/__tests__/PageBreadCrumbs.test.tsx, src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap
only show breadcrumb when there are 2 levels 
renamed the list clients and client scopes
[see marvel design](https://marvelapp.com/prototype/4bi07ca/section/1014937)
=> removed "Home" from navigation

src/stories/UserFedKerberosSettings.stories.tsx, src/user-federation/KerberosSettingsCache.tsx, src/user-federation/KerberosSettingsRequired.tsx, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/help.json, src/user-federation/messages.json
APPDUX-540 https://issues.redhat.com/browse/APPDUX-540
This lays out the sections in the User Federation Kerberos Settings. It is NOT tied to data nor are controls like switches and dropdowns operational.
This is intended to lay out the page and establish the structure for future work.
This can only be viewed in Storybook. Find it under "User Federation LDAP Settings Tab". It can be compared to this mockup: https://marvelapp.com/prototype/ecjc94b/screen/72098368
=> User federation Kerberos settings wip

src/components/keycloak-card/KeycloakCard.tsx, src/user-federation/UserFederationSection.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/213
Fixes three issues:
- Return from REST call to get enabled/disabled was not handled correctly as an array
- Disabled label was displaying as blue instead of gray as per spec
- Add new provider dropdown was not populating with items once separate card component was created 
In the legacy Keycloak Admin Console UI:
1. Select Configure > User Federation and select kerberos or ldap from the Add provider dropdown.
2. Enter the information for a new provider... just use placeholder text in the required fields, it's not verified.
3. Repeat steps 1-2 to create a second card, but this time, make sure to set the Enabled toggle to OFF.
In the new Keycloak Admin Console:
1. Verify that one of the cards is labeled correctly as Enabled and the …
=> Fix disabled label for user fed card view

src/client-scopes/add/MapperDialog.tsx, src/client-scopes/add/__tests__/MapperDialog.test.tsx, src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap
fixes: #210
client scope -> client scope details -> mapping -> add build in mapper -> click "Add"
open this dialog again and press 'X'
=> fixed x and empty select on dialog

src/client-scopes/add/RoleMappingForm.tsx, src/route-config.ts, src/stories/RoleMappingForm.stories.tsx
added a filter on the clients to only show the ones that have roles. Used `clientId` instead of `name` to show the clients in the dropdown and added a route so that it will use this screen if you use the "role mapping" in the dialog.
=> Add role mapping into the flow and filter the clients that don't have roles

src/components/keycloak-card/KeycloakCard.tsx, src/components/keycloak-card/keycloak-card.css, src/user-federation/UserFederationSection.tsx, src/user-federation/user-federation.css
Fixes #223 
The user federation card footer was changed to a flex layout so that it would wrap properly
Also, the gallery items were adjusted so that the cards would maintain the same height as each other.
Go to a realm that has user federation items, or add them with the old console. 
View the user federation section in Firefox. To reproduce the bug, you must have had the View -> Zoom -> Zoom text only turned on. 
Hit cmd+ to increase text size and see that the wrapping and card size stay in alignment.
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
Before:
After:
=> Fixes wrapping in user federation cards

src/common-messages.json, src/realm-roles/RealmRoleDetails.tsx, src/realm-roles/messages.json
Closes #235 
https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=4966&view=detail&selectedIssue=APPDUX-682
=> adds delete action to realm roles details page

src/groups/GroupsList.tsx
because `canSelectAll` is false there is no need for this check
=> Small refactor

src/KeycloakAdminConsole.tsx, src/PageHeader.tsx, src/clients/ClientsSection.tsx, src/context/whoami/WhoAmI.tsx, src/index.tsx
We could create an electron based keycloak admin client that could be used to administrate multiple keycloak instances
when we use the nodejs "version" of the admin client
When the admin client is in "nodejs mode" keycloak adapator is not set so this change adds checks on that.
=> be able to use admin client in nodejs mode

src/user-federation/LdapSettingsAdvanced.tsx, src/user-federation/LdapSettingsCache.tsx, src/user-federation/LdapSettingsConnection.tsx, src/user-federation/LdapSettingsGeneral.tsx, src/user-federation/LdapSettingsKerberosIntegration.tsx, src/user-federation/LdapSettingsSearching.tsx, src/user-federation/LdapSettingsSynchronization.tsx
Bring user federation LDAP settings to the same state of development as the kerberos settings
Adds controllers for form controls. Changes to use FormAccess. Adds a couple of cache settings fields that weren't in the settings mockup but should be there.
You can see the form in the storybook, but because it's now under FormAccess, all the fields will be disabled
I'll be following this with additional work, but this gets more of the settings forms in place.
=> User fed fix ldap controllers

src/clients/messages.json, src/clients/scopes/AddScopeDialog.tsx, src/clients/scopes/ClientScopeTypes.tsx, src/clients/scopes/ClientScopes.tsx
Added actions to the client scope tab of the client section
You can now change the client scope types of and remove and add them
go to a specific client by clicking on the link in the client list then open the client scope tab
try out adding, deleting and changing the types
=> added actions to client scope mapping screen

src/clients/ClientSettings.tsx, src/components/form-access/FormAccess.tsx, src/realm-roles/RealmRoleForm.tsx
fixes: #230
prevents warning in console
Go to any page that has a TextArea component like the new realm role page or the role detail page
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] axe report has been run and resulting a11y issues have been resolved
=> TextArea is child of controller

src/components/form-access/FormAccess.tsx, src/components/form-access/__tests__/__snapshots__/FormAccess.test.tsx.snap
not all of their props where copied
=> switches don't work in a `FormAccess` form

package.json, src/App.tsx, src/KeycloakAdminConsole.tsx, src/PageNav.tsx, src/client-scopes/ClientScopesSection.tsx, src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap, src/client-scopes/details/MapperList.tsx, src/client-scopes/details/MappingDetails.tsx, src/client-scopes/form/ClientScopeForm.tsx, src/clients/ClientsSection.tsx, src/clients/add/NewClientForm.tsx, src/components/bread-crumb/PageBreadCrumbs.tsx, src/components/bread-crumb/__tests__/PageBreadCrumbs.test.tsx, src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap, src/components/keycloak-card/KeycloakCard.tsx, src/components/realm-selector/RealmSelector.tsx, src/components/realm-selector/__tests__/RealmSelector.test.tsx, src/components/realm-selector/__tests__/__snapshots__/RealmSelector.test.tsx.snap, src/context/realm-context/RealmContext.tsx, src/context/whoami/WhoAmI.tsx, src/groups/GroupsSection.tsx, src/realm-roles/RealmRoleForm.tsx, src/realm-roles/RealmRoleTabs.tsx, src/realm-roles/RealmRolesSection.tsx, src/route-config.ts, yarn.lock
In order to create links that are "bookmarkable" we should add the realm name in the url
Update the code to create urls like: `/realm/section/` so that you could share links
Navigate to any page to see the realm name in the url
- [N] User-visible strings are using the react-i18next framework (useTranslation)
- [N] Help has been implemented
- [N] axe report has been run and resulting a11y issues have been resolved
- [N] Unit tests have been created/updated
=> Use realm name in urls

src/App.tsx, src/client-scopes/add/RoleMappingForm.tsx, src/client-scopes/details/MappingDetails.tsx, src/client-scopes/form/ClientScopeForm.tsx, src/clients/ClientDetails.tsx, src/clients/credentials/Credentials.tsx, src/clients/scopes/ClientScopes.tsx, src/components/data-loader/DataLoader.tsx, src/components/download-dialog/DownloadDialog.tsx, src/components/table-toolbar/KeycloakDataTable.tsx, src/context/auth/AdminClient.tsx, src/realm-roles/RealmRoleForm.tsx, src/realm-roles/RealmRoleTabs.tsx, src/realm-roles/RoleAttributes.tsx, src/stories/MockAdminClient.tsx, src/stories/UserFedKerberosSettings.stories.tsx, src/stories/UserFedLDAPSettingsTab.stories.tsx, src/user-federation/UserFederationSection.tsx, src/user-federation/kerberos/KerberosSettingsCache.tsx, src/user-federation/ldap/LdapSettingsAdvanced.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx, src/user-federation/ldap/LdapSettingsSearching.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx
otherwise React will mistake it for a react hook and will complain.
Seems our webpack build in storybook does some more checks that the snowpack build does not. If a function starts with `use` react will check if it's used as a proper react hook. Our `useFetch` is not a react hook just a helper function, so renamed it to `asyncStateFetch`
Storybook build should work again
=> renamed `useFetch` to `asyncStateFetch`

src/common-messages.json, src/components/scroll-form/ScrollForm.tsx, src/components/wizard-section-header/WizardSectionHeader.tsx, src/components/wizard-section-header/wizard-section-header.css, src/stories/UserFedKerberosWizard.stories.tsx, src/stories/UserFedLdapWizard.stories.tsx, src/stories/UserFedWizard.stories.tsx, src/stories/WizardSectionHeader.stories.tsx, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationKerberosWizard.tsx, src/user-federation/UserFederationLdapWizard.tsx, src/user-federation/help.json, src/user-federation/kerberos/KerberosSettingsCache.tsx, src/user-federation/kerberos/KerberosSettingsRequired.tsx, src/user-federation/ldap/LdapSettingsAdvanced.tsx, src/user-federation/ldap/LdapSettingsCache.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx, src/user-federation/ldap/LdapSettingsSearching.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx, src/user-federation/messages.json
Adds the wizard screens (just in storybook for now) for user federation ldap and kerberos.
LDAP wizard: https://marvelapp.com/prototype/ecjc94b/screen/72071048
Kerberos wizard: https://marvelapp.com/prototype/ecjc94b/screen/72098365
Adds two stories for the LDAP and Kerberos wizards. Also adds a story for a wizard section header component.
The two user federation settings pages also had to be refactored because the wizard has a section description that doesn't show up on the settings pages. So each section was changed to use the new section header and to use a prop on whether to display the title and description.
Note that these wizards are designed as in-page wizards, so the next step will be to embed them into the content area of a "new user federation" page.
In Storybook, check the …
=> User fed wizard

src/PageHeader.tsx, src/PageNav.tsx, src/clients/service-account/ServiceAccount.tsx, src/components/data-loader/DataLoader.tsx, src/components/data-loader/__tests__/DataLoader.test.tsx, src/components/form-access/__tests__/FormAccess.test.tsx, src/components/realm-selector/RealmSelector.tsx, src/context/access/Access.tsx, src/context/server-info/ServerInfoProvider.tsx, src/context/whoami/WhoAmI.tsx, src/realm/add/NewRealmForm.tsx
The `WhoAmI` context contains the `AccessType[]` needed for all pages when we create a new realm this information need to be updated.
Now when we create a new realm we can switch to the newly created realm without a full reload
=> update who am i on realm create as we need the accessTypes

src/App.tsx, src/components/bread-crumb/GroupBreadCrumbs.tsx, src/components/bread-crumb/PageBreadCrumbs.tsx, src/components/bread-crumb/__tests__/GroupBreadCrumbs.test.tsx, src/components/bread-crumb/__tests__/__snapshots__/GroupBreadCrumbs.test.tsx.snap, src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap, src/groups/GroupsSection.tsx, src/route-config.ts
This adds the ability to click on group names to navigate the sub groups
Introduces specialized breadcrumb, because it's basiclly the same page
Go to old admin console and create a group with subgroups then on the groups section click that groups link
=> Sub group navigation in groups section

src/realm-roles/RealmRoleForm.tsx, src/realm-roles/RealmRoleTabs.tsx, src/realm-roles/RoleAttributes.tsx
https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=4966&view=detail&selectedIssue=APPDUX-749
#298
Implements `reload` function in realm roles section.
1. Go to Realm Roles Section. 
2. Click on an existing realm role in the list.
3. Try typing something to updating the description (do not save)
4. Click "reload" and verify the description field has been reset to the default value loaded previously.
5. Now click on the "Attributes" tab.
6. Repeat the same procedure - try adding a new attribute (do not save) and click reload.
7. The fields should refresh to the default values.
=> Realm Roles: Implements Reload Function

src/client-scopes/ClientScopesSection.tsx
the columns on the client scope screen where excedently removed this PR brings them back
=> fixed excedently removed columns

src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationKerberosWizard.tsx, src/user-federation/kerberos/KerberosSettingsCache.tsx, src/user-federation/kerberos/KerberosSettingsRequired.tsx, src/user-federation/messages.json, src/user-federation/user-federation.css
https://issues.redhat.com/browse/APPDUX-721
Adds the ability to save (or cancel) changes made to the User Federation Kerberos settings page.
1. Go to User federation and select a Kerberos card.
2. Change any of the values in the Required Settings or Cache Settings sections.
3. Click Save. You should see a success alert.
4. Verify that the changes have been saved by traversing anywhere else in the UI and then re-clicking the card to make sure the values that were changed are displayed correctly.
Screen cap of successful save:
=> Add Save/Cancel buttons and logic to Kerberos settings

tests/cypress/integration/client_scopes_test.spec.js, tests/cypress/integration/clients_test.spec.js, tests/cypress/integration/masthead_test.spec.js, tests/cypress/integration/realm_roles_test.spec.js, tests/cypress/integration/realm_test.spec.js, tests/cypress/support/pages/admin_console/ListingPage.js
This PR modify the CRUD tests to join them and it adds a line to clear cookies before log in, it seems like after a retry Cypress doesn't clear cookies and when it launches the test the user is already logged in, causing an error when it waits for the login page. This should stabilize the test failures on retries.
=> Modify CRUD tests

src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/UserFederationLdapWizard.tsx, src/user-federation/help.json, src/user-federation/ldap/LdapSettingsAdvanced.tsx, src/user-federation/ldap/LdapSettingsCache.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx, src/user-federation/ldap/LdapSettingsSearching.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx, src/user-federation/messages.json
https://issues.redhat.com/browse/APPDUX-720
Adds the ability to save (or cancel) changes made to the User Federation Kerberos settings page.
1. Go to User federation and select an LDAP card.
2. Change any of the values in any of the subsections.
3. Click Save. You should see a success alert.
4. Verify that the changes have been saved by traversing anywhere else in the UI and then re-clicking the card to make sure the values that were changed are displayed correctly.
=> Add Save/Cancel buttons and logic to LDAP settings

tests/cypress.json, tests/cypress/integration/00_set_new_admin_console.spec.js, tests/cypress/integration/client_scopes_test.spec.js, tests/cypress/integration/clients_test.spec.js, tests/cypress/integration/login_test.spec.js, tests/cypress/integration/masthead_test.spec.js, tests/cypress/integration/realm_roles_test.spec.js, tests/cypress/integration/realm_test.spec.js, tests/cypress/support/pages/LoginPage.js, tests/package.json
Due to the random Cypress load failures and a bug which doesn't clear cookies, when Cypress retries a test sometimes the user is already logged in, so it fails when expecting the login page.
This PR adds a code on the log in to only do the login when there is a login page.
=> Ignore login when user is already logged

src/components/bread-crumb/__tests__/__snapshots__/PageBreadCrumbs.test.tsx.snap, src/route-config.ts, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/messages.json
https://issues.redhat.com/browse/APPDUX-722
Adds an Enable switch and Actions menu to the Kerberos settings page.
Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72098368
1. Go to User federation and select a Kerberos card.
2. Enable (if disabled) or disable (if enabled) the switch and click Save.
3. Verify that the Kerberos card you enabled/disabled now appears on the User Fed card view with the correct tag of enabled or disabled.
4. Click the card and verify that the Enabled/Disabled switch is correct.
5. Select Action > Delete provider to delete the user fed provider. 
6. Go back to the User federation card view and verify that the card is now gone and the provider has been deleted.
Screen caps:
=> Add enable switch and action menu to kerberos settings

src/components/table-toolbar/KeycloakDataTable.tsx
On client scopes after searching and then deleting the refresh doesn't work this fixes that
Reset the filtered data in the load
go to client scopes create a new scope search this new scope then delete it. afterwards it should no longer be in the list
=> fixes refresh issue

src/clients/ClientDetails.tsx, src/clients/messages.json, src/realm-roles/RealmRoleTabs.tsx, src/realm-roles/RealmRolesList.tsx, src/realm-roles/RealmRolesSection.tsx, src/realm-roles/RolesList.tsx, src/route-config.ts, src/user/SearchUser.tsx
Roles tab under clients is the same as the roles section this PR add it see [marvel](https://marvelapp.com/prototype/bi16ff1/screen/75842763)
See that there is a new tab under client details named roles that has the same functionality as the roles section
=> added roles tab to clients

src/user-federation/ldap/LdapSettingsConnection.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/327
Added ability to show/hide newly-typed passwords in LDAP settings bind credentials field so it works as it did in the old admin UI.
1. Go to the User federation card view and click an LDAP card.
2. In the Connection and authentication settings section, enter a new password in the Bind credentials field.
3. Click the eye button on the field. The password should display in plain text. 
4. Edit the password, and click the eye button again to continue to toggle off/on the text visibility of the password.
Screen cap before button click:
Screen cap after button click:
=> Issue 327: Fix for showing/hiding password text in Bind credentials field

src/clients/ClientDetails.tsx, src/realm-settings/RealmSettingsSection.tsx, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/messages.json
https://issues.redhat.com/browse/APPDUX-719
Adds layout for Enable toggle switch, Action menu and commands, and Remove imported modal. Adds business logic for the Enable switch and the Delete provider menu command. 
Note that the logic for the 4 user-related menu commands is tracked in a different JIRA (https://issues.redhat.com/browse/APPDUX-724) and will be handled in a separate PR as they will probably require backend work.
1. Go to User federation and select an LDAP card.
2. Enable (if disabled) or disable (if enabled) the switch and click **Save**.
3. Verify that the LDAP card you enabled/disabled now appears on the User Fed card view with the correct tag of enabled or disabled.
4. Click the card and verify that the Enabled/Disabled switch is correct.
5. Select **Action > Delete …
=> Add enable switch and action menu to LDAP settings

src/client-scopes/add/__tests__/__snapshots__/MapperDialog.test.tsx.snap, src/components/keycloak-card/KeycloakCard.tsx, src/components/view-header/ViewHeader.tsx, src/route-config.ts, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationSection.tsx, src/user-federation/kerberos/KerberosSettingsRequired.tsx, src/user-federation/messages.json, src/user-federation/shared/SettingsCache.tsx, tests/cypress/integration/user_fed_kerberos_test.spec.ts, tests/cypress/support/pages/admin_console/manage/providers/CreateKerberosProviderPage.ts, tests/cypress/tsconfig.json
https://issues.redhat.com/browse/APPDUX-807
Decision in the 2/2/21 keycloak status meeting was to move forward with functionality to add new providers directly using the 'Add new provider' dropdown in the User Federation settings view similar to the way it was done in the old admin console UI, instead of via the wizards, at least for now. 
Note that this PR also covers creating a new kerberos provider via the user fed empty state page as well, by clicking the 'Add Kerberos providers' card.
Also included in this PR is a suite of cypress tests for the kerberos user federation as a whole, which includes tests for:
- Creating kerberos provider from empty state
- Creating kerberos provider from the card view
- Changing an existing kerberos provider and saving (update)
- Changing an existing …
=> User fed: Add Kerberos provider and tests

src/realm-roles/RealmRolesSection.tsx, src/realm-roles/RolesList.tsx
#365 : Upon reviewing/testing Erik's PR I noticed a bug in the realm roles section when paginating by 10 items per page. This PR addresses and fixes the bug described below.
When a user would select 10 items per page, it was possible to infinitely paginate with the same data showing on every page.
=> Realm roles: fix pagination by 10

src/components/download-dialog/DownloadDialog.tsx, src/context/auth/AdminClient.tsx, src/user-federation/UserFederationSection.tsx, src/user/UsersSection.tsx
Change the type of asyncFetch so we can't use it without an errorHandler
=> now it can't be called without  an error handler

cypress/integration/clients_test.spec.ts, src/clients/ClientsSection.tsx, src/clients/messages.json
Adds missing confirm dialog to clients list
see [marvel](https://marvelapp.com/prototype/f00e9jb/screen/71869615)
Delete a client from the clients list a confirm dialog should be displayed
=> added missing confirm dialog

cypress/integration/user_fed_ldap_test.spec.ts, src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationLdapSettings.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/375
When creating a new user fed provider, navigates to the user fed main page when you click Save. This is how it should've been working from the start, and thus prevents the issue identified in the issue in which multiple providers with the same name could be created unintentionally.
Note that the issue was filed for Kerberos specifically but this fixes the issue for both kerberos and ldap providers.
1. Add a new kerberos user fed provider, by clicking the kerberos card on the empty state page, or by using the Add New Provider button in the card view.
2. Verify that you are navigated to the user fed page upon clicking Save.
3. Repeat steps 1-2 for a new ldap user fed provider.
=> Prevent multiple saves when creating new provider

src/user-federation/UserFederationKerberosSettings.tsx, src/user-federation/UserFederationLdapSettings.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/374
The save button for the User Fed Kerberos and LDAP provider settings was always active. This fix will disable the save button unless the form has changed fields. 
1. Go to User Federation and select an existing Kerberos provider.
2. Verify that the Save button is disabled by default.
3. Change any of the fields in the form.
4. Verify that the Save button is now enabled.
5. Click Save.
6. Verify that the Save button is now disabled again.
7. Repeat steps 1-6 for an LDAP provider.
Note that the original issue that was filed was related to Kerberos specifically, but this change fixes both the Kerberos and LDAP forms.
=> Prevent LDAP and Kerberos settings saves unless dirty

cypress/integration/users_test.spec.ts, cypress/support/pages/admin_console/manage/users/CreateUserPage.ts, src/components/list-empty-state/ListEmptyState.tsx, src/components/list-empty-state/_tests_/__snapshots__/ListEmptyState.test.tsx.snap, src/components/view-header/ViewHeader.tsx, src/route-config.ts, src/user/SearchUser.tsx, src/user/UserForm.tsx, src/user/UsersSection.tsx, src/user/UsersTabs.tsx, src/user/messages.json
- https://issues.redhat.com/browse/APPDUX-860
- Towards https://issues.redhat.com/browse/APPDUX-861
This PR adds a "Create User" page to the Users section of Keycloak. 
1. Go to Users section of Keycloak.
2. Click "Add User".
3. Verify the page matches the mock: https://marvelapp.com/prototype/7i7ja65/screen/75693207
4. Toggle help and confirm that the text content matches what is expected.
5. Click "Cancel" and make sure you are navigated back to the initial users page.
6. Click the "Add User" button again and fill in the Username.
7. Go back to the table and verify that the new user is in the table.
=> Users: Adds create user page to users section

src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/messages.json
https://issues.redhat.com/browse/APPDUX-724
Add business logic for the following LDAP settings menu commands that were available in the legacy admin console:
* Sync changed users
* Sync all users
* Unlink users
* Remove imported
1. Go to user federation and select an LDAP provider card (or create a new one if it doesn't exist).
2. In the action menu, select 'Sync changed users'. Verify that you get an alert with the status.
3. Repeat for the 'Sync all users', 'Unlink users' and 'Remove imported' commands.
There are no cypress tests yet, as we discussed, we will need to set up some kind of mock data or equivalent LDAP config to really test this. These commands will eventually need to be revisited.
=> Action menu commands for User Fed LDAP settings

src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/399.
In the new console UI, when you enable the 'Allow Kerberos authentication' switch, four kerberos controls were supposed to appear but were missing from the initial implementation (kerberos realm text field, server principal text field, key tab text field, and debug switch). These have been added so the implementation now matches the old console UI.
1. Go to user fed and click an existing LDAP card, or create a new LDAP provider.
2. Verify that when you switch Allow Kerberos authentication to ON, the Kerberos realm, Server principal, Keytab, and Debug controls appear.
3. Add values to the fields and click Save.
4. Verify that the new values have been saved by navigating away and returning, or going to the old console, etc.
5. …
=> Add missing kerberos-related fields to LDAP settings

cypress/integration/clients_test.spec.ts, cypress/support/pages/admin_console/manage/clients/AdvancedTab.ts, src/clients/advanced/AdvancedSettings.tsx, src/clients/advanced/FineGrainOpenIdConnect.tsx, src/clients/advanced/FineGrainSamlEndpointConfig.tsx, src/clients/advanced/OpenIdConnectCompatibilityModes.tsx, src/clients/advanced/SaveReset.tsx, src/common-messages.json, src/realm-roles/RealmRoleForm.tsx, src/realm-roles/RoleAttributes.tsx, src/realm-settings/RealmSettingsSection.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/397.
Changes all references of 'Reload' (in most cases, the action button) to 'Revert'. This was brought up during the UXD App Services demo and the change was agreed upon during the Keycloak team meeting on 2/23.
"Revert" is more intuitive and conveys the form is being reverted to the existing values from the server.
Verify that Reload buttons are now replaced with Revert buttons throughout the UI.
None
=> Rename Reload buttons to Revert

public/index.css, src/clients/ClientSettings.tsx, src/common-styles.css, src/user-federation/UserFederationLdapSettings.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/398.
On long forms, aka the forms that have jump links, the action buttons (Save, Cancel, Revert, etc) to the bottom of the screen should be fixed so you don't need to scroll long forms to click them.
1. Go to user fed and select an LDAP provider, or create one if it doesn't already exist.
2. Verify that the Save and Cancel buttons are available at the bottom of the screen without scrolling.
3. Verify that you can navigate the long form by scrolling or using the jump links, and the action buttons still remain available at the bottom of the screen.
4. Repeat steps 1-3 for the client details long form.
=> Nonscrolling action buttons for long forms

public/index.css
=> fix help icon alignment

.github/workflows/cypress.yml, cypress/integration/client_scopes_test.spec.ts, cypress/integration/clients_test.spec.ts, cypress/integration/group_test.spec.ts, cypress/integration/login_test.spec.ts, cypress/integration/masthead_test.spec.ts, cypress/integration/realm_roles_test.spec.ts, cypress/integration/realm_test.spec.ts, cypress/integration/user_fed_kerberos_test.spec.ts, cypress/integration/user_fed_ldap_test.spec.ts, cypress/integration/users_test.spec.ts, cypress/support/pages/admin_console/ListingPage.ts, cypress/support/util/keycloak_before.ts, public/index.html, security-admin-console-v2-combined.json, snowpack.config.js, src/App.tsx, src/PageHeader.tsx, src/context/auth/keycloak.ts, src/dashboard/Dashboard.tsx
Allow New Admin Console to run as a WAR on Keycloak server.
Most of this PR is to align the code so that it works both in dev mode as usual and also as a WAR named "adminv2.war".  We will possibly get rid of the hard-coded WAR name later.
The biggest change is to switch to using the HashRouter.  While this results in uglier URLs, it makes it much easier to have code that runs in both dev and prod modes.
First verification step is to just run in development mode as usual and make sure everything still works.
To get this to run as a WAR on the Keycloak server:
1. `yarn build`
2. Copy contents of `/build` directory to `<keycloak install>/standalone/deployments/adminv2.war/` on the Keycloak server.
3. Add an empty marker file `<keycloak install>/standalone/deployments/adminv2.war.dodeploy`
4. …
=> Allow New Admin Console to run as a WAR on Keycloak server.

src/realm-roles/RealmRolesSection.tsx
I don't know why this was added, it might break something somewhere else, but for me realm roles list was empty every time.
Also it was fetching the list twice.
Realm roles was always empty
Go to realm roles and see realm roles
=> removed double query for realm roles

src/user/UserGroups.tsx
Towards #496 
Set "Leave" button only on "direct membership" groups
=> Users(groups): set leave buttons  only on groups with direct membership

src/context/auth/keycloak.ts
Need to be able to run new admin console from keycloak.org.
Four ways to set location of Keycloak server:
1. http://anydomain/anycontext/?keyclaok-server=http://my-keycloak-server.com
2. Usual dev mode, which defaults server to http://localhost:8180
3. Demo mode, http://anydomain/adminv2/?demo=true, which defaults server to http://localhost:8080
4. Integrated into keycloak server, http://keycloak-server-domain/adminv2
Try out any or all of the modes above.
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] axe report has been run and resulting a11y issues have been resolved
=> Allow four ways to set location of keycloak server.

public/index.css
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/527.
When we upgraded Patternfly two releases ago, borders were no longer appearing around Select components. After some due diligence, turns out that PF is using valid CSS but one of our dependencies (postCSS) is not interpreting it correctly. See the issue above for a full explanation and a screen cap of the issue.
Best solution in this case, and recommended by PF team, is to just override the border style to get the borders back.
Open any place in the new admin UI and verify that borders now appear around the Select components.
**Before:**
**After:**
=> Fix missing borders around Select components

cypress/integration/partial_import_test.spec.ts, cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts, cypress/support/pages/admin_console/configure/realm_settings/RealmSettings.ts, src/components/json-file-upload/JsonFileUpload.tsx, src/realm-settings/PartialImport.tsx, src/realm-settings/RealmSettingsSection.tsx, src/realm-settings/messages.json
Start to implement Partial Import: [Marvel](https://marvelapp.com/prototype/fg26f9b/screen/75624791)
This just handles:
- Open/Close Partial import dialog
- Enable/Disable import button when json added or cleared
- Show/Hide (unfinished) [section for "choose resources" and "if resource exists"](https://marvelapp.com/prototype/fg26f9b/screen/75624792)
- Implement Cancel
Go to Realm Settings -> Actions menu -> Partial Import
Verify above works as expected.
=> Begin implementation of Partial Import modal.

cypress/integration/users_test.spec.ts, src/client-scopes/messages.json, src/clients/ClientsSection.tsx, src/clients/messages.json, src/components/list-empty-state/ListEmptyState.tsx, src/components/table-toolbar/KeycloakDataTable.tsx, src/user/UserConsents.tsx, src/user/UsersTabs.tsx, src/user/messages.json, src/user/user-section.css
JIRA: closes https://issues.redhat.com/browse/APPDUX-919
Github: Closes #517 + #526 
1. Go to Users section
2. Create a new user
3. Click on "Consents" tab
4. Verify empty state matches the mock at https://marvelapp.com/prototype/f734jga/screen/73531547
=> Users(Consents): add empty state and list consents

src/user/UserGroups.tsx, src/user/messages.json
Closes #458 
Adds popover with help text as agreed upon in Keycloak UI meeting.
1. Go to Users -> Groups tab
2. Make sure help mode is enabled.
3. Click "Who will appear in this groups list" button.
=> Users(groups): Adds help text for direct membership

src/clients/AdvancedTab.tsx, src/components/scroll-form/ScrollForm.tsx, src/components/scroll-form/ScrollPanel.tsx, src/components/scroll-form/form-panel.css
Removes the borders from the client detail page scroll form and only adds them on the advanced tab.
=> add option to add borders on scroll panel

cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/ldap/mappers/LdapMapperDetails.tsx, src/user-federation/ldap/mappers/LdapMapperFullNameAttribute.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedAttribute.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapAttribute.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapGroup.tsx, src/user-federation/ldap/mappers/LdapMapperList.tsx, src/user-federation/ldap/mappers/LdapMapperUserAttribute.tsx
https://issues.redhat.com/browse/APPDUX-867
Adds cypress CRUD tests for the existing 8 implemented LDAP mapper types:
- msad-user-account-control-mapper
- msad-lds-user-account-control-mapper
- user-attribute-ldap-mapper
- hardcoded-attribute-mapper
- certificate-ldap-mapper
- full-name-ldap-mapper
- hardcoded-ldap-group-mapper
- hardcoded-ldap-attribute-mapper
Run the new user_fed_ldap_mapper_test cypress test and verify that all tests complete without failing.
=> Cypress tests for initial 8 LDAP mappers

public/index.css, src/identity-providers/IdentityProvidersSection.tsx, src/user-federation/UserFederationSection.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/user-federation.css
Partially fixes https://github.com/keycloak/keycloak-admin-ui/issues/436.
Adds a hand cursor icon when hovering over the User federation empty state cards. Also adds a default value of 'ldap' to the console name field when creating a new LDAP provider.
1. Go to User Federation.
2. If there are existing LDAP/Kerberos providers configured, delete them from the card view.
3. Verify that the cursor changes to a hand icon when hovering over either of the cards in empty state view.
4. Click the LDAP card and verify that the default console name is listed as 'ldap'.
None
=> Show hand cursor when hovering over User Fed empty state cards

src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/ldap/LdapSettingsSearching.tsx
Partially fixes https://github.com/keycloak/keycloak-admin-ui/issues/436.
When creating an LDAP user federation provider, if you change the Vendor type, the Username LDAP attribute, RDN LDAP attribute, UUID LDAP attribute, and User Object Classes fields should be populated with values specific to the 5 vendor types.
1. Go to User Fed and click the LDAP card to create a new LDAP user fed provider.
2. Verify that choosing the 5 vendor types will change the values of the above mentioned fields.
This issue is flagged as high priority for the user testing effort.
=> Update LDAP provider default values based on vendor type

cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx, src/user-federation/messages.json
Partially fixes https://github.com/keycloak/keycloak-admin-ui/issues/436.
When creating an LDAP provider, in the Connection and authentication settings section, the "Bind DN" and "Bind credentials" fields should only display when 'simple' is selected from the "Bind type" dropdown, and should be hidden when the Bind type is 'none'.
1. Create a User Federation LDAP provider and verify that the two fields above are shown/hidden correctly.
**Update**: Currently having an issue in which the DN and Credentials fields are no longer populating with the correct data when the form is loaded or when simple is chosen.
This should not be pushed until the issue in verification steps is fixed.
=> LDAP Providers - do not show DN and Credentials when bind type is none

src/util.ts
Base url is now invalid because it doesn't have a slash at the end resulting in Urls with `authreamls`
go to the clients section and see that the urls are valid or the realm settings
=> add `/` after baseUrl

src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx
https://github.com/keycloak/keycloak-admin-ui/issues/436
Requests from UX:
- In the "Connection and authentication settings" section, the Test button should always be enabled, and it should not be hidden regardless of bind type.
- In the "Synchronization settings" section, the Import users toggle should default to On. 
Go to User Fed and create a new LDAP provider. Verify that the:
- Import users toggle default to On. 
- Test button can be clicked.
- Test button appears when you select Bind type of none or simple.
All user federation cypress tests passed.
=> UX review: Fixes for test button and import users

Gruntfile.js
location of fonts is now different because of new postcss plugin
https://github.com/keycloak/keycloak-admin-ui/pull/627
=> changed location due to new snowpack postcss plugin

package.json, yarn.lock
Update Patternfly to the latest releases so we stay current with the latest changes.
As part of the Patternfly release process, I perform sanity tests of the new proposed versions on the keycloak admin UI and file issues as needed. This occurs about every 3 weeks. As part of that process, we should update keycloak to the latest versions on a regular cadence.
Note that this PR also reverts snowpack/plugin-postcss from 1.4.0 to 1.0.4 in order to fix font issues introduced with the dependabot PR.
Use the keycloak admin UI and verify that no visual or behavioral issues have been introduced, and that there are no new console warnings/errors. Also, rebuild node_modules and verify that the font 404 issues are now fixed.
=> Update to Patternfly 4.108.2 (latest release)

cypress.json
Increases the cypress default command timeout from 4 secs to 10 secs.
Simple cypress configuration change. Should help automatically eliminate cases in which slow load times are interfering with test step completion.
Run the tests locally and verify that wait times for any commands getting errors are now waiting 10000ms instead of 4000ms.
When I ran the tests locally, there were two errors and on each of those errors the default wait was 10000ms. 
I watched the tests execute in real-time and during both of those timeouts, the errors were not due to page loads. The pages were loaded and waiting for a command, but certain data-helpids were not found. It seemed both were related to button clicks and could probably be fixed by forcing the clicks of those buttons, but that is tangential to …
=> Increase cypress default command timeout to 10 seconds

src/route-config.ts, src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/messages.json
Additional items recently added to the User Fed UX review:
https://github.com/keycloak/keycloak-admin-ui/issues/436 (see bottom)
Fixes 3 UX issues:
- Should not be a tab bar and tabs on the LDAP provider creation page, just when editing an existing LDAP provider.
- When creating an LDAP provider, the breadcrumb should be **User federation > Add LDAP provider** instead of **User Federation > Settings**.
- When creating an LDAP provider, the page title should be **Add LDAP provider** instead of **LDAP**.
1. Create a new LDAP provider and verify that the same configuration and scroll appear without tabs.
2. Verify that the breadcrumb and title on the create LDAP provider page are correct as noted above.
3. Edit an existing LDAP provider and verify that the Settings and Mapper configurations …
=> Fix additional UX issues with User Federation

cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/components/role-mapping/AddRoleMappingModal.tsx, src/components/role-mapping/RoleMapping.tsx, src/components/table-toolbar/KeycloakDataTable.tsx, src/user-federation/ldap/mappers/LdapMapperDetails.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapGroup.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapRole.tsx, src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx, src/user-federation/user-federation.css
https://issues.redhat.com/browse/APPDUX-929 and https://issues.redhat.com/browse/APPDUX-940
Adds the 3 remaining mapper types to user federation ldap providers (group-ldap-mapper, role-ldap-mapper, and hardcoded-ldap-role-mapper). These required extra functionality than the others e.g. a modal to select from existing roles/clients. Also includes cypress tests for all 3 of the new mappers.
1. Go to User Fed and create a new LDAP provider if one doesn't already exist.
2. Go to the LDAP provider settings and click the Mappers tab.
3. Click Add mapper and choose group-ldap-mapper and verify that you can create a new one successfully.
4. Repeat for role-ldap-mapper and hardcoded-ldap-role-mapper. 
5. When configuring the role mappers, verify that you can select a role via the "Select role" …
=> Adds User Fed Group and Role mappers

src/user/UserConsents.tsx, src/user/UsersTabs.tsx, src/user/messages.json, src/user/user-section.css
Closes #668 
1. Go to client scopes -> create a new client scope.
2. Set the “Type” to “default” and make sure “Display on consent screen” is enabled.
3. Repeat for however many client scopes you want to create/grant.
4. Go to Clients and make sure both security-admin-console and security-admin-console-v2 have “Consent required” set to “on” under Login Settings
5. Go to Clients -> Client Scopes and then add the new client scopes as “Default”
6. Log out of both the new admin console and the old one
7. Log back into both
8. It should ask you to verify the new consents -> click accept/yes
9. Go to Users -> admin -> consents and you should see them listed there
=> Consents UI fixes

cypress/integration/partial-import-test-data/client-only.json, cypress/integration/partial-import-test-data/kcexport.json, cypress/integration/partial-import-test-data/multi-realm.json, cypress/integration/partial_import_test.spec.ts, cypress/support/pages/admin_console/configure/realm_settings/PartialImportModal.ts, src/components/json-file-upload/JsonFileUpload.tsx, src/realm-settings/PartialImport.tsx, src/realm-settings/messages.json
This is phase 2 of the Partial import implementation.  Phase 3 will be the final phase where the imported data is sent to the Keycloak server.
Partial import modal now handles the imported JSON and presents the user with import options as per [Marvel](https://marvelapp.com/prototype/fg26f9b/screen/75624791).  
Note: The design did not include functionality for handling JSON files with multiple realms.
1. Go to `Realm settings`.
2. Select Partial import form the Action dropdown.
3. Import a previously exported Keycloak json. (Samples included in test data for this PR. `kcexport.json` is a good one to look at)
4. Verify that modal presents the user with options as shown in the design, plus multi-realm functionality.
=> Partial import phase 2

public/index.css, src/realm-settings/KeysProvidersTab.tsx, src/realm-settings/LocalizationTab.tsx, src/realm-settings/RSAGeneratedModal.tsx, src/realm-settings/RealmSettingsSection.css, src/realm-settings/RealmSettingsSection.tsx, src/realm-settings/ThemesTab.tsx, src/realm-settings/messages.json
Closes #682 
Towards https://issues.redhat.com/browse/APPDUX-937
1. Go to the old admin console.
2. Navigate to Realm settings -> Localization 
3. Create a locale: you must name it any of the following: ca, cs, da, de, en, es, fr, hu, it, ja, lt, nl, no, pl, pt-BR, ru, sk, sv, tr, zh-CN
4. Add at least one key, value pair and click save.
5. Go to the new console. 
6. Navigate to Realm settings -> localization 
7. Comment out https://github.com/keycloak/keycloak-admin-ui/compare/master...jenny-s51:localizationTab?expand=1#diff-6a013ef3899e308f424b7fd2f79cee59df8f9f2989832ece8ccf14d4081aa2abR207
7. Enable Internationalization and select your new locale as the "default locale". 
8. Verify that the key-value mappings are listed in the table below.
=> Localization tab

cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/mappers/LdapMapperDetails.tsx
Adds a typeahead to the LDAP mapper select list, as requested in UXD demo and referenced in https://github.com/keycloak/keycloak-admin-ui/issues/705.
LDAP mapper select list consists of 11 items, which qualifies for the PF guideline that each list with > 10 items should use the typeahead variant. Simple change to add the variant.
1. Go to User Fed and create an LDAP provider if one doesn't already exist.
2. In the LDAP provider details, go to the **Mappers** tab and click **Add mapper**.
3. In the **Mapper type** dropdown, verify that you can narrow the list of mapper types by typing the first few chars of one or more mapper types.
none
=> Use typeahead for mapper list

cypress/integration/masthead_test.spec.ts, cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts, src/client-scopes/details/ScopeForm.tsx, src/components/help-enabler/HelpItem.tsx, src/components/help-enabler/__tests__/__snapshots__/HelpItem.test.tsx.snap, src/realm-roles/RealmRoleForm.tsx, src/realm-roles/RealmRoleTabs.tsx, src/realm-roles/RealmRolesSection.css, src/realm-roles/RolesList.tsx, src/realm-roles/messages.json
Closes #687 
Verify that the following have been addressed:
> Based on meeting with Vlasta, we need the following changes:
> - Recognize default realm role.  Add help text so that user understands it is special.
> - Do not allow default realm role to be deleted.
> - Description for default realm role should be read only.
> - Attributes tab should be hidden
> - Users in Role tab should be hidden
_Originally posted by @ssilvert in https://github.com/keycloak/keycloak-admin-ui/issues/687#issuecomment-857652466_
=> Default roles: UI Changes from KEYCLOAK-14846

src/realm-settings/LocalizationTab.tsx, src/realm-settings/ThemesTab.tsx
This PR fixes the default value warnings that coccured in the console on the realm settings
=> fixed default value warning

.github/workflows/cypress.yml, snowpack.config.js
Disable the WebPack plugin for production to allow more tests to pass in the CI.
=> Disable WebPack production build to pass tests

.github/pull_request_template.md, .github/workflows/node.js.yml, README.md, package-lock.json, package.json, snowpack.config.js
This allows types to be checked during development without running `npm run check-types` separately and reduces the need to run this task on the CI.
=> Use a Snowpack plugin to check TypeScript types

package-lock.json, package.json, snowpack.config.js, src/index.tsx, tsconfig.json
This enables Hot Module Reloading and React Fast Refresh, for more information see the [Snowpack documentation](https://www.snowpack.dev/concepts/hot-module-replacement). TLDR; this change allows us to update styling and React components during development without reloading the page and preserving state, which increases development speed.
=> Use a Snowpack plugin to enable React Fast Refresh

package-lock.json, package.json, src/user/user-section.css
There are some fixes in PatternFly that are needed for the the Snowpack 3 (https://github.com/keycloak/keycloak-admin-ui/pull/839) upgrade that are only available in a prerelease version.
=> Upgrade PatternFly to a prerelease version

snowpack.config.js
Remove the snowpack error overlay since it obscures the UI and is redundant with the information that is available in the console.
Simple snowpack config file change that sets the error overlay to false.
Generate an error by modifying the code and verify that the error overlay no longer appears in the browser window, but the error still appears in the console window.
none
=> Remove snowpack error overlay

start.js
@ssilvert's work on the theme integration requires a newer version of Keycloak. This change updates the Keycloak version to 14 and enables the feature flag to enable the new admin console.
=> Update development Keycloak server to version 14

cypress/integration/realm_settings_test.spec.ts, src/realm-settings/RealmSettingsSection.tsx
Tests for https://github.com/keycloak/keycloak-admin-ui/pull/856 are failing because you can't go to the Realm Settings for any realm except master.  The reason is that we are getting a NPE on WildFly 14+.  I believe that there is a bug in WildFly.  It is probably not initializing the localization when you create a new realm.
However, I see some possible issues with the implementation on our side as well.  Our localization tab assumes that you should always be able to create bundle keys and values for English.  I believe this should not be the case.
The error is actually caused when you try to make the REST call to admin/realms/mynewrealm/localization/en.  But the old console does not make this call until you explicitly create the locale for en.  So you don't see the error in the old …
=> Comment out localization tab.

keycloak-theme/.gitignore, keycloak-theme/README.md, keycloak-theme/pom.xml
This will allow Java devs to build the frontend through Maven, so they do not have to deal with JavaScript tooling. Also an enabler to build the JAR on our CI so folks can try out builds on `master`.
Depends on: https://github.com/keycloak/keycloak-admin-ui/pull/854, please merge that one first.
=> Allow Maven to build the frontend

cypress/integration/realm_settings_test.spec.ts, package-lock.json, src/realm-settings/key-providers/rsa/RSAForm.tsx, src/realm-settings/key-providers/rsa/RSAModal.tsx, src/route-config.ts
Closes #869 ; Towards #639
Also https://issues.redhat.com/browse/APPDUX-1022
Adds details/edit functionality for rsa providers in keys tab of realm settings.
1. Go to Realm settings -> Keys -> Providers
2. Select "rsa", populate fields in modal, and save
3. Find the new provider you just created in the list and click on it.
4. See the new "rsa" details page. 
5. Edit some fields, save, and navigate elsewhere in the app.
6. Navigate back to your updated rsa provider and verify that the data is saved correctly.
=> Realm settings(keys): add rsa provider details

src/realm-settings/KeysProvidersTab.tsx, src/realm-settings/key-providers/java-keystore/JavaKeystoreForm.tsx, src/realm-settings/key-providers/java-keystore/JavaKeystoreModal.tsx, src/route-config.ts
Closes #875  ; Towards #639
Also https://issues.redhat.com/browse/APPDUX-1022
Adds details/edit functionality for java-keystore providers in keys tab of realm settings.
1. Go to Realm settings -> Keys -> Providers
2. Select "java-keystore", populate fields in modal, and save
3. Find the new provider you just created in the list and click on it.
4. See the new "java-keystore" details page. 
5. Edit some fields, save, and navigate elsewhere in the app.
6. Navigate back to your updated java-keystore provider and verify that the data is saved correctly.
=> Realm settings(keys): add java-keystore details/modal

src/realm-settings/RealmSettingsSection.tsx, src/route-config.ts
#832 
1. Go to realm settings -> keys -> providers
2. Click on a provider or create a new one and then go to the provider details. 
3. Verify the breadcrumb now contains Realm settings > Keys > Providers > Edit provider
=> Realm settings(keys): add updated breadcrumb for key providers

src/App.tsx, src/PageNav.tsx, src/components/bread-crumb/PageBreadCrumbs.tsx, src/route-config.ts
Allows us to access the route definitions without first having to call a function to pass the translations.
=> Defer breadcrumbs translations on route definitions

package-lock.json, package.json, src/PageHeader.tsx, src/client-scopes/add/RoleMappingForm.tsx, src/clients/scopes/EvaluateScopes.tsx, src/components/alert/Alerts.tsx, src/components/download-dialog/DownloadDialog.tsx, src/components/help-enabler/HelpHeader.tsx, src/components/help-enabler/HelpItem.tsx, src/components/realm-selector/RealmSelector.tsx, src/components/view-header/ViewHeader.tsx, src/context/access/Access.tsx, src/context/auth/AdminClient.tsx, src/context/realm-context/RealmContext.tsx, src/context/server-info/ServerInfoProvider.tsx, src/context/whoami/WhoAmI.tsx, src/events/AdminEvents.tsx, src/events/EventsSection.tsx, src/groups/SubGroupsContext.tsx, src/realm-roles/UsersInRoleTab.tsx, src/realm-settings/EmailTab.tsx, src/realm-settings/RealmSettingsSection.tsx, src/realm/add/NewRealmForm.tsx, src/user-federation/UserFederationSection.tsx, src/user/UserGroups.tsx, src/user/UsersSection.tsx, src/utils/useRequiredContext.test.ts, src/utils/useRequiredContext.ts
Introduce a `useRequiredContext` function to assert the value from `useContext` is non-nullable, and throw an exception if it is not.
Other notable changes:
- All contexts now have a default value of `undefined`.
- Use dedicated hooks to retrieve values of contexts instead of direct access through `useContext` calls.
- All hooks calls proxy through `useRequiredContext` to ensure the context is always present.
=> Introduce 'useRequiredContext' utility function

src/components/bread-crumb/PageBreadCrumbs.tsx, src/route-config.ts
If `undefined` is passed into a route definition on the `breadcrumb` property a best effort attempt will be made to provide breadcrumbs from route parameters. This is however not the behavior we want, so we will have to set `disableDefaults` to `true` in order to prevent breadcrumbs from being added implicitly.
For example, without this change the breadcrumbs for a subgroup will look like this:
And with this change, we get the expected behavior:
=> Disable automatically generated breadcrumbs

src/route-config.ts, src/sessions/routes.ts, src/sessions/routes/Sessions.ts
Aligns the routing for session routes with the conventions as discussed in the team meetingoutput.
=> Use new routing conventions for session routes

get-version.sh, release.sh, set-version.sh
This PR contains our "Keycloak standard" scripts needed to do a release.  They are based on the scripts used in other Keycloak projects.
I was only able to verify that `get-version.sh` and `set-version.sh` are working properly.  `release.sh` requires our org.keycloak credentials to the maven central repo, so I think only Stian can run it.
As a Windows user, I don't write a lot of shell scripts.  So please review and let me know if you see anything obviously wrong, especially with `release.sh`.
=> Add scripts needed for release.

.eslintrc.js, src/App.tsx, src/components/alert/Alerts.tsx, src/components/data-loader/DataLoader.test.tsx, src/components/form-access/FormAccess.tsx, src/components/help-enabler/HelpHeader.tsx, src/components/scroll-form/FormPanel.tsx, src/components/scroll-form/ScrollForm.tsx, src/components/scroll-form/ScrollPanel.tsx, src/components/table-toolbar/PaginatingTableToolbar.tsx, src/components/table-toolbar/TableToolbar.tsx, src/context/access/Access.tsx, src/context/realm-context/RealmContext.tsx, src/context/server-info/ServerInfoProvider.tsx, src/context/whoami/WhoAmI.tsx, src/events/AdminEvents.tsx, src/groups/SubGroupsContext.tsx, src/identity-providers/component/FormGroupField.tsx
The `FunctionComponent` type contains the correct types for the `children` prop and enforces a correct return type.
=> Use FunctionComponent type for components needing 'children' prop

keycloak-theme/pom.xml
`loginRealm` in `index.ftl` is currently hard-coded to "master".
Change so that new Keycloak server code that passes the value for `loginRealm` can provide that value.  For older Keycloak servers, it will continue to default to "master"
CI can verify if this is working in the default case.  You won't be able to test passing the `loginRealm` to the Freemarker template until my PR is integrated into Keycloak server.
=> Fix loginRealm to work on old and new Keycloak

.eslintrc.js, src/clients/ClientSettings.tsx, src/clients/credentials/X509.tsx, src/components/attribute-form/AttributeForm.tsx, src/components/multi-line-input/MultiLineInput.tsx, src/components/table-toolbar/KeycloakDataTable.tsx, src/components/table-toolbar/TableToolbar.tsx, src/context/whoami/WhoAmI.tsx, src/identity-providers/add/AdvancedSettings.tsx, src/identity-providers/add/DiscoverySettings.tsx, src/identity-providers/add/OpenIdConnectSettings.tsx, src/identity-providers/component/ClientIdSecret.tsx, src/realm-roles/RoleAttributes.tsx, src/user-federation/kerberos/KerberosSettingsRequired.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx, src/user-federation/ldap/LdapSettingsSearching.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapGroup.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapRole.tsx, src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx, src/user/UserGroups.tsx
Use optional chaining in all places over validating references. Introduce an ESLint rule to enforce this.
A common review comment is to use optional chaining over traditional reference validation (e.g. `foo && foo.bar`). To save time on these trivial review comments it's easier to enforce this as an ESLint rule so it can be caught early in development.
=> Prefer optional chaining over validating references

cypress/integration/sessions_test.spec.ts, cypress/support/pages/admin_console/manage/sessions/SessionsPage.ts, src/components/view-header/ViewHeader.tsx, src/context/whoami/WhoAmI.tsx, src/sessions/LogoutAllSessionsModal.tsx, src/sessions/RevocationModal.tsx, src/sessions/SessionsSection.css, src/sessions/SessionsSection.tsx, src/sessions/messages.ts
Towards https://issues.redhat.com/browse/APPDUX-1067
Adds "revocation" functionality to Actions dropdown of sessions page
1. Go to Sessions
2. Click on "Actions" menu in the top right and select "Revocation"
3. Click "Set to now".
4. Sign back in
5. Repeat steps 1-2
6. Verify that "Not before" value is correct
7. Click "Clear"
8. Click on "Actions" menu in the top right and select "Revocation"
9. Verify that "Not before" value is set to none.
* Push functionality will be confirmed by @ssilvert per Zulip thread
=> Sessions(actions dropdown): Adds actions dropdown - "revocation" and "log out all sessions"

.github/dependabot.yml
Prevents Dependabot from creating PRs that try to update major versions of dependencies that are known to cause issues.
=> Disable major updates of broken dependencies

src/PageNav.tsx, src/components/table-toolbar/KeycloakDataTable.tsx, src/realm-settings/LocalizationTab.tsx, src/realm-settings/RealmSettingsSection.tsx
https://issues.redhat.com/browse/APPDUX-1066
Adds locale filter to message bundle table as shown in https://marvelapp.com/prototype/56d9606/screen/76458142
1. Go to `RealmSettings.tsx` and uncomment the Localization tab.
2. Go to Realm Settings -> Localization.
3. As per the design, the locale filter in the table should be disabled until the form above is modified and saved.
4. Save the form and verify that the new locale select filter works as expected.
=> Realm settings(localization): add locale dropdown to table

src/components/password-input/PasswordInput.tsx, src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx
Because keycloak doesn't store the password as clear text and returns the password as '***' it doesn't make sense to reveal the text
fixes: #971
=> change to TextInput when editing 

.eslintrc.js, src/clients/ClientsSection.tsx, src/components/bread-crumb/GroupBreadCrumbs.tsx, src/components/keycloak-tabs/KeycloakTabs.tsx, src/identity-providers/add/DetailSettings.tsx, src/user-federation/ldap/mappers/LdapMapperList.tsx
Change code to prefer using `includes()` over `indexOf() === -1` to check if items exist in an array. Also adds an ESLint rule to enforce this.
This comes up as a review comment every once and a while, enforcing it as a rule will prevent some trivial review comments.
=> Prefer Array#includes() over Array#indexOf()

src/context/whoami/WhoAmI.tsx, src/i18n.ts, src/realm-settings/LocalizationTab.tsx
Adds a constant for the default locale for this application. Also adds a `getLocale()` method to `WhoAmI` to get the locale preferred by the user.
Having a single constant for the default locale will make it easier to refactor the application. This is also required for a later PR that will take advantage of the `getLocale()` method for `WhoAmI`.
=> Add a constant for the default locale

src/authentication/FlowDetails.tsx, src/authentication/components/ExecutionConfigModal.tsx, src/authentication/components/FlowHeader.tsx, src/authentication/components/FlowRow.tsx, src/authentication/help.ts, src/authentication/messages.ts
still needs to render different controls based on the types
Go to authentication section click on one of the flows some executions can have settings indicated by a cog wheel on the right side
clicking it will open a modal dialog to add the settings or clear / update existing onces.
TODO is rendering different inputs based on the type of the field
The fields are dynamic based off a backend call
=> Initial version of config settings for executions

src/user/UserIdPModal.tsx, src/user/UserIdentityProviderLinks.tsx, src/user/UsersTabs.tsx, src/user/help.ts, src/user/messages.ts, src/user/user-section.css
https://issues.redhat.com/browse/CLUX-234
1. Go to Identity Providers -> Add provider
2. Add a few different Identity providers
3. Go to Users -> Create a new user
4. Go to the Identity Provider Links tab
5. Click "Link account" for one of the Available Identity Providers
6. Populate the fields in the modal, save, and verify the Linked account shows up in the Linked Identity Providers list
7. Click "Unlink account" for the provider you just linked
8. Save and verify it is no longer visible under "Linked Identity Providers", and it _is_ visible again in Available Identity Providers
=> Users: Add Identity Provider Links tab

.eslintrc.js
Prettier setting to allow Windows users to maintain existing line endings.  Otherwise, prettier complains in VS code.  The line endings are handled by git on commit so that we should never see Windows line endings in our repo.
REVIEWER: Please test to make sure you can still do normal commits with this change.  The commit hook depends on the eslint config, which is what this PR is changing.
=> Don't complain about Windows line endings

src/realm-settings/messages.ts, src/realm-settings/security-defences/BruteForceDetection.tsx
Fix help text for minimum quick login wait.  Before, it was pointing to minimumQuickLoginWaitSeconds, which it was looking for in the wrong bundle.  Now, both help text and label use minimumQuickLoginWait, which exists in both messages.ts and help.ts.
=> Fix help text for minimum quick login wait

src/identity-providers/IdentityProvidersSection.tsx, src/identity-providers/add/AddOpenIdConnect.tsx, src/identity-providers/add/AddSamlConnect.tsx, src/identity-providers/add/DetailSettings.tsx, src/identity-providers/routes/IdentityProviderTab.ts, src/user/UserIdentityProviderLinks.tsx
Allows users to save identity providers as the alias name, as is intended. Also allows you to edit an existing identity provider and save it.
Prior to this PR, you were able to successfully create new OIDC or SAML identity providers but they would be saved with the providerId name (e.g. 'saml' or 'oidc', etc). This fix will save the id provider by the specified alias name. This also adds new routing for and the ability to edit an existing id provider and save results, which wasn't working previously.
1. Go to Identity Providers and add a new SAML provider.
2. Type in a specific alias name instead of the default 'saml'
3. Turn Use entity descriptor to off.
4. Add a Single Sign-On service URL, such as 'https://localhost.8180/auth/realms/sso'.
5. Click Add and verify that it saved correctly, …
=> Adds routing for and fixes add new/save existing identity providers

src/user/UsersSection.tsx, src/user/messages.ts
[marvel](https://marvelapp.com/prototype/7i7ja65/screen/81351820)
ability to unlock all temporary locked users when brute force is enabled for the realm
1. enable brute force defence on the realm
1. fail to login for a user
1. unlock the user by using the unlock all button on the user screen
=> added remove all temporary locks

src/components/time-selector/TimeSelector.tsx
The Time selector was generating duplicate id's when you go to Realm Settings.  
I think it should be OK to let the id be auto-generated if needed.  I don't expect that anything relied on this ID since it was using a timestamp.
=> Time selector was generating duplicate id's

cypress/integration/authentication_test.spec.ts, cypress/support/pages/admin_console/manage/authentication/FlowDetail.ts, package-lock.json, package.json, src/authentication/FlowDetails.tsx, src/authentication/components/EditFlowDropdown.tsx, src/authentication/components/FlowDiagram.tsx, src/authentication/components/FlowRow.tsx, src/authentication/components/modals/AddStepModal.tsx, src/authentication/components/modals/AddSubFlowModal.tsx, src/authentication/messages.ts, src/clients/credentials/Credentials.tsx
This adds the add button on the authetication flows [marvel](https://marvelapp.com/prototype/bh91013/screen/75676609)
Adding an execution or condition works, but subflow only shows a model that doesn't work, as it needs some clarification
on how to do that without type and provider.
1. Go to authentication copy one of the existing flows
1. Then go to the details of that flow
1. Now you'll see a `+` icon on the sub flows
1. use the "Add step" and "Add condition" dropdown items to add excutions to the sub flow
=> Add button on authentication flows

src/components/data-loader/DataLoader.test.tsx, src/components/form-access/FormAccess.test.tsx, src/components/realm-selector/RealmSelector.tsx, src/context/realm-context/RealmContext.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm/add/NewRealmForm.tsx
Closes #1068
1. Create a new realm
2. Go to 'Realm Settings' and delete the newly created realm
3. Use the main navigation to navigate around
The navigation occurs in the 'Master' realm as this is the realm that was redirected to after deleting the newly created realm.
The navigation occurs in the realm that was deleted, causing the app to crash.
=> Keep realm value from RealmContext in sync with the URL

.eslintrc.js
Adds an ESLint rule to warn about unnecessary conditions. A warning was chosen as there is too much code to fix for the error level.
This comes up as a review comment every once and a while, enforcing it as a rule will prevent some trivial review comments.
=> Warn about unnecessary conditions

src/identity-providers/IdentityProvidersSection.tsx, src/identity-providers/add/AddIdentityProvider.tsx, src/identity-providers/add/DetailSettings.tsx, src/identity-providers/messages.ts, src/identity-providers/routes/IdentityProviderTab.ts
https://issues.redhat.com/browse/CLUX-223
Adds data table for mappers of SAML Identity Providers
1. In the old console, go to Identity Providers -> Add Provider -> SAML v2.0
2. Save the new provider and scroll up to the Mappers tab.
3. Click the mappers tab and create a few mappers with different names and mapper types.
4. Now in the new console, go to Identity Providers and click on the SAML provider you created.
5. Click the Mappers tab and verify the data matches the table in the old console
=> Identity Providers(SAML): Adds data table for SAML mappers

.github/workflows/publish.yml, keycloak-theme/pom.xml
This will allow us to automatically publish a snapshot version on every commit on master, which can be used to in the main Keycloak project to include the latest changes from the Admin Console. For more information see @ssilvert's PR https://github.com/keycloak/keycloak/pull/8366
=> Add action to automatically publish snapshots

src/identity-providers/IdentityProvidersSection.tsx, src/identity-providers/add/OIDCGeneralSettings.tsx, src/identity-providers/add/SamlGeneralSettings.tsx
Closes #1116 
1. Go Identity Providers
2. Create an identity provider for each of the three "User-defined" options, and verify that the "alias" field is editable in the "create" form.
4. Save and go to the settings screen for an identity provider. 
5. Verify the alias is read-only in the settings screen.
6. Repeat for all the user-defined providers you added.
=> Identity Providers: sets alias to read-only in settings form

.husky/pre-commit
Running the unit tests on every commit is a tad annoying, since the CI already takes care of this let's drop it.
=> Stop running unit tests on commit

.github/workflows/publish.yml
Prevents Github Actions from starting a job to publish the package on forked repositories.
=> Prevent publish from running on forked repositories

src/clients/ClientSettings.tsx, src/clients/help.ts
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/997.
Adds missing tooltips/help for the 3 fields in Login settings noted in Issue https://github.com/keycloak/keycloak-admin-ui/issues/997: `Consent required`, `Display client on screen`, and `Client consent screen text`. Used text from the same fields that existed in the legacy admin console.
1. Go to `Clients`.
2. Scroll down to `Login settings.`
3. Verify that the `Consent required`, `Display client on screen`, and `Client consent screen text` fields now have a clickable help tooltip icon (?).
4. Verify that, when clicked, each of the above field's tooltip displays the correct help.
None
=> Add missing help for client login fields

package-lock.json, src/identity-providers/add/AdvancedSettings.tsx, src/identity-providers/add/DescriptorSettings.tsx, src/identity-providers/add/ReqAuthnConstraintsSettings.tsx, src/identity-providers/help.ts, src/identity-providers/messages.ts
Several fields in the original SAML identity provider were not working in the first pass, to be fixed later. 
This fixes it so all SAML fields should be working as expected. Any fields that are not working from here on should be filed as issues.
Verify that the following fields now work as expected in the SAML ID provider config, as they worked in the old console (set the value in the old console and verify that the new console reads the value, etc):
Single logout service URL
NameID policy format
Principal type
Principal attribute
Want AuthnRequests signed
Signature algorithm
SAML signature key name
Validating X509 certificates
Pass subject
Allowed clock skew
Comparison
AuthnContext ClassRefs
AuthnContext DeclRefs
Stored tokens readable
Hide on login page
Cypress tests coming in separate …
=> SAML ID provider cleanup

cypress/plugins/index.ts, cypress/tsconfig.json, package-lock.json, package.json
Allows Cypress to check files for type-errors as this is no longer performed by Snowpack which was disabled in #1168.
=> Check types when running Cypress

cypress/integration/realm_settings_test.spec.ts, package-lock.json, package.json, src/realm-settings/PoliciesTab.tsx, src/realm-settings/messages.ts
https://issues.redhat.com/browse/CLUX-262
Add policies list to client policies
1. Go to old admin console.
2. Go to Realm settings -> Client policies -> policies subtab
3. Click "Create" and fill out the form fields. 
4. Save the new policies.
5. Go to the new admin console
6. Go to Realm settings -> Client policies -> policies subtab
7. Verify the policies you created are listed in the table correctly.
- Enabled/disabled switches, and create/update/delete functionality will be implemented once https://github.com/keycloak/keycloak-nodejs-admin-client/pull/258 is merged
- Tests will be written once CRUD functionality can be implemented for policies (also dependent on https://github.com/keycloak/keycloak-nodejs-admin-client/pull/258)
=> Realm Settings(Client Policies): Add policies list

cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/LdapSettingsSearching.tsx, src/user-federation/messages.ts
In the in-development version of Keycloak the 'Edit mode' field for the LDAP provider is required. In order for the tests to pass in #1207 this will have to be merged.
=> Add editMode as a required field

.github/workflows/cypress.yml
Builds the latest version of Keycloak Server and runs the Cypress tests on top of it. This ensures that we remain compatible with Keycloak before release, as opposed to using the latest stable version, catching regressions in the process.
This also runs the complete integration of the Admin UI and Keycloak as we would for production by building the theme locally and installing it as a dependency when building Keycloak.
Closes #1036
=> Run the Cypress tests on master of Keycloak Server

src/identity-providers/add/AdvancedSettings.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1202.
Saw this issue and knew that i had already added the `Stored tokens readable` field for SAML, so just a very quick code change to make it applicable to OIDC and Keycloak OIDC as well.
In the old admin console:
1. Create an OIDC provider. 
2. Edit the OIDC provider and enable `Stored tokens readable`.
In the new admin console:
3. Edit the OIDC provider created in step 1.
4. Verify that the `Stored tokens readable` field is enabled.
5. Verify that you can change the setting in the new console and it persists on save.
Repeat steps 1-5 for a Keycloak OIDC provider.
None
=> Make 'stored tokens readable' field applicable to OIDC providers

src/identity-providers/add/AddMapper.tsx, src/identity-providers/help.ts, src/identity-providers/messages.ts
Closes #1205 
1. Go to Identity Providers -> Select a Provider -> Click Mappers tab
2. Add a mapper
3. Verify that the help text for the "Name" field is correct.
4. Verify that the help text for all mapper types changes with the selected mapper type.
=> Identity Providers(mappers): fix help text

.github/dependabot.yml
Dependabot can rebase open PRs very aggressively when another PR is merged, even if the HEAD is in a mergable state with master. This means that a lot of tasks such as the Cypress tests are kicked off unnecessarily causing the pipeline to get bogged down.
This change disables this behavior, which can instead by triggered manually by means of a comment on the respective PR.
=> Prevent Dependabot from automatically rebasing

.github/workflows/main.yml
Runs the different tasks (test, build, lint) in parallel and adds an additional level of caching so the CI can pass faster. The intention is to apply the learnings from this on the Cypress workflow as well but I wanted to work on something smaller first to understand Github actions a bit better.
=> Run jobs for CI in parallel

src/clients/ClientDetails.tsx, src/clients/messages.ts
This is one of the items on the sheet, we need to add a tooltip to explain to users that a client is bearer only. For more information see the [design](https://marvelapp.com/prototype/5di1ce1/screen/81685258).
=> Show a tooltip to explain bearer-only clients

cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/realm-settings/PoliciesTab.tsx, src/realm-settings/ProfilesTab.tsx, src/realm-settings/RealmSettingsSection.tsx
When a request is active and the user navigates away from the screen that triggered the request we need to cancel that request
and not set the state as that would create memory issues.
This PR changes how the state is set by using `useFetch` instead of setting the sate in the loader.
=> Small fix on policies tab

cypress/integration/identity_providers.spec.ts, cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts, src/identity-providers/add/AddMapper.tsx, src/identity-providers/add/DetailSettings.tsx, src/identity-providers/help.ts, src/identity-providers/messages.ts
Towards #1206
1. Go to Identity Providers
2. Create a SAML provider
3. Go to the "mappers" tab
4. Create a new mapper
5. In the "Mapper Type" dropdown, select "Username Template Importer"
6. Verify that the correct fields in the form are shown -- you should see new form fields for "Target" and "Template".
7. Fill out the fields and save. 
8. Verify the save is successful.
9. Go back to mappers and select the new mapper you just created.
10. Edit the mapper, save, and verify the mapper has been updated successfully.
=> Identity Providers(Mappers): Add create/edit functionality for mappers of type Username Template Importer

cypress/integration/clients_test.spec.ts, src/clients/ClientDetails.tsx
I added some logic to show a tooltip for bearer-only clients that was not yet tested, this PR adds the missing tests.
=> Add tests for bearer-only client details

src/clients/ClientDetails.tsx, src/clients/ClientsSection.tsx, src/clients/utils.ts
Clients that are intended to be used for authenticating a realm are not allowed to be deleted.
=> Remove ability to delete a realm client from the overview

src/PageHeader.tsx, src/authentication/AuthenticationSection.tsx, src/client-scopes/ClientScopesSection.tsx, src/client-scopes/details/MappingDetails.tsx, src/clients/ClientsSection.tsx, src/clients/import/ImportForm.tsx, src/clients/initial-access/CreateInitialAccessToken.tsx, src/clients/initial-access/InitialAccessTokenList.tsx, src/identity-providers/add/DetailSettings.tsx, src/realm-settings/NewClientProfileForm.tsx, src/realm-settings/ProfilesTab.tsx
This allows us to properly type-check the link functions which can catch regressions.
=> Use type-safe alternative for links

cypress/support/pages/admin_console/manage/clients/CreateClientPage.ts, src/client-scopes/details/ScopeForm.tsx, src/clients/ClientDetails.tsx, src/clients/ClientsSection.tsx, src/clients/add/GeneralSettings.tsx, src/clients/help.ts, src/clients/messages.ts, src/clients/utils.ts
Use more human readable names for client protocols in the UI such as when creating a client or viewing it. Also shows protocol badge, which closes #1276
=> Add a human readable name for client protocol

cypress/integration/identity_providers.spec.ts, cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts, src/identity-providers/add/AddMapper.tsx, src/identity-providers/add/AddMapperForm.tsx, src/identity-providers/help.ts, src/identity-providers/messages.ts
Closes #1206 
1. Go to Identity Providers
2. Create a provider and select a "Social" identity provider from the . 
3. Go to the "Mappers" tab
4. Click "Create a new mapper."
5. Verify that when a new mapper type is selected in the "Mapper Type" menu, the fields in the form change corresponding to the mapper type. 
6. Create a mapper for every type and verify the save is successful.
=> Identity providers(mappers): update form fields for all Social mapper types

src/user-federation/UserFederationLdapSettings.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1392.
Changed the LDAP user fed provider's form so that it only allows editing of the Vendor field when it is being created as new, otherwise aka on existing LDAP providers, it will be disabled.
1. Create a new LDAP user fed provider.
2. Verify that you can select a vendor type e.g. Active Directory.
3. Add values for all of the required fields and save the provider.
4. Open the main User Fed provider screen, click the card of the provider you saved in step 3.
5. Verify that the Vendor field is now disabled.
None
=> Disable vendor for existing LDAP providers

cypress/integration/realm_settings_test.spec.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/realm-settings/ClientProfileForm.tsx, src/realm-settings/ExecutorForm.tsx, src/realm-settings/NewClientPolicyForm.tsx
https://issues.redhat.com/browse/CLUX-293
1. Go to Realm Settings -> Client Policies tab
2. Click on the "policies" subtab
3. Create a policy
4. Go back to the data table and click the policy you just created
5. Change the name and/or description of the policy
6. Verify the save is successful
7. Go back to the data table and select the policy you just edited
8. Verify the data shown is correct
=> Client policies(policies): Add support for editing client policy data

cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/support/pages/admin_console/Masthead.ts
Follow-up to https://github.com/keycloak/keycloak-admin-ui/pull/1438, and provides a fix for the issue in which notifications can stack to a point that they will interfere with attempted actions on a modal. This solution dismisses the notifications instead of adding timed waits.
See https://github.com/keycloak/keycloak-admin-ui/pull/1438 for a more descriptive explanation of the problem. This solution adds an optional closeNotification parameter to the existing checkNotificationMessage function, so when you call the function to check the content of a notification message and pass true, it will dismiss the notification after checking the text. I chose to make it optional so it won't affect any legacy tests in which this is not an issue.
Verify that the ldap mapper test no longer fails …
=> Fix notification-related cypress failures without waits

.github/dependabot.yml
Version 6 of React Router is a major version with a lot of breaking changes, the [upgrade guide](https://reactrouter.com/docs/en/v6/upgrading/v5) recommends the following:
> We recommend waiting for the backwards compatibility package to be released before upgrading apps that have more than a few routes.
Therefore this change will prevent Dependabot from offering updates until we have decided a proper upgrade path.
=> Prevent Dependabot from offering major updates for React Router

cypress/integration/realm_settings_test.spec.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/components/dynamic/DynamicComponents.tsx, src/components/dynamic/MultivaluedListComponent.tsx, src/components/dynamic/components.ts, src/components/multi-line-input/MultiLineInput.tsx, src/realm-settings/NewClientPolicyCondition.tsx, src/realm-settings/NewClientPolicyForm.tsx, src/realm-settings/messages.ts, src/realm-settings/routes.ts, src/realm-settings/routes/EditCondition.ts
https://issues.redhat.com/browse/CLUX-329
Conditions are now editable.
1. Go to Realm settings -> Client Policies tab
2. Create a client policy if one does not exist yet.
3. Save the new client policy and then click "Add condition"
4. Add a new condition.
5. Navigate back to the "Edit policy" screen
6. Click the condition you created and update the field(s) under the condition type.
7. Save
8. Navigate back to the condition again and verify your changes were saved successfully.
=> Realm settings(client policies): Edit conditions in client policy

src/user-federation/help.ts, src/user-federation/ldap/mappers/LdapMapperUserAttribute.tsx, src/user-federation/messages.ts
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1480.
For the `user-attribute-ldap-mapper` mapper type, there was field missing called `Attribute default value`. Also, the default for the `Read only` switch was incorrectly set to `OFF`, when it should be `ON`.
1. Create an LDAP user federation provider and click the Mappers tab. 
2. Click `Add mapper` to create new mapper.
3. Select `user-attribute-ldap-mapper` as the mapper type.
4. Verify that the `Read only` field defaults to `On`, and that you can save/retrieve values for the newly-added `Attribute default value` field (and that help works, etc).
None
=> Add missing field/change default value in user-attribute-ldap-mapper

.github/dependabot.yml
Prevents major updates to `use-react-router-breadcrumbs` from being offered since it is not compatible with the version of React Router we are using.
=> Prevent Dependabot from offering major updates for React Router breadcrumbs

src/App.tsx, src/components/data-loader/DataLoader.test.tsx, src/components/form-access/FormAccess.test.tsx, src/components/realm-selector/RealmSelector.tsx, src/context/RealmsContext.tsx, src/context/realm-context/RealmContext.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm/add/NewRealmForm.tsx
Separates the concerns of the active realm and the realm overview into two separate contexts. This is also a prerequisite for some further improvements I want to make to the active realm context to reduce the amount of API calls.
This also improves memoization of the values the context provides, which will reduce [accidental re-renders](https://medium.com/@ryanflorence/react-context-and-re-renders-react-take-the-wheel-cd1d20663647).
=> Split realm context into two

src/user-federation/ldap/mappers/LdapMapperUserAttribute.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1484.
The original issue above was fixed as part of https://github.com/keycloak/keycloak-admin-ui/issues/1480. However, during testing, `Read Only` was defaulting to `ON` for `user-attribute-ldap-mapper` and `certificate-ldap-mapper`, which is incorrect. `Read Only` should only default to `ON` for `user-attribute-ldap-mapper`, and for `certificate-ldap-mapper` it should default to `OFF`. 
1. Go to User Federation > LDAP > LDAP Mappers.
2. Create new mapper.
3. Choose `certificate-ldap-mapper` as mapper type.
4. Verify that the `Attribute default value` field exists and can be save/retrieved.
5. On the create new mapper screen, verify that `Read only` defaults to `ON` when you select the `user-attribute-ldap-mapper` mapper type and …
=> Change read-only default based on mapper type

src/identity-providers/add/DescriptorSettings.tsx, src/identity-providers/help.ts, src/identity-providers/messages.ts
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1487.
Change the `Pass subject` field so it correctly points to the correct API value: `loginHint`.
Added the two missing fields: `Attribute Consuming Service Index` and `Attribute Consuming Service Name`.
1. Go to Identity providers > some SAML provider > Provider details.
2. Change the `Pass subject` switch to `ON` (or if it is already `ON`, change it to `OFF`).
3. Add values to the `Attribute Consuming Service Index` and `Attribute Consuming Service Name` fields, and verify their help works as expected.
4. Click `Save`.
5. Verify that the values of the three fields you modified are persisted in both the new and old admin consoles.
6. Change the three values in the old admin console and verify that they are persisted in the new …
=> Save Pass Subject correctly and add two missing fields to SAML IDP

src/user-federation/help.ts, src/user-federation/ldap/mappers/LdapMapperFullNameAttribute.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1485.
Added default value of `cn` to `LDAP full name attribute`.
Changed `Read only` default to `ON`.
Fixed `Write only` help, also fixed `Read-only` help which was pointing to the wrong help string.
1. Go to `User Federation > LDAP > LDAP Mappers`.
2. Create a new mapper.
3. Choose `full-name-ldap-mapper` as mapper type.
4. Verify that the `LDAP full name attribute` and `Read only`fields have default values of `cn` and `ON`, respectively.
5. Verify that the `Write only` help now displays correctly.
None
=> Fix defaults and help for full-name-ldap-mapper

src/user-federation/help.ts
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1486.
Fixed incorrect help string for hardcoded-ldap-group-mapper's Group field.
1. Go to User Federation > LDAP > LDAP Mappers.
2. Create new mapper.
3. Choose `hardcoded-ldap-group-mapper` as mapper type.
4. Verify that the help text for `Group` matches the string from the old console.
None
=> Fix help string for hardcoded-ldap-group mapper Group field

.github/workflows/cypress.yml, .github/workflows/main.yml, keycloak-theme/pom.xml, package-lock.json, package.json
Node 17 causes issues like failing to run the tests in Cypress 9 and breaks `import.mjs`. To mitigate this we can downgrade to version 16 which is an LTS version and will be supported for a while.
=> Downgrade to Node 16

keycloak-theme/pom.xml, src/dashboard/Dashboard.tsx, src/dashboard/messages.ts, src/environment.ts
Shows the exact commit hash of the Admin UI in the user-interface when built with Maven. This allows us to find out the exact version the user is running so we can reliably reproduce bugs and other issues.
The commit hash is shown on the dashboard page below the server information.
=> Show exact commit hash of Admin UI in interface

.dockerignore
Since merging #1572 the Docker build is no longer functional, this is because the Maven plugin that was included needs information from the `.git` directory. This PR allows this directory to be passed into the Docker build, which allows it to function again.
=> Include .git directory to fix Docker build

cypress/integration/realm_settings_test.spec.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/client-scopes/ClientScopesSection.tsx, src/clients/ClientDetails.tsx, src/clients/messages.ts, src/clients/scopes/AddScopeDialog.tsx, src/clients/scopes/ClientScopes.tsx, src/clients/scopes/client-scopes.css, src/clients/utils.ts, src/components/dynamic/MultivaluedScopesComponent.tsx, src/realm-settings/NewClientPolicyCondition.tsx, src/realm-settings/NewClientPolicyForm.tsx, src/realm-settings/RealmSettingsSection.css
https://issues.redhat.com/browse/CLUX-330
https://marvelapp.com/prototype/2b3ghc06/screen/81619352
- Adds screen, correct fields, and functionality to client policies -> add condition -> client-scopes condition type
- Supports save and edit functionality
1. Go to Realm settings -> Client policies -> Policies subtab
2. Create a new client policy if one doesn't exist yet.
3. Click on the client policy and under Conditions, click "Add condition"
4. Select the "client-scopes" condition type.
5. Verify that the UI and functionality match the design and work as expected. 
6. Save the client-scopes condition.
7. Navigate back to the client-scope condition type and verify that updating the data works as expected.
Dependent on #1532  - will rebase once merged to simplify review process.
=> Realm settings(Client policies): Update client-scopes condition to match new design

.github/workflows/publish.yml
Because we keep publishing snapshot versions to Github Actions we are not exceeding our storage limit. This change will automatically prune older snapshot versions so this storage is freed.
=> Prune older versions of published snapshots

src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1481.
As noted in https://github.com/keycloak/keycloak-admin-ui/issues/1481, the `Role Object Classes` issue was fixed as part of https://github.com/keycloak/keycloak-admin-ui/pull/1511.
For the `User roles retrieve strategy` issue, fixed it so the Active Directory vendor has three possible choices vs the other 4 vendor types which only have two available choices.
During testing, noticed that the field itself was not writing/reading correctly - this is because both roles and groups both use the user-roles-retrieve-strategy API value, but have different enums. It works correctly now.
And finally, with these changes, there were just far too many IF conditions within the Select so made one check for isRole and based on that load a …
=> Fix role-ldap-mapper defaults

cypress/support/pages/admin_console/manage/groups/GroupDetailPage.ts, package-lock.json, package.json, src/components/role-mapping/AddRoleMappingModal.tsx, src/components/role-mapping/RoleMapping.tsx, src/groups/GroupRoleMapping.tsx, src/groups/GroupsSection.tsx, src/groups/Members.tsx, src/groups/messages.ts
In the current admin console is possible to assign roles to groups and we need this functionality to adopt the new admin console in our keycloak installation
Added role mapping tab to the group detail page with the same UI/UX of the role mapping tab present in the user detail page
=> Added role mapping tab to group detail page

src/components/role-mapping/AddRoleMappingModal.tsx, src/groups/GroupsSection.tsx, src/user-federation/ldap/mappers/LdapMapperHardcodedLdapRole.tsx
Closes #1483 
@ssilvert it looks like clients without assigned roles are no longer displayed as options in the filter dropdown, which seems to  address the filtering issue you raised - please confirm
=> Fix modal title in User Fed -> hardcoded-ldap-mapper

cypress/integration/client_scopes_test.spec.ts, cypress/integration/clients_test.spec.ts, cypress/support/pages/admin_console/ListingPage.ts, cypress/support/pages/admin_console/manage/clients/ClientScopesTab.ts, cypress/support/util/AdminClient.ts, src/client-scopes/ClientScopesSection.tsx, src/clients/scopes/ClientScopes.tsx
Closes [#1359](https://github.com/keycloak/keycloak-admin-ui/issues/1359)
**Client scopes**
1. Go to **Client scopes** and create six new scopes so that there are 15 total
2. When the table is set to display 1-10 rows, go to the next page
3. You should have listed remaining 5 items in second page.
**Clients**
1. Go to **Clients** -> Clients list -> Navigate to client details page by item _Client ID_ link
2. Navigate to _Clients Scope_ tab and Add client scope to ensure client has more than 11 items added.
2. When the table is set to display 1-10 rows, go to the next page
3. You should have listed remaining items in second page.
=> Fix. 1359-Can't view all scopes.

src/authentication/AuthenticationSection.tsx, src/authentication/messages.ts, src/client-scopes/ClientScopesSection.tsx, src/client-scopes/messages.ts, src/clients/ClientsSection.tsx, src/clients/messages.ts, src/components/help-enabler/HelpHeader.tsx, src/components/view-header/ViewHeader.tsx, src/events/EventsSection.tsx, src/groups/GroupsSection.tsx, src/groups/messages.ts, src/help-urls.ts, src/identity-providers/IdentityProvidersSection.tsx, src/realm-roles/RealmRolesSection.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm-settings/messages.ts, src/sessions/SessionsSection.tsx, src/sessions/messages.ts, src/user-federation/UserFederationSection.tsx, src/user-federation/messages.ts, src/user/UsersSection.tsx, src/user/messages.ts
Add documentation links to main Admin Console pages.
Adds 'Learn more' links to each of the landing pages accessed via the Admin Console sidebar, as well as a link to the Server Administration Guide main page from the Documentation link in the masthead. Added placeholder descriptions for landing pages that were missing a subKey. 
For this first pass, did my best at linking each landing page to its most relevant section in the latest Server Admin Guide. The links/anchors in the helpUrls file should eventually be reviewed and/or edited by Documentation, as well as the text for any descriptions for landing pages which were missing subKeys (I just put in placeholders for now).
1. Navigate to any Admin Console section via the sidebar (e.g. Clients, Client scopes, Realm roles, etc.). 
2. Verify …
=> Add help url links

.github/workflows/cypress.yml
Enables the 'admin-preview' profile when building Keycloak so that the Admin UI is correctly installed. This allows the Cypress tests to run properly again.
=> Enable 'admin-preview' profile when building Keycloak

Dockerfile, start.mjs
New version of Keycloak is out, this keeps us up-to-date.
=> Update Keycloak development server to 16.1.0

.github/workflows/cypress.yml, cypress/integration/realm_settings_events_test.spec.ts, cypress/integration/realm_settings_tabs_test.spec.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/realm-settings/GeneralTab.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm-settings/help.ts, src/realm-settings/messages.ts, src/realm-settings/user-profile/JsonEditorTab.tsx, src/realm-settings/user-profile/UserProfileTab.tsx, src/utils/useIsFeatureEnabled.ts, start.mjs
1. Start the Keycloak server with the `DECLARATIVE_USER_PROFILE` feature enabled (`start.mjs` will do this for you).
2. Go to realm settings and enable the 'User Profile Enabled' switch
3. Verify the 'User Profile' tab is visible
=> Add toggle for user profile to realm settings

cypress/integration/login_test.spec.ts, cypress/integration/masthead_test.spec.ts, cypress/support/pages/admin_console/Masthead.ts
Updating Masthead tests in order to make it more clear and avoid a possible failure scenario of  the`isMobileMode` method
- Change the name of the method `isAdminConsole`, that could imply the return of a boolean, to `checkIsAdminConsole` to imply the assert check.
- Modify `isMobileMode` method to check the window size instead of just returning a variable (there are different scenarios where the mobile mode could change without updating the variable)
- [ x] Code has been tested locally by PR requester
=> Update Masthead tests

README.md, keycloak-theme/README.md
The name of the feature to enable the new Admin UI has changed, but this was not yet reflected in all the documentation. This PR resolves this issue.
Closes #1831
=> Use correct feature flag name in docs

cypress/integration/user_profile_tab.spec.ts, cypress/support/util/AdminClient.ts, src/common-messages.ts, src/realm-settings/messages.ts, src/realm-settings/user-profile/AttributesGroupTab.tsx, src/realm-settings/user-profile/JsonEditorTab.tsx, src/realm-settings/user-profile/UserProfileTab.tsx
Adds the overview for the attributes groups to the realm settings (as per [design](https://marvelapp.com/prototype/5eed532/screen/82246800)). Does not include the form to create a new attributes group to keep review size small.
To test, follow these steps:
1. Go to realm settings and enable the 'User Profile Enabled' switch
2. Save the realm settings
3. Use the old UI to create an attributes group (Realm Settings :arrow_right: User Profile :arrow_right: Attribute Groups)
4. Visit the same page in the new UI and verify it can be deleted from the context menu.
=> Add overview for attributes groups to realm settings

cypress/integration/realm_settings_events_test.spec.ts, package-lock.json, package.json, src/components/routable-tabs/RoutableTabs.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm-settings/routes/RealmSettings.ts
Introduces a new `RoutableTabs` component that allows (nested) tabs to be routed by means of the path of a path. This component is intended as a replacement for `KeycloakTabs`, which requires too much configuration and does not support nested tabs properly.
This is required in order to facilitate returning to nested tabs after filling in a form related to that tab (for example #1823).
=> Add RoutableTabs component for routed tabs

cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts, cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/support/util/ModalUtils.ts, package.json
Now that we are getting more consistent cypress test suite passes, the LDAP mapper tests stand out as being still a bit flakey and seem to sporadically cause an otherwise passing test suite to fail. 
After watching the vids of the failing ldap mapper tests, the issue is that when the final mapper is deleted, the timing causes the modal confirm button to be disconnected from the DOM. This is a common issue with cypress and although there are a few community-proposed workarounds, there is no cypress officially supported solution. In my testing, adding a force to the modal button click seems like the easiest resolution to the issue. 
To test these changes, I ran the mapper tests locally (UI and headless) 10 times, and then ran the mapper tests on CI 5 times, and then the full suite on CI an …
=> LDAP mapper test fix

src/realm-settings/LocalizationTab.tsx
Closes #1857 
Previously there was a `try/catch` block in the loader that prevented this error. The loader was recently refactored to a `useFetch` in #1663 to allow for message bundle functionality.
=> Fixes localization 500 error

cypress/integration/realm_settings_client_policies_test.spec.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/realm-settings/ClientProfileForm.tsx, src/realm-settings/NewClientPolicyForm.tsx, src/realm-settings/PoliciesTab.tsx, src/realm-settings/ProfilesTab.tsx, src/realm-settings/RealmSettingsSection.tsx, src/realm-settings/RealmSettingsTabs.tsx, src/realm-settings/routes/AddClientPolicy.ts, src/realm-settings/routes/AddClientProfile.ts, src/realm-settings/routes/ClientPolicies.ts, src/realm-settings/routes/RealmSettings.ts
@_**Haley Wang|246396** [said](https://keycloak.zulipchat.com/#narrow/pm-with/246396,327337-pm/near/265912135):
> Can the cancel here navigate back to the policies list instead of the profiles list?
This has been a repeated subject of discussion, as the current implementation of tabs does not support bookmarkable subtabs. @ssilvert recently brought this up while reviewing the code for client policies, and @yih-wang also requested a change here.
The PR includes a workaround for navigating back to the "Client Policies" subtab.
1. Go to Client Policies -> Policies subtab.
2. Click "Create client policy"
3. Click the "Cancel" button.
4. Verify that the UI takes you to the client policies list, rather than the client profiles list.
5. Repeat steps 1-2 and add a new client policy.
6. Go back to …
=> Realm settings: Return user to Policies subtab 

src/realm-settings/user-profile/AttributesGroupTab.tsx, src/realm-settings/user-profile/JsonEditorTab.tsx, src/realm-settings/user-profile/UserProfileContext.tsx, src/realm-settings/user-profile/UserProfileTab.tsx
Splits out the logic to fetch and update the User Profile configuration into a separate context that can be used on different routes to manipulate this data. This is work that is needed for a later PR implementing the other user profile screens.
=> Re-use User Profile logic from shared context

cypress/integration/user_fed_kerberos_test.spec.ts, cypress/support/pages/admin_console/manage/providers/PriorityDialog.ts, src/components/view-header/ViewHeader.tsx, src/identity-providers/IdentityProvidersSection.tsx, src/identity-providers/messages.ts, src/user-federation/ManagePriorityDialog.tsx, src/user-federation/UserFederationSection.tsx, src/user-federation/messages.ts
Adds priority configuration to user fed providers. Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1500.
Uses a drag and drop modal to change priority of existing user federation providers. Adds an optional lower button/link to the ViewHeader component, which in this case is being used to add the Manage priorities link. Also, user fed cards are now sorted alphabetically.
1. Go to User Fed and create at least two providers.
2. Select the Manage priorities link, the names should be in alphabetical order by default. 
3. Drag and drop one or more providers to create a new order, then click Save.
4. Exit and return to verify the priority order is retained. 
5. Go to the old console and verify that the order is correct in the Priority column in User Fed.
Could not get actual drag and …
=> Add priorities to User Federation

.github/workflows/publish.yml
The pruning of the Maven package we are publishing has been broken for a while. Tweaking these settings hopefully might cause it to work again.
=> Tweak some settings to (hopefully) fix package pruning

Dockerfile, start.mjs
Updates both the Docker and scripted development server to the latest version of Keycloak. This does not yet move us to the Quarkus version, for this a separate issue has been created (#2104).
=> Update Keycloak development server to version 17.0.0

cypress.json, cypress/integration/authentication_test.spec.ts, cypress/integration/clients_test.spec.ts, cypress/integration/masthead_test.spec.ts, cypress/integration/partial_export_test.spec.ts, cypress/integration/realm_settings_client_policies_test.spec.ts, cypress/integration/realm_settings_client_profiles_test.spec.ts, cypress/integration/realm_test.spec.ts, cypress/integration/realm_user_registration.spec.ts, cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts, cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/support/pages/LoginPage.ts, cypress/support/pages/admin_console/CreateRealmPage.ts, cypress/support/pages/admin_console/ListingPage.ts, cypress/support/pages/admin_console/Masthead.ts, cypress/support/pages/admin_console/SidebarPage.ts, cypress/support/pages/admin_console/manage/clients/InitialAccessTokenTab.ts, cypress/support/pages/admin_console/manage/providers/PriorityDialog.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, cypress/support/pages/admin_console/manage/realm_settings/UserRegistration.ts, cypress/support/util/ModalUtils.ts, cypress/support/util/keycloak_hooks.ts, src/clients/messages.ts
Adds tests to Clients for the List and Initial Access Token screens and fix a notification message
Adds tests to Clients for the List and Initial Access Token screens and fix the notification message when deleting an initial access token fixing issue #1936 
- [ x] Code has been tested locally by PR requester
=> Add Clients tests, fix notification message and stabilize tests

src/user-federation/custom/CustomProviderSettings.tsx, src/user-federation/kerberos/KerberosSettingsRequired.tsx, src/user-federation/ldap/LdapSettingsAdvanced.tsx, src/user-federation/ldap/LdapSettingsConnection.tsx, src/user-federation/ldap/LdapSettingsGeneral.tsx, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1391.
Added componentId to 'Test connection' and 'Test authentication' calls so the payload is the same as the old console. Verified that it works with LDAP server (see verification steps). Also fixed several broken help IDs in the LDAP provider form, I suspect they were the victim of an overzealous search/replace for user --> users.
1. Go to User Fed and create a new LDAP provider.
2. Add the following (leave everything else as the default):
- **Connection URL**: `ldap://ldap.forumsys.com:389`
- **Users DN**: `dc=example,dc=com`
3. Click **Test connection**. It should say that it succeeded, and the payload in the Network call should include componentId.
4. Add the following (leave everything else as the default):
- …
=> Add componentId to LDAP provider test connection/authorization

src/authentication/routes/Authentication.ts, src/authentication/routes/Flow.ts, src/components/form-access/FormAccess.tsx, src/realm/add/NewRealmForm.tsx, src/realm/routes/AddRealm.ts, src/sessions/routes/Sessions.ts
Fixes #2097
See https://www.keycloak.org/docs/latest/server_admin/#_admin_permissions
All left navigation that are visible should work when the admin has limited permissions.  If user does not have enough permission to render the screen then the navigation link should not be shown.
Also, a master realm user should be able to create realms with only "create-realm" access and should not need full "admin" access.
- [N/A] User-visible strings are using the react-i18next framework (useTranslation)
- [N/A] Help has been implemented
- [N/A] axe report has been run and resulting a11y issues have been resolved
A separate comprehensive test needs to be written for admin role settings.
=> Fix bugs when admin has limited roles.

src/components/alert/Alerts.tsx, src/utils/useSetTimeout.test.ts, src/utils/useSetTimeout.ts
Creates a specialized `useSetTimeout()` hook that can be used to set timeouts that are tied to a component's lifecycle. This means that if a timeout is scheduled and a component unmounts in the mean time it does not trigger the callbacks. This prevents accidental memory leaks such as setting state after a component is unmounted.
This PR is facilitating for #2103 as well.
=> Add 'useSetTimeout' hook to manage timers

.github/workflows/cypress.yml
Skips the build of the account v2 theme so the build for Keycloak server is sped up. This shaves 1½ minutes off the total time to run the Cypress tests.
=> Speed up CI by skipping account v2 theme in build

cypress/integration/authentication_test.spec.ts, cypress/integration/client_authorization_test.spec.ts, cypress/integration/client_scopes_test.spec.ts, cypress/integration/clients_saml_test.spec.ts, cypress/integration/clients_test.spec.ts, cypress/integration/group_test.spec.ts, cypress/integration/partial_export_test.spec.ts, cypress/integration/partial_import_test.spec.ts, cypress/integration/realm_roles_test.spec.ts, cypress/integration/realm_settings_client_policies_test.spec.ts, cypress/integration/realm_settings_client_profiles_test.spec.ts, cypress/integration/realm_settings_events_test.spec.ts, cypress/integration/realm_settings_tabs_test.spec.ts, cypress/integration/realm_settings_user_profile_tab.spec.ts, cypress/integration/realm_test.spec.ts, cypress/integration/realm_user_registration.spec.ts, cypress/integration/users_test.spec.ts, cypress/support/util/AdminClient.ts
As discussed in the team meeting, this allows all tests to use the same admin client instance. This reduces the amount of times we need to construct an instance in individual tests.
=> Use a single admin client instance for all tests

package.json
This more accurately reflects what browser our actual users are running. Another advantage is that this will use a recent version of Chrome, whereas Cypress ships with a version of Electron that is locked to the Cypress version.
=> Run Cypress tests on Chrome when running headlessly

cypress/support/pages/admin_console/manage/clients/AuthorizationTab.ts, cypress/support/util/grantClipboardAccess.ts
Adds a utility method to allow access to the clipboard during Cypress tests. This allows the client authorization tests to pass as expected.
=> Allow access to clipboard in Cypress tests

src/client-scopes/details/ScopeForm.tsx
Closes #2051 & #1991 
Fixed **Consent screen text** input was not shown when switch **Display on consent screen** was turned ON. Also fixed issue when **Consent screen text** was impossible to set/modify.
=> fixed Consent screen text was not shown

cypress/integration/realm_roles_test.spec.ts
The role to edit was sometimes not there as the test didn't wait for the promise
=> fixed async role creation bug

cypress/integration/realm_settings_events_test.spec.ts
After doing some testing locally it looks like all tests are passing, including the skipped ones. Therefore this PR restores all skipped tests back to their original state.
=> Restore previously skipped tests

src/client-scopes/details/ScopeForm.tsx, src/client-scopes/form/ClientScopeForm.tsx
Closes #1997 
During creation of new client scope, if name contains white-space, error message is shown
=> fixed msg error when clientScope created with whitespace (#1997)

cypress/integration/partial_import_test.spec.ts, cypress/integration/user_fed_kerberos_test.spec.ts, cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts
Some tests are quite flaky on the CI. This is an issue as we now have to run all the tests locally for each PR to ensure that the tests are running correctly, taking up precious developer time.
This PR skips the tests that are flaky so that we can continue to run the tests on our CI instead of locally. The intention is that these tests will be fixed and made more resilient over time so they no longer have to be skipped.
=> Skip tests that are often flaky on CI

cypress.json
Disables the test retries for Cypress in order to make it more apparent which tests are flaky. The idea is to keep this PR open and rebased and provide the actual test fixes in other PRs until we see a green CI here consistently.
=> Disable test retries for Cypress

cypress/integration/client_authorization_test.spec.ts, cypress/integration/client_scopes_test.spec.ts, cypress/integration/clients_saml_test.spec.ts, cypress/integration/clients_test.spec.ts, cypress/integration/masthead_test.spec.ts, cypress/integration/partial_import_test.spec.ts, cypress/integration/realm_roles_test.spec.ts, cypress/integration/realm_settings_client_policies_test.spec.ts, cypress/integration/realm_settings_client_profiles_test.spec.ts, cypress/integration/realm_test.spec.ts, cypress/integration/realm_user_registration.spec.ts, cypress/integration/users_test.spec.ts, cypress/support/index.ts, cypress/support/util/keycloak_hooks.ts
This changes ensures that the Keycloak session cookies are preserved between tests. This remove the need to manually call `keycloakBeforeEach()` for each test case.
=> Always preserve session cookies for all tests

src/realm-settings/NewClientPolicyForm.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1788.
The navigation destination for client profile links was empty, added the appropriate link.
See https://github.com/keycloak/keycloak-admin-ui/issues/1788 for steps to reproduce, verify that clicking any of the client profiles will now navigate to that particular client profile, instead of jumping to the realm homepage.
None
=> Fixes client profile links

src/user/UsersTabs.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1716.
Simple fix to change order of User details tabs to match design.
1. Go to Users and select a user to get details.
2. Verify that the order is now Details, Attributes, Credentials, Role mapping, Groups, Consents, and Identity provider links.
None
=> Change tab order in user details

src/clients/ClientSettings.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1434.
Issue https://github.com/keycloak/keycloak-admin-ui/issues/1434 requests that SAML client settings match the [design](https://marvelapp.com/prototype/880h4f8/screen/82212914) by adding two missing fields (`Always display in console` and `Front channel logout`) and changing the section order. The two missing fields were actually added as part of [this PR](https://github.com/keycloak/keycloak-admin-ui/pull/2165) to fix a [duplicate issue](https://github.com/keycloak/keycloak-admin-ui/issues/2026). So this fix just changes the order to match the original design.
Verify that the SAML client exactly matches the original design here:
https://marvelapp.com/prototype/880h4f8/screen/82212914
None
=> Change order of client sections

cypress/integration/user_fed_kerberos_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/kerberos/KerberosSettingsRequired.tsx
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=A741
Added tests for all cache policy types and general settings switches (rows 743, 744, 746, 747, and 750 in the [test coverage dashboard](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516).
The user fed kerberos test runs without errors.
Tests passed locally in cypress UI and headless.
=> Adds all missing user fed kerberos tests

cypress/integration/user_fed_ldap_mapper_test.spec.ts
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=720:722
Added tests for searching LDAP mappers, including tests for strings that return one result, multiple results, all results, and no results. Also sped up the test a bit by removing the certificate ldap mapper test, it is already being tested in the CRUD test section so it was essentially being tested twice.
The LDAP mappers test runs without errors.
Tests passed locally in cypress UI and headless.
=> Adds tests for searching LDAP mappers

.github/workflows/cypress.yml
Removes the `--proxy=none` option passed to the Keycloak server which is currently preventing the server from starting correctly.
=> Remove no-proxy argument from Keycloak server

cypress/plugins/index.ts, package-lock.json, package.json
Depending on how the tests are ran removing the video files can cause an exception (especially when running in parallel). This aligns with what the Cypress documentation [recommends](https://docs.cypress.io/guides/guides/screenshots-and-videos#Only-upload-videos-for-specs-with-failing-or-retried-tests).
Also includes changes to properly await the deletion of the files.
=> Use 'del' to remove passing test videos

.github/workflows/cypress.yml, start.mjs
Make use of keycloak-quarkus features option and add fine grained authorization.  This is now preferred to using the java system properties.
Based on https://www.keycloak.org/server/features
I am unable to run the start.mjs file on my box, so I need someone else to verify that this works.
=> Change to using quarkus features option and add fine grained auth

.github/dependabot.yml
The new version of `react-flow-renderer` has some breaking changes which will require a manual upgrade. For that reason, let's disable this dependency update for now.
=> Disable Dependabot updates for react-flow-renderer

.github/workflows/codeql-analysis.yml
The changes proposed here will run the CodeQL analysis in the admin-ui
repository, skipping `cypress` and `mocks` paths to prevent false
alerts.
Closes #2261
- [Pull-request with the worst practices](https://github.com/keycloak-poc/keycloak-admin-ui/pull/72/files)
=> Introduce CodeQL analysis

src/authentication/RequiredActions.tsx
used to be that it would use disabled to indicate that it had been registered
now it only is disable when it's not enabled.
fixes: #1964
=> changed to be disabled when not enabled

README.md
`./start.mjs` throws an error if `npm install` isn't executed first -- we should clarify in the README that `npm install` is the first step to building/running
=> Update README to include npm install

src/realm-settings/NewAttributeSettings.tsx
Fix "cannot destructure property error" when selecting the "Create Attribute" button on Realm-settings -> User Profile tab
1. Navigate to Realm-settings -> User Profile tab and select the "Create Attribute" button.
2. Blank form should display.
=> fixed cannot destructure property error

.github/dependabot.yml
This will allow Dependabot to keep our Github Actions up-to-date automatically.
=> Automatically update Github Actions using Dependabot

src/util.test.ts, src/util.ts
Empty attributes `attributes: [{ key: "", value: "" }]` where not detected as such, this fixes that
=> fixes empty key value convert

cypress/integration/user_fed_ldap_hardcoded_mapper_test.spec.ts, cypress/integration/user_fed_ldap_mapper_test.spec.ts, cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/LdapSettingsConnection.tsx
Test coverage dashboard:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516
Adds several cypress tests for the Connection settings and General settings sections of the user fed LDAP provider UI. Specifically, addresses rows [686-692](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=686:692) and [694](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=694:694) in the test coverage dashboard.
Also cleaned up and hardened existing user fed tests and made them more consistent.
Verify that tests pass.
All of the following four tests pass consistently when run locally in the cypress UI and headless:
- …
=> Adds LDAP connection and general tests

cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/LdapSettingsKerberosIntegration.tsx, src/user-federation/ldap/LdapSettingsSynchronization.tsx
Test coverage dashboard:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516
Adds several cypress tests for the Kerberos Integration settings and Synchronization settings sections of the user fed LDAP provider UI. Specifically, addresses rows [696-699](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=696:699) and rows [709-714](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=709:714) in the test coverage dashboard.
Verify that tests pass
The user_fed_ldap_test.spec.ts passes consistently locally when run via the cypress UI or headless.
=> Adds LDAP kerberos integration and synchronization tests

cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/LdapSettingsSearching.tsx
Test coverage dashboard:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516
Adds several cypress tests for the LDAP searching and updating section of the user fed LDAP provider UI. Specifically, addresses rows [701-707](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=701:707) in the test coverage dashboard.
Verify that tests pass.
The user_fed_ldap_test.spec.ts passes consistently locally when run via the cypress UI or headless.
=> Adds LDAP searching tests

src/groups/GroupTable.tsx, src/groups/SearchGroups.tsx
If the user does not have "manage-users" and "query-clients" roles, clicking on a group will result in a 403 error.
1. Create a group with an admin user.
2. Create test a user with realm-management roles of "query-groups", "query-users", and "view-realm".
3. Log in with the test user and go to groups section.
4. Click on the group.
This change deals with the problem by making so you can view that the group exists, but you can't manage the group.  It also doesn't allow you to attempt to create a group without proper permissions.
=> Avoid errors in Groups section.

.github/workflows/cypress.yml, cypress.json
Changes the CI so that the Cypress tests are ran in parallel across multiple jobs using the [Cypress Dashboard](https://docs.cypress.io/guides/dashboard/introduction). This should speed up our testing suite significantly and provide us with tooling to detect and mitigate flaky tests.
=> Run Cypress tests in parallel to optimize performance

.github/workflows/cypress.yml
The Cypress dashboard already takes care of this, so we no longer need to upload this on Github.
=> Skip uploading Cypress assets

.github/workflows/cypress.yml
Removes the Java setup from the testing job as this is not required to run the Quarkus server.
=> Remove Java setup from testing job

src/realm-settings/user-profile/attribute/AddValidatorDialog.tsx, src/realm-settings/user-profile/attribute/AttributeValidations.tsx
Used to only remove the validators as long as the dialog stayed open
now also removes the already installed validators when the dialog
is opened again.
fixes: #2397
=> now also removes the already added validators after closing the dialog

cypress/integration/partial_import_test.spec.ts
An attempt to fix "Displays user options after realmless import and does the import" test in partial_import_test suit.
1. Run tests in `partial_import_test.spec.ts` locally. All tests in this suit should be greeen.
=> wip: Partial import test fix

cypress/integration/user_fed_ldap_test.spec.ts, cypress/support/pages/admin_console/manage/providers/ProviderPage.ts, src/user-federation/ldap/LdapSettingsAdvanced.tsx
Test coverage dashboard:
https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516
Adds cypress tests for the **Advanced settings** and **Cache settings** sections of the user fed LDAP provider UI. Specifically, addresses rows [676-678](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=676:678) and [680-684](https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=680:684) in the test coverage dashboard.
Verify that tests pass.
All tests in user_fed_ldap_tests.spec.ts passed locally in the cypress UI and headless.
=> Adds tests for LDAP provider advanced and cache settings

cypress/integration/realm_settings_events_test.spec.ts, cypress/support/pages/admin_console/ListingPage.ts, cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts, src/realm-settings/keys/KeysListTab.tsx, src/realm-settings/keys/KeysProvidersTab.tsx
Adds search and delete tests for keys -> providers tests in Realm Settings, also tests active/passive/disabled dropdown filter
- https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=461:461
- https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=449:449
- https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=452:454
- https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=459:459
=> Add search and delete to key providers tests

keycloak-theme/.gitignore, keycloak-theme/README.md, keycloak-theme/pom.xml, keycloak-theme/src/main/resources/META-INF/keycloak-themes.json
Changes the build so the theme can be [deployed as an archive](https://www.keycloak.org/docs/latest/server_development/index.html#deploying-themes). This allows the theme to be added into the Keycloak installation as a JAR, without the need to extract it.
This also helps eliminate the need to build the Keycloak server and theme together, which can simplify our integration tests and possibly reduce the time needed to run the tests in a future change.
Merge together with: https://github.com/keycloak/keycloak/pull/11281
=> Make theme deployable from archive

.github/workflows/cypress.yml
Since the Cypress video upload is broken often we want to restore this functionality.
=> Uploading Cypress assets to Github

.github/workflows/codeql-analysis.yml, .github/workflows/cypress.yml, .github/workflows/main.yml, README.md, package.json, scripts/import-client.mjs
Version 18 of Node.js has [been released](https://nodejs.org/en/blog/announcements/v18-release-announce/), this brings us up-to-date with the latest.
=> Upgrade to version 18 of Node.js

src/components/key-value-form/AttributeForm.tsx, src/user/UserAttributes.tsx, src/user/UserForm.tsx, src/user/UserGroups.tsx, src/user/UsersSection.tsx, src/user/UsersTabs.tsx, src/user/routes/User.ts
This implements fine-grained permissions for the user section only.
Implements part of https://github.com/keycloak/keycloak-admin-ui/issues/2403
This is a fairly simple approach.  In some cases we could do better with how we present a restricted screen to the user.  But overall it's on par with the implementation in the old UI.  So I think this approach is good for a first pass and we can improve it later.  Higher priority is to get all of FGP implemented and then create an FGP test suite.
Since the [fine-grained permissions configuration screens](https://github.com/keycloak/keycloak-admin-ui/issues/2402) are not implemented in the new UI yet, verification requires going to the old UI.  You can follow the [examples in the documentation](https://www.keycloak.org/docs/latest/server_admin/#_f …
=> Fine-grained permissions for user section.

cypress/integration/masthead_test.spec.ts, cypress/integration/sessions_test.spec.ts, package-lock.json, package.json
Updated keycloak-js on the admin client to version 18 so that the redirect url problem is fixed and we can enable the logout tests again.
=> with keycloak-js updated logout works again

public/resources/en/identity-providers-help.json, public/resources/en/identity-providers.json, src/identity-providers/add/DescriptorSettings.tsx
Fixes #2560 as requested on https://github.com/keycloak/keycloak/pull/11084 .
Added an option to enter the expected Identity Provider Entity ID.
=> Fix #2560 SAML Broker: Add option to validate IdP Entity ID

src/groups/GroupAttributes.tsx, src/groups/GroupTable.tsx, src/groups/GroupsSection.tsx, src/groups/Members.tsx
This implements fine-grained permissions for the group section only.
Implements part of https://github.com/keycloak/keycloak-admin-ui/issues/2403
This implementation differs somewhat from what we see in the old UI.  I believe that the old UI and back end has some bugs where a user clearly has "manageMembership" authority but is still not allowed to add/remove users from the group.  In this case, the new UI will allow the administrator to add/remove users but will get an error from the back end.
You can follow the [examples in the documentation](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions).
You can also see the access object that is returned in the record when a group is queried. It looks something like this: …
=> Fine-grained permissions for groups

.github/dependabot.yml, package-lock.json, package.json
Since we will need to update various components in order to support React 18 it's better to lock the version for now.
=> Lock React and related dependencies to version 17

src/realm-roles/RealmRoleForm.tsx
On the edit details screen there are 2 headers rendered
=> Don't render create header when editing

src/clients/import/ImportForm.tsx
Prevents the form data from being reset when component unmounts. Closes #2471.
=> Fix client import form state

src/authentication/form/NameDescription.tsx, src/client-scopes/details/ScopeForm.tsx, src/clients/ClientDescription.tsx, src/clients/ClientSettings.tsx, src/clients/authorization/AuthorizationExport.tsx, src/clients/authorization/PermissionDetails.tsx, src/clients/authorization/policy/NameDescription.tsx, src/clients/keys/Certificate.tsx, src/clients/scopes/GeneratedCodeTab.tsx, src/components/download-dialog/DownloadDialog.tsx, src/components/keycloak-text-area/KeycloakTextArea.tsx, src/realm-roles/RealmRoleForm.tsx, src/realm-settings/ClientProfileForm.tsx, src/realm-settings/NewClientPolicyForm.tsx
The default `TextArea` from PatternFly modifies the `onChange` handler so the value can be more easily accessed. This change in the function signature is however incompatible with what React Hook Form expects. This PR therefore introduces a `KeycloakTextArea` that restores the function signature, fixing the integration.
This change is needed as part of moving towards updating React Hook Form to version 7 (#812).
=> Replace text areas with KeycloakTextArea

cypress/integration/realm_settings_events_test.spec.ts, src/realm-settings/LocalizationTab.tsx
It seems that locale edit is disabled and enabled only after save, this should not be the case.
Even when internationalization isn't enabled you should be able to change the default (English) one.
=> Locale edit shouldn't be disabled

src/clients/ClientDetails.tsx, src/clients/ClientSettings.tsx, src/clients/ClientsSection.tsx, src/clients/advanced/SaveReset.tsx, src/clients/authorization/Settings.tsx, src/clients/scopes/ClientScopes.tsx, src/clients/service-account/ServiceAccount.tsx, src/components/role-mapping/RoleMapping.tsx, src/components/view-header/ViewHeader.tsx, src/realm-roles/RolesList.tsx
The PR fixes role-based authorization in the Clients section by hiding components or making them read-only as needed.
This is in preparation for implementing fine-grained authorization, where flags such as `isManager` will also include a check for fine-grained authorization.
To verify the PR, it is best to log into a test realm with a test user.  Then set limited client roles for that user on the realm-management client.
To see the Clients section the user should have "view-clients" and "query-clients" roles.
To see the Permissions tab, the user also needs "manage-authorization" role.
To see Keys and Credentials tabs, the client needs to have `Client authentication` enabled.
To see Authorization tab, the client needs to have `Authorization` enabled.
To see Service account roles tab, the …
=> Fix role-based authorization in Clients section.

public/resources/en/realm-settings-help.json
Small fix for tooltip text.
1. Go to Realm settings > Events > User events settings 
2. Verify that tooltip text for "Save events" is reading "If enabled, user events are saved to the database, which makes events available to the admin and account management consoles."
=> User events tooltip text fix

src/clients/ClientDetails.tsx, src/clients/add/SamlSignature.tsx
saml.server.signature = boolean
saml.server.signature.keyinfo.xmlSigKeyInfoKeyNameTransformer and objec
fixes: #2467
=> added workaround for overlapping property

src/context/auth/AdminClient.tsx
Previously, the admin-console did not initialize properly when users configured the admin-hostname different from the frontend-hostname.
E.g:
--hostname: id.acme.test
--hostname-admin: admin.acme.test
produces an `environment` like:
...
- ´authUrl: https://admin.acme.test:8443/auth/...´
- ´authServerUrl: https://id.acme.test:8443/auth/...´
Since `authUrl` was used, the admin-client tried to create an 3p-check-iframe from
`https://admin.acme.test:8443/auth/...` which is not allowed since only `https://id.acme.test:8443/auth/...´ is allowed.
Using the `authServerUrl` ensures that the correct `IdP` url is used.
Fixes #2703
Signed-off-by: Thomas Darimont <thomas.darimont@googlemail.com>
=> Use authServerUrl instead of authUrl to initialize keycloak client (#2703)

src/clients/AdvancedTab.tsx, src/clients/ClientDescription.tsx, src/clients/ClientDetails.tsx, src/clients/ClientSettings.tsx, src/clients/ClientsSection.tsx, src/clients/add/GeneralSettings.tsx, src/clients/advanced/AdvancedSettings.tsx, src/clients/advanced/AuthenticationOverrides.tsx, src/clients/advanced/FineGrainOpenIdConnect.tsx, src/clients/advanced/OpenIdConnectCompatibilityModes.tsx, src/clients/authorization/AuthorizationEvaluate.tsx, src/clients/authorization/AuthorizationExport.tsx, src/clients/authorization/PermissionDetails.tsx, src/clients/authorization/ResourceDetails.tsx, src/clients/authorization/ScopeDetails.tsx, src/clients/authorization/policy/PolicyDetails.tsx, src/clients/import/ImportForm.tsx, src/clients/keys/Keys.tsx, src/clients/routes/DedicatedScopeDetails.ts, src/clients/routes/NewPermission.ts, src/clients/routes/NewPolicy.ts, src/clients/routes/NewResource.ts, src/clients/routes/NewScope.ts, src/clients/routes/PermissionDetails.ts, src/clients/routes/PolicyDetails.ts, src/clients/routes/Resource.ts, src/clients/scopes/ClientScopes.tsx, src/clients/scopes/DecicatedScope.tsx, src/clients/service-account/ServiceAccount.tsx
The PR fixes fine-grained authorization in the Clients section by hiding components or making them read-only as needed.
Primarily, the PR uses access.configure or access.manager flags to hide components or make them read-only.
Strangely, I have found that everything in the authorization tab should only require "read-clients" access.  I suspect this may be wrong, but the old UI and the API both allow authorization changes for users with "read-clients" access.  So I have changed that in this PR as well.
To verify the PR, it is best to log into a test realm with a test user.  Then set limited client roles for that user on the realm-management client.
To see the Clients section the user should have "view-clients" and "query-clients" roles.
To see the Permissions tab, the user also needs …
=> Fine grained clients

cypress/integration/clients_saml_test.spec.ts
Due to a bug Cypress accidentally exposed `cy.waitFor()` which has been removed in newer versions (see https://github.com/cypress-io/cypress/issues/20556). In order for the tests to pass on newer versions of Cypress we need to replace instances of `cy.waitFor()` with `cy.wait()`.
Needed to land #2707.
=> Use cy.wait() instead of cy.waitFor()

.github/workflows/codeql-analysis.yml
The code quality check running on every commit is causing Github Actions to bog down. Running these tasks on a nightly schedule will alleviate this issue.
=> Run code quality check on a nightly schedule

keycloak-theme/src/main/resources/theme/keycloak.v2/admin/theme.properties
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/2778
From my testing, this should fix the problem with User Federation error messages that are not localized.
The problem was that we have not been including a theme.properties.  So unless you run the old admin console first, the message bundles for localization of error messages will never get loaded.
See steps in https://github.com/keycloak/keycloak-admin-ui/issues/2778
But note that you wouldn't see the issue if you had already run the old console against the keycloak database.  So for a valid test you need to start with a clean database (or just delete it).
=> Add theme.properties to the build.

public/resources/en/realm-settings.json, src/client-scopes/add/MapperDialog.tsx
Fix for #2817 
<!--
Add the steps required to verify this change. Keep in mind that these steps should be written so groups unfamiliar with the 
new functionality can follow them, such as QE or documentation.
1. Go to 'Realm settings', select the 'Client policies' tab, and select the 'Policies' subtab.
2. Click 'Create client policy' and verify that the heading is now reading 'Create client policy.'
=> Fixed heading for create client policy #2817

src/client-scopes/add/MapperDialog.tsx
Fix for #2810 
<!--
Add the steps required to verify this change. Keep in mind that these steps should be written so groups unfamiliar with the 
new functionality can follow them, such as QE or documentation.
1. Go to 'Client scopes', select scope, and go to the "Mappers" tab.
2. Click "Configure a new mapper" and verify that the dialog is showing the "Configure a new mapper" header
=> Fixed subheading in the dialog #2810

public/resources/en/client-scopes.json, src/client-scopes/add/MapperDialog.tsx
Fix for https://github.com/keycloak/keycloak-admin-ui/issues/2810
1. Go to `Client scopes`, select scope, and go to the 'Mappers' tab.
2. Click 'Configure a new mapper' and verify that the subheading is reading 'Choose any of the mappings from this table'
=> Fixed subheading text for "Configure a new mapper" dialog

cypress/e2e/realm_settings_tabs_test.spec.ts, src/clients/ClientDescription.tsx, src/clients/add/LogoutPanel.tsx
In Clients --> Settings, the "Always display in console" field was missing from OIDC clients.
Also, for SAML, Front Channel Logout was in General Settings instead of Logout settings.
Verify that "Always display in console" is always visible for both OIDC and SAML clients.
Verify "Front Channel Logout" is in Logout settings for both OIDC and SAML clients.
- [N/A] axe report has been run and resulting a11y issues have been resolved
- [N/A] Unit tests have been created/updated
=> Always Display in Console missing from OIDC clients

src/authentication/AuthenticationSection.tsx
=> remove bind flow if the flow is already bound

src/util.ts
Replaces all instances of `.hasOwn()` with external calls to `.hasOwnProperty()` (see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#using_hasownproperty_as_a_property_name)). This is because the current [ESR version](https://support.mozilla.org/en-US/kb/switch-to-firefox-extended-support-release-esr) of Firefox [does not support](https://caniuse.com/mdn-javascript_builtins_object_hasown) this functionality yet.
Closes #2864.
=> Replace .hasOwn() with .hasOwnProperty()

src/utils/isDefined.test.ts, src/utils/isDefined.ts, src/utils/useRequiredContext.ts
Adds an easy to use utility function to check for values that are defined (anything not `undefined` or `null`). This allows for filtering collections in a manner that will provide type safety guarantees.
=> Add utilty function to check for defined values

src/dashboard/ProviderInfo.tsx
Fixes and closes https://github.com/keycloak/keycloak-admin-ui/issues/2839
Verification: 
1. Run axe scan for the `Provider info` tab on the Home page.
=> Serious accessibility fixes for Home/Provider Info page #2839

src/realm-settings/RealmSettingsTabs.tsx, src/realm-settings/realm-settings-section.css
Fix for 3 &4 #2851. Closes #2851
1. Go to the `Client policies` tab under `Realm settings` and scan the page using AXE.
2. Verify that all serious ay11 issues have been fixed.
=> Fixed serious ay11 issues on Realm-settings/Client policies tab

cypress.config.ts, package-lock.json, package.json
Allows us to use Vite to preprocess our test files. This prevents issues that are occurring when importing libraries built with modern JavaScript, which the standard compiler cannot handle.
This change is needed to support the new version of the Admin Client (see #2954).
=> Preprocess Cypress tests with Vite

src/clients/ClientSettings.tsx, src/clients/add/LogoutPanel.tsx
I spoke with Pedro about what login and logout settings actually make sense for SAML.
All login settings should apply to SAML.
For Logout, only "Front channel Logout" should be there for SAML.  In the future, it might make sense to move the settings related to SAML front channel from the Advanced tab to the Settings tab.
=> Fix login and logout settings for SAML

src/clients/authorization/AuthorizationEvaluate.tsx, src/clients/authorization/auth-evaluate.css, src/clients/authorization/key-based-attribute-input.css
Close #2159
See #2159
Clients -> Client details -> Permissions -> Enable permissions -> Scope Name -> Cancel button -> Authorization -> Evaluate
The "Resources and Authentication Scopes" and "Contextual Attributes" stick out on the right side of the page. This was already present. I've changed the width of the input/selectable fields from 500px to 400px to make it less noticeable.
=> fine-tuning of layout in Authorization Evaluate page (Issue 2159)

.github/workflows/cypress.yml
This will allow us to run the Cypress tests on PRs from 'external' contributors such as @dominikkawka. See #2969 for an example of a PR where these tests are not running as expected.
Also includes a change to replace the hard-coded record key for the Cypress Dashboard with a secret so that it cannot be abused by 3rd parties. A new key was generated for this and the old key should be revoked as soon as this PR has been merged.
Please hold on merging this PR until @ssilvert has added this new key to the secrets to avoid potential isssues running the tests.
=> Replace CI trigger for Cypress

public/resources/en/common.json, src/user/UserConsents.tsx
Close #1703
See #1703
1. You can enable the "Consent required" and "Display client on screen" in the settings page of the "security-admin-console-v2" client.
2. Then you can logout and login again.
3. You will find some consents in the User>Consent page.
4. After clicking the kebab menu, there will be an option list that includes "Revoke" option.
=> Changed button text from Delete to Revoke (Issue 1703)

.github/workflows/cypress.yml
Due to limitations in Github Actions we need to check in the record key for the Cypress Dashboard so the tests will run in parallel.
=> Check in Cypress Dashboard record key

index.html
Cleans up the CSS for `index.html` used for the initial page load. Removes unused classes and selectors. Also removes excess margin from the body to prevent obscuring the background color.
=> Clean up CSS for index.html

src/App.tsx, src/components/alert/Alerts.tsx, src/components/data-loader/DataLoader.test.tsx, src/components/help-enabler/HelpHeader.tsx, src/context/RealmsContext.tsx, src/context/access/Access.tsx, src/context/auth/AdminClient.tsx, src/context/realm-context/RealmContext.tsx, src/context/server-info/ServerInfoProvider.tsx, src/context/whoami/WhoAmI.tsx, src/groups/SubGroupsContext.tsx, src/realm-settings/user-profile/UserProfileContext.tsx, src/utils/createNamedContext.ts
Adds a `createNamedContext` utility function that creates a context with a specified [`displayName`](https://reactjs.org/docs/context.html#contextdisplayname). Also refactors all contexts to use this function to improve the debugging experience.
=> Add display names to contexts

src/clients/scopes/ClientScopes.tsx
This PR is to fix https://github.com/keycloak/keycloak-admin-ui/issues/3043
It seems that "sub component" was not rerendered when setKebabOpen was called. I move the useState in the sub component, I also empty selectedRows after delete because delete button was not disabled.
1. Go to client detail
2. Click on Dropdown and delete all button is displayed
=> Fix deleteAll in Client -> Client scopes (#3043)

public/resources/en/identity-providers-help.json, public/resources/en/identity-providers.json, src/identity-providers/add/DiscoverySettings.tsx
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/3050
Adds missing fields
1. Create OIDC or Keycloak OIDC identity provider
2. Verify `Use PKCE` and `PKCE Method` fields are saving properly
=> Add PKCE Enabled and PKCE Method to OIDC Identity Providers

src/App.tsx
Applies the [migrations](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v51) for React Router version 5.1, which are required for the upgrade to version 6. Since we were already mostly using the hooks API the changes we need to make are very small.
=> Apply migrations for React Router 5.1

public/resources/en/identity-providers.json, src/identity-providers/add/OIDCAuthentication.tsx
=> added translation for OIDC choices for Client authentication

src/App.tsx, src/authentication/routes/Authentication.ts, src/authentication/routes/Flow.ts, src/client-scopes/routes/ClientScope.ts, src/clients/routes/Clients.ts, src/clients/routes/DedicatedScopeDetails.ts, src/clients/routes/NewPermission.ts, src/clients/routes/Resource.ts, src/clients/routes/Scope.ts, src/dashboard/routes/Dashboard.ts, src/events/routes/Events.ts, src/groups/routes/Groups.tsx, src/realm-roles/routes/ClientRole.ts, src/realm-roles/routes/RealmRole.ts, src/realm-settings/routes/AddCondition.ts, src/realm-settings/routes/EditCondition.ts, src/realm-settings/routes/RealmSettings.ts, src/route-config.ts, src/user-federation/routes/UserFederationLdap.ts, src/user/routes/Users.ts
Update all routes that can be migrated to version 6 of React Router to use the new API. Keeps routes that cannot be migrated directly under the old API by means of a boolean option called `legacy`.
=> Use CompatRoute for routes that can be migrated

src/components/routable-tabs/RoutableTabs.tsx, src/groups/GroupAttributes.tsx, src/groups/GroupTable.tsx, src/groups/GroupsSection.tsx, src/groups/Members.tsx, src/groups/components/GroupTree.tsx
Replaces usages of the 'useLocation' hook from React Router with the new version compatible with version 6, as per the [official migration guide](https://github.com/remix-run/react-router/discussions/8753).
=> Use 'useLocation' hook from v6 API of React Router

src/realm-settings/EmailTab.tsx
Fixes #3097 
In `Realm Settings --> Email`, the port was not being saved properly if left blank.  The back end is expecting a `null` value to signify default port.
See #3097
=> Realm email doesn't default to port 25

src/realm-settings/NewClientPolicyForm.tsx
Closes #3138.
I replace usage of value from form by using name received from URL
1. Go to `Realm settings >> Client policies`.
2. Create a new policy.
3. Edit the new policy and empty name value.
I also change display of policy name in the header because it does not make any sense to check if `policyName` variable exists to display value from form
=> Do not display error when policy name is empty

src/components/multi-line-input/MultiLineInput.tsx
fixes comment: https://github.com/keycloak/keycloak-ui/issues/3004#issuecomment-1216072431
=> disable remove button only when it's the last field

.eslintrc.js, cypress/e2e/clients_test.spec.ts, cypress/support/util/AdminClient.ts, package-lock.json, package.json
Removes a Cypress test exclusion (`.only()`) and adds linting rules to enforce this in future instances.
=> Remove Cypress test exclusion

src/realm-settings/NewClientPolicyCondition.tsx, src/realm-settings/NewClientPolicyForm.tsx
see #1785
fixed #1785
Realm settings -> client policies -> policy details -> add condition
The policy details had a similar bug, which I've included a fix in this pr. `realm-settings:conditions` text was just 'Condition', so I've used `realm-settings-help` instead
=> Client policies > add condition: the initial help info of condition selector is not correct (Issue-1785) fix

src/user/UsersTabs.tsx
Closes #3180 
The problem is that field stay dirty after save, so I force refresh of user after an update. Maybe there is a better way to reset dirty field, for exemple display a spinner instead of form during save.
1. Update user firstname and save.
2. Switch to Attributes tab.
3. Do it once again if problem doesn't occurred.
=> Force refresh of user after save to avoid modal (#3180)

apps/admin-ui/src/components/group/GroupPickerDialog.tsx, apps/admin-ui/src/user/UserForm.tsx, apps/admin-ui/src/user/UserGroups.tsx, apps/admin-ui/src/user/UsersTabs.tsx, apps/admin-ui/src/user/routes/AddUser.ts
Fixes #3141 
- Adds groups with the same request as when first creating the user.
- Creates a `canBrowse` flag for the group selector dialog so that users who don't have rights to navigate the group tree won't crash the UI.  These users must search for groups instead.
See #3141
=> Allow adding permitted groups to new users with fine-grained permissions.

.github/dependabot.yml
Sets the Dependabot versioning strategy for NPM dependencies so that the package lockfile will also (hopefully) be updated. For more information see https://github.com/dependabot/dependabot-core/issues/5226#issuecomment-1179434437.
=> Set Dependabot versioning strategy for NPM

apps/admin-ui/src/PageHeader.tsx
The default mapper uses `picture` as field in the token so if it's there let's use that instead
I've used github as Idp:
=> use avatar picture when it exists

apps/admin-ui/public/resources/en/identity-providers.json, apps/admin-ui/public/resources/en/user-federation.json, apps/admin-ui/src/identity-providers/ManageOrderDialog.tsx, apps/admin-ui/src/user-federation/ManagePriorityDialog.tsx
Closes https://github.com/keycloak/keycloak-ui/issues/3216
1. Go to `User federation`.
2. Add provider.
3. Open Manage priorities dialog
4. Verify that the aria-label for the drag button is reading `Press space or enter to begin dragging, and use the arrow keys to navigate up or down. Press enter to confirm the drag, or any other key to cancel the drag operation.`
=> Added missing manageOrderItemAria

apps/admin-ui/public/resources/en/roles.json, apps/admin-ui/src/realm-roles/routes/RealmRoles.ts
Closes https://github.com/keycloak/keycloak-ui/issues/1827
1. Go to `Realm roles >> Select realm role eg. admin
2. Verify that the breadcrumb reads "Realm roles > Role details"
=> Fixed realm roles breadcrum #1827

apps/admin-ui/src/clients/scopes/AddScopeDialog.tsx
disable add button when nothing selected
fixes: #2042
=> disabled add button when no items are selcted

apps/admin-ui/src/user/UserForm.tsx
Fixes #1975 
I think I have come up with a reasonable compromise.  I found that if `Edit username` is off and you go ahead and let the user try to change it, nothing bad will happen.  Other changes in the submission will go through, but it won't change the user name.
So in the rare case where a user doesn't have `view-realm` access, we can just allow the username field to be editable.  That way, the field is still properly enabled/disabled in most instances but doesn't do any harm if we can't determine mutability.  And then we don't need any weird changes on the back end.
See #1975
=> Allow edit username if we can't determine mutability.

apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx, keycloak-theme/src/main/java/org/keycloak/admin/ui/rest/RoleMappingResource.java
fixes: #3266
When you start searching on the third page of a paged result you want to reset the page to 0, as there might not be 3 pages of search results.
=> reset first param on client when start searching

.github/workflows/cypress.yml
Sometimes we need to run the tests on release branches manually, so let's make it possible to manually run this workflow.
=> Allow triggering Cypress workflow by dispatch

.github/workflows/cypress.yml
Continuation of #3290. Allows a repo and branch to be specified for the Keycloak server, which is useful for pairing the correct release branch.
=> Add inputs to specify Keycloak repo and branch

apps/admin-ui/cypress/e2e/clients_test.spec.ts, apps/admin-ui/package.json, apps/admin-ui/src/clients/keys/GenerateKeyDialog.tsx, apps/admin-ui/src/clients/keys/ImportKeyDialog.tsx, apps/admin-ui/src/components/dynamic/FileComponent.tsx, apps/admin-ui/src/components/json-file-upload/FileUploadForm.tsx, apps/admin-ui/src/components/json-file-upload/patternfly/FileUpload.tsx, apps/admin-ui/src/components/json-file-upload/patternfly/FileUploadField.tsx, apps/admin-ui/src/components/json-file-upload/patternfly/fileUtils.ts, apps/admin-ui/vite.config.ts, package-lock.json
Optimize dependencies using Rollup instead of esbuild. This prevents issues where a dependency can be duplicated and create errors at runtime.
=> Optimize dependencies with Rollup

apps/admin-ui/src/components/dynamic/TextComponent.tsx, apps/admin-ui/src/components/dynamic/components.ts
- fix opening the execution config modal
- added component for type TEXT
=> added text component for `ProviderConfigProperty.TEXT_TYPE`

.github/workflows/cypress.yml
Added a nightly run of Cypress to test the nightly built artefacts rather than building it within the GA workflow. This serves two purposes:
a) A nightly check of KC + admin-ui even if there are no pushes to this repo
b) Check KC as it will be built by the release process
=> Add nightly run using nightly builds

apps/admin-ui/package.json
Since recent changes in Vite the dev server is no longer available to Cypress tests during development unles the `--host` flag is passed to it.
=> Always pass in `--host` for Vite dev server

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .gitignore, apps/admin-ui/package.json, keycloak-theme/pom.xml, libs/keycloak-js/package.json, package-lock.json, package.json
Adds [Wireit](https://github.com/google/wireit) to automatically build Keycloak JS whenever needed. For example, when building the Admin UI you want to make sure the latest version of Keycloak JS has been built in the workspace.
The configuration set up here for Wireit allows us to also cache the Keycloak JS build so it will only run once unless changes are made to Keycloak JS itself.
=> Add Wireit to automatically build Keycloak JS

.github/dependabot.yml
We can't upgrade React Router just yet, so let's hold back Dependabot from updating major versions.
=> Prevent Dependabot from updating react-router

apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
Closes #3252 
When creating a Keycloak OpenID Connect Identity Provider, the providerId is set to 'oidc' instead of 'keycloak-oidc', resulting in unexpected behavior.
1. Master Realm > Identity Providers
2. Select 'Keycloak OpenID Connect'. If there are already IdPs created: Click 'Add provider' dropdown, select 'Keycloak OpenID Connect'
4. Confirm that the header says 'Add Keycloak OpenID Connect provider' instead of 'Add OpenID Connect provider'
5. Fill out form, save.
6. Go back to Master Realm > Identity Providers
7. Confirm the "Provider details" for the provider created says "Keycloak-oidc" instead of "oidc"
=> Fix Keycloak OpenID Connect Identity provider creation

apps/admin-ui/cypress/e2e/events_test.spec.ts, apps/admin-ui/cypress/e2e/realm_test.spec.ts, apps/admin-ui/cypress/e2e/sessions_test.spec.ts, apps/admin-ui/cypress/e2e/user_fed_kerberos_test.spec.ts, apps/admin-ui/cypress/e2e/user_fed_ldap_test.spec.ts, apps/admin-ui/cypress/e2e/users_test.spec.ts, apps/admin-ui/cypress/support/pages/CommonElements.ts, apps/admin-ui/cypress/support/pages/admin_console/Masthead.ts, apps/admin-ui/cypress/support/pages/admin_console/components/PageObject.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesMappersTab.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/realm_settings/tabs/realmsettings_events_subtabs/UserEventsSettingsTab.ts
Set default value of closeNotification to true, so it closes notifications on all the checks, to avoid having too many notifications due to the bug that they sometimes don't disappear
=> Add default value true to closeNotification

apps/admin-ui/README.md
I was reading through the Keycloak UI documentation and I was getting a 404 on the link to the theme readme.
What was done in this PR? Updated path to theme readme to reference correct file.
Why it was done? Users were getting a 404 trying to navigate to doc on theming.
1. Go to the Preview of this PR or https://github.com/PinPinIre/keycloak-ui/tree/patch-1/apps/admin-ui
2. Search for the #building-as-a-keycloak-theme section
3. Click on the `Keycloak theme documentation` link
N/A
=> Fix path to keycloak theme readme

apps/admin-ui/src/context/auth/AdminClient.tsx
Fix https://github.com/keycloak/keycloak-ui/issues/3374 
Use the "correct" URLs for initialization.
Start keycloak with --hostname and a different --hostname-admin.
Try to access the admin-konsole.
Either CORS Issues from calling --hostname based URLs from within the --hostname-admin or the calls go to --hostname without error.
The --hostname-admin must be used for all ajax calls from within the admin-console.
Work in progress. Missing tests, but want to verify the direction this is heading.
=> Adjusted initialization of admin-client-ui with different urls in hostname and hostname-admin

keycloak-theme/pom.xml
resolves #3364 
This PR adds the possibility to import custom styles when extending from the theme. The style import would would similar to the way it works in the account theme.
When copying over the index.html to the index.ftl file the necessary code for importing custom styles is inserted via replacing the end tag of the head.  
1. Build and package the theme with `mvn package`.
2. Check the index.ftl file in the target folder.
None
=> Add possibility to import custom styles by extending the theme

keycloak-theme/pom.xml
Cleanup around release profile, and wrapping Nexus plugin in a profile to allow releasing to non-Nexus repositories using `-DaltDeploymentRepository`.
Please review, but don't merge as this needs to be merged together with PRs to the release process.
=> Refactor release profiles

apps/admin-ui/index.html, keycloak-theme/pom.xml
Add a `<base>` element for improved security around relative URLs. Closes #3442.
=> Add a `<base>` element for relative URLs

apps/admin-ui/src/context/auth/AdminClient.tsx
Changes the config for Keycloak JS in when running in production so it uses [this endpoint](https://github.com/keycloak/keycloak/blob/fb24c86a3bf4dcfd661e11288686afe8a88f10ef/services/src/main/java/org/keycloak/services/resources/admin/AdminConsole.java#L180-L189) instead. This is the [same behavior](https://github.com/keycloak/keycloak/blob/fb24c86a3bf4dcfd661e11288686afe8a88f10ef/themes/src/main/resources/theme/base/admin/resources/js/app.js#L14) as the old Admin Console.
This might address issues where the Admin UI uses an incorrect URL to make requests when Keycloak is running behind a reverse proxy that splits the OpenID Connect endpoints from the rest of Keycloak.
=> Use Keycloak config endpoint in production

apps/admin-ui/src/components/realm-selector/RealmSelector.tsx, apps/admin-ui/src/context/RealmsContext.tsx
this will not totally fix the issue but make the console at least usable
fixes: #3381
=> only load realms when dropdown is opened

apps/admin-ui/src/components/role-mapping/RoleMapping.tsx
Added group id to assigned-roles data table key to reload when navigating groups
Closes #3413
Added group id to assigned-roles data table to reload role mappins when navigating the groups
1. Go to a group and assign roles from a client
2. Go to a different page
3. Go back to the group and see that role mappins show the client roles assigned
=> Added group id to assigned-roles data table key to reload when navigating groups

.github/workflows/cypress.yml, apps/admin-ui/cypress.config.mjs
Allows the Cypress tests to run again by disabling parallelization. This is currently broken due to https://github.com/cypress-io/github-action/issues/602.
=> Stop running Cypress tests in parallel

.github/workflows/cypress.yml
Reverts some of the changes #3485, allowing the Cypress tests to run in parallel again.
=> Run Cypress tests in parallel again

apps/admin-ui/public/resources/en/dashboard.json
Simple fix for typo - was always jumping to my eyes when selecting a realm  
English: `mange` instead of `manage`
Only a very brief typo fix
Open a realm (other than "_master_") and see the text shown in the main screen
None
=> Fix typo in dashboard.json

apps/admin-ui/cypress.config.mjs
This should improve the amount of tests passing.
=> Re-enable test retries for Cypress

apps/admin-ui/src/clients/routes/NewPermission.ts
Removes an optional parameter from the new permission route. Optional parameters are not supported by React Router v6, so this is causing errors at runtime.
=> Remove optional param from new permission route

apps/admin-ui/src/user/user-credentials/CredentialsResetActionMultiSelect.tsx
Fixes #3450 
Reset actions for credential reset email were hard-coded to the values in the `RequiredActionAlias` enum.  Now it gets the enabled required actions from the server.
1. Go to `Authentication --> Required actions` and enable some extra required actions.
2. Go to `User --> User Details --> Credentials --> Credential Reset`
3. Verify that the newly-enabled required actions show up in the dropdown.
=> Reset actions should not be hard-coded.

apps/admin-ui/src/realm-settings/EmailTab.tsx
Closes https://github.com/keycloak/keycloak-ui/issues/1775
Note: I also searched the codebase for all the places where we have implemented passwords, and they all seem to use the PasswordInput component.
1. Go to `Realm settings > Email` and enable `Authentication`
2. Verify that it's now possible to view the password.
=> Added view password - issue-1775

.github/workflows/main.yml, apps/account-ui/vite.config.ts, apps/admin-ui/vite.config.ts
Allows the CI to run the linting and build tasks for the Account UI to ensure no regressions are introduced by accident.
=> Run CI jobs for the Account UI

apps/admin-ui/public/resources/en/common.json, apps/admin-ui/public/resources/en/roles.json
Rename "Filter by roles" to "Filter by realm roles" 
1. Go to `Clients >> Client details >> Create policy`.
2. Select `Add roles`.
3. Verify that the placeholder in the search box is now reading `Filter by realm roles`.
=> Text remate to 'Filter by realm roles'

apps/admin-ui/src/realm-settings/user-profile/attribute/AttributePermission.tsx
When using the experimental feature declarative user profile it was not possible to allow only the admin to view/edit an attribute. When admin was selected, user was always included.
Changed update handling of attribute permission checkboxes.
1. Enable declarative user profile feature
2. Set "User Profile Enabled" to "on"
3. Go "User Profile" and edit any attribute
4. Select "admin" (user should no longer be selected automatically)
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] axe report has been run and resulting a11y issues have been resolved
=> Allow user and admin attribute permissions to be independantly set

apps/admin-ui/cypress/e2e/authentication_policies.spec.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/authentication/OTPPolicies.ts, apps/admin-ui/public/resources/en/authentication.json, apps/admin-ui/src/authentication/policies/OtpPolicy.tsx
Adds some labels for the supported applications of the 'OTP Policy' tab. These changes were added upstream under https://github.com/keycloak/keycloak/pull/14800. This should allow the test suite to pass again.
Also changes the text input to a chip group, which can show this readonly listed value a bit better:
=> Add labels for supported applications to 'OTP Policy'

apps/admin-ui/cypress/e2e/authentication_policies.spec.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/authentication/OTPPolicies.ts, apps/admin-ui/public/resources/en/authentication-help.json, apps/admin-ui/public/resources/en/authentication.json, apps/admin-ui/public/resources/ja/authentication-help.json, apps/admin-ui/src/authentication/policies/OtpPolicy.tsx, apps/admin-ui/src/authentication/policies/otp-policy.css
Sorts the labels used for the 'Supported Applications' field under the OTP Policy. This ensures the tests for this field do not become unstable, as the API might return these labels in any order.
Also renames 'supported actions' to 'supported applications', which seems to have been a typo.
=> Ensure list of supported applications is stable

apps/admin-ui/src/components/alert/AlertPanel.tsx, apps/admin-ui/src/components/alert/Alerts.tsx
this fixes the issue with the notification timeout being cumulative
see: https://github.com/patternfly/patternfly-react/issues/8064
=> when using timeout we don't need onTimeout

apps/account-ui/src/react-i18next.d.ts
Changes the type definitions for `i18next` to the correct module namespace. This was changed in the recent major version, but this migration was not yet applied.
=> Use correct namespace for i18n types

apps/admin-ui/package.json, package-lock.json
Removes the hard dependency on `babel-loader`. This dependency is required for the custom WebPack loader we are using for the Cypress tests. However it was accidentally upgraded to an incompatible version by Dependabot.
Since it's a peer dependency it will be automatically installed by NPM, so there is no need to have it in our package file explicitly.
=> Remove hard dependency on `babel-loader`

apps/admin-ui/src/realm-settings/LoginTab.tsx
When both switches are on, you get this result
Closes #3588
=> partial fix for issue 3588

apps/admin-ui/package.json, apps/admin-ui/src/sessions/RevocationModal.tsx, package-lock.json
Adds an alias to v7  of `react-hook-form` to the package and refactors the revocation modal to use it.
=> Use `react-hook-form` v7 for session revocation

apps/admin-ui/cypress/e2e/events_test.spec.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/realm_settings/tabs/realmsettings_events_subtabs/AdminEventsSettingsTab.ts
Add interceptors for API calls related to the Admin Events, then wait for them to finish before continuing. This should resolve intermittently failing tests.
Closes #3653
=> Wait for network requests to finish in events test

apps/admin-ui/package.json
Adds the `server:import-client` script to Wireit configuration, as it depends on the Admin Client. This ensures the Admin Client is built before running the script, preventing import errors/
=> Add `server:import-client` script to Wireit configuration

apps/admin-ui/cypress/support/pages/admin_console/manage/users/user_details/tabs/IdentityProviderLinksTab.ts, apps/admin-ui/src/user/UserIdPModal.tsx, apps/admin-ui/src/user/UserIdentityProviderLinks.tsx, apps/admin-ui/src/user/UsersTabs.tsx
Refactors the user IDP modal to use v7 of `react-form-hook`, and cleans up the code a little.
=> Use `react-form-hook` v7 for user IDP modal

apps/admin-ui/src/util.ts
This feature is now also supported by the latest ESR release of Firefox. Closes #2883.
=> Use `Object.hasOwn()` instead of `Object.prototype.hasOwnProperty()`

apps/admin-ui/src/authentication/BindFlowDialog.tsx
Refactors the bind flow dialog to use v7 of `react-form-hook`, and cleans up the code a little.
=> Use `react-form-hook` v7 for bind flow dialog

apps/admin-ui/src/identity-providers/routes/IdentityProvider.ts
Fixes #3725 
See steps in #3725 
User is required to have at least `view-identity-providers` and `query-clients` roles.
=> Allow view IDP with view-identity-providers role.

apps/admin-ui/src/groups/GroupsSection.tsx, apps/admin-ui/src/identity-providers/add/DetailSettings.tsx, apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx, apps/admin-ui/src/user/UsersSection.tsx
Fixes https://github.com/keycloak/keycloak-ui/issues/3741
Permissions tabs should not be shown if `ADMIN_FINE_GRAINED_AUTHZ` is disabled.
1. Start Keycloak with `--features=preview` flag.
2. Permissions tab should be visible in Client Details, Group Details, Realm Role Details, User main screen, and IDP Details.
3. Start Keycloak without `--features=preview` flag.
4. Permissions tabs should no longer be visible.
=> Hide permissions tabs when ADMIN_FINE_GRAINED_AUTHZ is disabled.

apps/admin-ui/src/authentication/DuplicateFlowModal.tsx, apps/admin-ui/src/authentication/EditFlowModal.tsx, apps/admin-ui/src/authentication/form/CreateFlow.tsx, apps/admin-ui/src/authentication/form/FlowType.tsx, apps/admin-ui/src/authentication/form/NameDescription.tsx
Refactors the flow form to use v7 of `react-form-hook`, and cleans up the code a little.
=> Use `react-form-hook` v7 for flow form

apps/admin-ui/src/authentication/policies/OtpPolicy.tsx, libs/keycloak-admin-client/src/defs/realmRepresentation.ts
Refactors the OTP policy form to use v7 of `react-hook-form`, and cleans up the code a little.
=> Use `react-hook-form` v7 for OTP policy form

.github/workflows/cypress.yml
Upload the Keycloak server logs when running the Cypress tests. This will allow us to diagnose issues when API calls fail unexpectedly.
=> Upload Keycloak server logs when running Cypress

apps/admin-ui/src/events/EventsSection.tsx
Refactors the events section form to use v7 of `react-hook-form`, and cleans up the code a little.
=> Use `react-hook-form` v7 for events section

libs/keycloak-admin-client/src/resources/realms.ts
t looks like the types here are incorrect. The Date object is invalid to query Keycloak api and throws an error: Invalid value for 'Date(From)', expected format is yyyy-MM-dd" when used.
=> Use `string` type for dates for `findEvents` method

apps/admin-ui/src/authentication/__tests__/ExecutionList.test.ts, apps/admin-ui/src/authentication/execution-model.ts
=> fixes parsing the list into sub-lists

.github/workflows/cypress.yml
This will ensure the logs of the Keycloak server are uploaded, even if the tests job has failed.
=> Upload server logs even when tests fail

apps/admin-ui/src/util.ts
Make `convertAttributeNameToForm` type-safe, so we can improve type checking on forms in the future.
=> Make `convertAttributeNameToForm` type-safe

.github/workflows/cypress.yml, .github/workflows/main.yml
Sets up the concurrency for CI so that jobs on branches like `main` will always run to completion (not getting cancelled by new merges). This change will still cancel previous jobs when pushing new commits on PRs, cutting down our GitHub Actions & Cypress Dashboard runtime.
=> Only cancel CI jobs on pushes for PRs

.github/workflows/cypress.yml, .github/workflows/main.yml
Adds the name of the workflows (`main`, and `cypress`) to the concurrency group. This should prevent these jobs from cancelling each other out.
=> Add worflow name to concurrency group

apps/admin-ui/src/components/alert/Alerts.tsx, apps/admin-ui/src/context/RealmsContext.tsx, apps/admin-ui/src/context/auth/AdminClient.tsx, libs/keycloak-admin-client/README.md, libs/keycloak-admin-client/package.json, libs/keycloak-admin-client/src/client.ts, libs/keycloak-admin-client/src/index.ts, libs/keycloak-admin-client/src/resources/agent.ts, libs/keycloak-admin-client/src/resources/users.ts, libs/keycloak-admin-client/src/utils/auth.ts, libs/keycloak-admin-client/src/utils/fetchWithError.ts, package-lock.json
Replaces Axios in the Admin Client with the Fetch API and a thin error handling wrapper. This resolves the issues upgrading Axios (see #3877), and eliminates a dependency in the process.
=> Replace Axios with the Fetch API

.github/workflows/main.yml
Adds a job to the CI to automatically merge Dependabot PRs when the CI completes successfully.
=> Automatically merge Dependabot PRs when CI passes

apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts, apps/admin-ui/src/components/dynamic/BooleanComponent.tsx
apparently when the property is not there it means `false`
fixes: #3819
=> Don't use a default value in `BooleanComponent`

apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts, apps/admin-ui/cypress/e2e/clients_test.spec.ts, apps/admin-ui/cypress/e2e/realm_roles_test.spec.ts, apps/admin-ui/cypress/e2e/realm_user_registration.spec.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/groups/group_details/GroupDetailPage.ts, apps/admin-ui/public/resources/en/clients.json
Closes #985 
1. Go to `Users > Role mapping > Select role > Click on Unassign`.
2. Verify that the world `mapping(s)` was replaced with the word `role(s)`
=> Replaced word `mapping(s)` with word `role(s)` - issue 985

apps/admin-ui/cypress/e2e/realm_settings_events_test.spec.ts
Adds an arbitrary wait to the 'enable user events'  test. It looks like a re-render is causing the element reference to be lost, so hopefully this will allow it to settle.
Still need a better fix, as awaits are bad practice. For now this (hopefully) allows us to merge some PRs.
=> Add wait to 'enable user events' test

.github/workflows/main.yml
Should hopefully keep the Dependabot auto-merge job from failing.
=> Allow extended write permissions for Dependabot auto-merge

apps/admin-ui/cypress/e2e/client_scopes_test.spec.ts, apps/admin-ui/cypress/support/pages/admin_console/manage/client_scopes/CreateClientScopePage.ts, apps/admin-ui/src/client-scopes/details/ScopeForm.tsx, apps/admin-ui/src/client-scopes/form/ClientScopeForm.tsx, apps/admin-ui/src/components/client-scope/ClientScopeTypes.tsx
Refactors the client scope form to use v7 of `react-hook-form`, and cleans up the code a little.
=> Use `react-hook-form` v7 for client scope form

apps/admin-ui/src/clients/authorization/SearchDropdown.tsx
Refactors the search dropdown form to use v7 of `react-hook-form`, and cleans up the code a little.
=> Use `react-hook-form` v7 for search dropdown form

apps/admin-ui/src/clients/authorization/ScopeDetails.tsx
Refactors the add scope details form to use v7 of `react-hook-form`, and cleans up the code a little.
=> Use `react-hook-form` v7 for scope details form

apps/admin-ui/src/clients/add/AccessSettings.tsx, apps/admin-ui/src/clients/add/LogoutPanel.tsx, apps/admin-ui/src/clients/advanced/ApplicationUrls.tsx, apps/admin-ui/src/clients/advanced/FineGrainSamlEndpointConfig.tsx, apps/admin-ui/src/clients/authorization/ResourceDetails.tsx, apps/admin-ui/src/clients/keys/Keys.tsx, apps/admin-ui/src/identity-providers/add/DescriptorSettings.tsx, apps/admin-ui/src/identity-providers/add/DiscoverySettings.tsx, apps/admin-ui/src/identity-providers/component/DiscoveryEndpointField.tsx, apps/admin-ui/src/identity-providers/component/ExtendedFieldsForm.tsx, apps/admin-ui/src/realm-settings/GeneralTab.tsx, apps/admin-ui/src/user-federation/ldap/LdapSettingsConnection.tsx
Closes #1542 
Reviewed all forms (KeycloakTextInput) and identified a couple of possibly missing `url` types.
=> Added missing`url` types to KeycloakTextInput form fields - #1542

.github/workflows/cypress.yml
Sometimes the version of Google Chrome can be different between Github Action runners. This causes the Cypress tests to fail. This additional step ensures that we're always running the latest version of Google Chrome.
=> Download latest version of Chrome for Cypress tests

apps/admin-ui/src/identity-providers/add/DetailSettings.tsx, apps/admin-ui/src/identity-providers/routes/IdentityProvider.ts
Replaces the `KeycloakTabs` used in the identity provider details screen with routable tabs. This is part of the effort to upgrade React Router to the latest version.
=> Use routable tabs for identity provider details

.github/workflows/cypress.yml
This file no longer exists in the main project and is causing test run failures.
=> Stop copying `settings.xml` for Maven configuration

apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts, apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/AddMapperPage.ts, apps/admin-ui/src/identity-providers/add/AddMapper.tsx
Closes #1355 . Also added a test.
1. Go to `Identity providers` and create a new OIDC provider.
2. Select created provider and go to the `Mappers` tab and click on the `Cancel` button.
3. Verify that clicking on the `Cancel` button is taking the user to the Mappers tab.
=> Fixed navigation to mappers tab in identity providers #1355

apps/admin-ui/src/identity-providers/IdentityProvidersSection.tsx
=> Identity provider link is not displayed when display name is empty

apps/admin-ui/src/authentication/AuthenticationSection.tsx
Converts the routable tabs of user authentication page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of authentication page

apps/admin-ui/src/dashboard/Dashboard.tsx
Converts the routable tabs of user dashboard page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of dashboard page

apps/admin-ui/src/clients/ClientsSection.tsx
Converts the routable tabs of user clients page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of clients page

apps/admin-ui/src/realm-settings/RealmSettingsTabs.tsx
Converts the routable tabs of the realm settings page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the realm settings page

apps/admin-ui/src/user-federation/CreateUserFederationLdapSettings.tsx, apps/admin-ui/src/user-federation/UserFederationLdapForm.tsx, apps/admin-ui/src/user-federation/UserFederationLdapSettings.tsx, apps/admin-ui/src/user-federation/routes/NewLdapUserFederation.ts, apps/admin-ui/src/user-federation/routes/UserFederationLdap.ts
Converts the routable tabs of the user federation LDAP settings page to use the latest version of React Router. Also splits out the edit and create pages into separate components to reduce complexity.
Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the user federation LDAP settings page

apps/admin-ui/src/realm-settings/keys/KeysTab.tsx
Converts the routable tabs of the realm settings keys page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the realm settings keys page

apps/admin-ui/src/user/UsersSection.tsx
Converts the routable tabs of the users page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the users page

apps/admin-ui/src/clients/scopes/DedicatedScopes.tsx
Converts the routable tabs of the dedicated scope page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the dedicated scope page

apps/keycloak-server/package.json
Adds a convenient  `clear-data` script to the Keycloak server. This removes any stored information from a previously downloaded Keycloak server, allowing you to start with a clean database.
=> Add `clear-data` script to Keycloak server

apps/admin-ui/src/clients/ClientDetails.tsx
Converts the routable tabs of the client page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the client page

apps/admin-ui/src/events/EventsSection.tsx
Converts the routable tabs of the events page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the events page

apps/admin-ui/src/realm-settings/user-profile/UserProfileTab.tsx
Converts the routable tabs of the user profile page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the user profile page

apps/admin-ui/src/identity-providers/add/DetailSettings.tsx
Converts the routable tabs of the identity provider page to use the latest version of React Router. Based off the work in #4113, but split out to reduce review burden.
=> Use React Router v6 for the routable tabs of the identity provider page

apps/admin-ui/src/client-scopes/details/MappingDetails.tsx
Refactors client scope mapping to use the React Router v6 API. Also replaces a dynamically built route path with a route function.
=> Refactor client scope mapping to React Router v6

apps/admin-ui/src/identity-providers/add/AddOpenIdConnect.tsx
Refactors the OpenID Connect identity provider code to use the new React Router v6 API.
=> Refactor OpenID Connect IDP to use React Router v6

apps/admin-ui/src/realm-settings/keys/KeysProvidersTab.tsx
Refactor the realm keys providers to the React Router v6 API. Also replaces dynamically built links with route functions.
=> Refactor realm keys providers to React Router v6

apps/admin-ui/cypress/e2e/clients_test.spec.ts, apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/ClientRolesTab.ts, apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_roles/CreateRealmRolePage.ts, apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Fixes a bug introduced by #1838 where the realm & client roles tab would create an excessive amount of requests and subsequently re-renders. This was caused by providing the current URL as a dependency to `useFetch()` which would trigger a request every time the tab was changed, even when such a fetch was not needed.
This also removes a bunch of request intercepts from the Cypress tests, which were added to stabilize the tests. Presumably this instability was actually caused by the changes made in #1838 as well.
=> Reduce excessive re-renders for realm & client roles tab

apps/admin-ui/src/clients/routes/ClientRole.ts, apps/admin-ui/src/realm-roles/RealmRoleTabs.tsx
Converts the realm and client roles code to use React Router v6. Also replaces dynamically built paths with route functions.
=> Refactor realms & client roles to React Router v6

libs/keycloak-admin-client/src/utils/auth.ts, libs/keycloak-admin-client/test/auth.spec.ts
Since the release of keycloak 20.0.0 it is required to specify the scope when authenticating. This is easily discovered when calling the /userinfo endpoint in keycloak with an auth token that is created without the scope.
https://www.keycloak.org/docs/latest/upgrading/#userinfo-endpoint-changes
I have added a default scope as "openid" to solve above problem. 
I have also added an optional parameter for users who wish to set their own scope.
1. get an auth token by calling
```
const keycloakAdmin = new KeycloakAdmin({<some settings>})
keycloakAdmin.auth(authInfo)
```
2. Use the accessToken created above and call the `protocol/openid-connect/userinfo` endpoint.3. 
3. Before this PR it results in a 403.
- [N/A] User-visible strings are using the react-i18next framework (useTranslation)
- …
=> add openid as default scope and add option to set custom scopes

apps/admin-ui/src/realm-settings/NewAttributeSettings.tsx, apps/admin-ui/src/realm-settings/user-profile/AttributesTab.tsx
When groups are used for the user profile, but they are not passed when updating, then we get an error from the server.
This PR addresses this.
=> small fix to also add the group when it's used

apps/admin-ui/src/user/UsersSection.tsx
Fixes https://github.com/keycloak/keycloak-ui/issues/3965
Relies on recent back end change. See https://github.com/keycloak/keycloak/pull/15967
See https://github.com/keycloak/keycloak-ui/issues/3965
Simpler way than what is in the issue is to grant permissions with a user policy instead of a group policy.
=> Allow add/remove user with only query-users role.

.github/dependabot.yml, apps/admin-ui/package.json, apps/admin-ui/src/authentication/components/FlowDiagram.tsx, apps/admin-ui/src/authentication/components/diagram/ButtonEdge.tsx, apps/admin-ui/src/authentication/components/diagram/ConditionalNode.tsx, apps/admin-ui/src/authentication/components/diagram/SubFlowNode.tsx, apps/admin-ui/src/authentication/components/diagram/auto-layout.ts, package-lock.json
Upgrades `reactflow` (formerly known as `react-flow-renderer`) to version 11. See the [migration guide](https://reactflow.dev/docs/guides/migrate-to-v11/) for more information.
=> Upgrade `reactflow` to version 11

apps/admin-ui/cypress/support/pages/admin-ui/manage/clients/client_details/DedicatedScopesMappersTab.ts
Experiment to fix flaky predefined mapper test.  This test is shown to be flaky over 50% of the time on main.  It's by far the flakiest test we have.
Suspect that the `force:true` flag may sometimes keep Cypress from waiting until the modal appears.
Run many times in CI to see if it is stable.
=> Experiment to fix flaky predefined mapper test.

apps/admin-ui/cypress/WRITING_TESTS.md, apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts, apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts, apps/admin-ui/public/resources/en/identity-providers-help.json, apps/admin-ui/public/resources/en/identity-providers.json, apps/admin-ui/public/resources/ja/identity-providers-help.json, apps/admin-ui/public/resources/ja/identity-providers.json, apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx
keycloak/keycloak#14021
Closes #4144 
No response
I changed this one along with WRITING_TEST.md.
=> Client assertion signature configuration of identity broker is missing on new security admin console

.github/dependabot.yml
Forgot to remove this when upgrading the `react-form-hook` dependency. Since it is now up-to-date we can re-enable Dependabot for it.
=> Re-enable Dependabot updates for `react-form-hook`

apps/account-ui/package.json, apps/admin-ui/package.json, package-lock.json
Since the [release](https://github.com/npm/cli/releases/tag/v9.0.0) of NPM v9 the latest version of the lockfile (v3) has become the default. This change regenerates the lockfile from scratch in this new format, and in the process bumps all transitive dependencies to their latest versions.
This change is backwards compatible with version 8 of NPM.
=> Regenerate lockfile in v3 format

apps/admin-ui/src/realm-settings/PartialImport.tsx
Fixes #3824 
Group label was missing from type column in partial import result modal.
See #3824
=> Fix group type label in partial import.

.eslintrc.js
Introduces the [`react/no-unstable-nested-components`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md) linting rule. This will warn when nested components are used which causes accidental component re-mounts.
I have created #4293 to fix these in the future.
=> Introduce linting rule warn about nested components

apps/admin-ui/public/resources/en/authentication-help.json, apps/admin-ui/public/resources/en/authentication.json, apps/admin-ui/public/resources/en/common.json, apps/admin-ui/src/authentication/policies/CibaPolicy.tsx, apps/admin-ui/src/authentication/policies/Policies.tsx
Closes #4286.
Adds the "CIBA Policies" tab to authentication policies (Authentication :arrow_right: Policies :arrow_right: CIBA Policy). The form is different than the original in several ways:
- The "Backchannel Token Delivery Mode" is no longer marked as required, as there is always a value selected.
- Validation messages have been added for minimal and maximum values for the "Expires In" and "Interval" fields.
- The "Expires In" and "Interval" fields are now required (the original allowed saving empty values, which would error out when saving).
- ~~The "Authentication Requested User Hint" field has been omitted, as there is only one value that can be selected at all times.~~ This has been restored with a slightly different design.
=> Add CIBA policy tab to authentication policies

apps/admin-ui/cypress/component/MultiLineInput.cy.tsx, apps/admin-ui/src/components/multi-line-input/MultiLineInput.tsx
created component test for the multi line edit see https://github.com/keycloak/keycloak-ui/issues/4273
=> added component test

apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
Adding aria-label to MultivaluedStringComponent to get rid of error in DevTools Console. Was moved out of PR https://github.com/keycloak/keycloak-ui/pull/4306 to separate PR.
=> Added aria-label to MultivaluedStringComponent

apps/admin-ui/src/components/dynamic/MultivaluedStringComponent.tsx
Fixes #4273
Added missing stringify for MultiLineInput inside MultiValuedStringComponent to fix the problem of missing values in a condition with property of type MULTIVALUED_STRING_TYPE.
=> Added stringify in MultiValuedStringComponent

apps/admin-ui/package.json
CI on main is failing as some Cypress component tests have been introduced that require the Admin Client to be built beforehand. This PR adds a WireIt config to ensure this happens.
=> Build Admin Client before running Cypress component tests

apps/admin-ui/src/user/EditUser.tsx
This enhancement adds support for the use case described in https://github.com/keycloak/keycloak/discussions/16769.  They want to have administrators that can only see Users but not Groups.
Fixes #4321 
Follow steps I outlined in [this comment](https://github.com/keycloak/keycloak/discussions/16769#discussioncomment-4856011).
=> Don't show Groups tab if user does not have query-groups role.

apps/admin-ui/src/components/group/GroupPath.tsx, apps/admin-ui/src/components/group/GroupPickerDialog.tsx, apps/admin-ui/src/components/group/group-picker-dialog.css
fixes: #4121
this creates more room for the path:
and when there is still not enough room it will be cut off in the end with have tooltip:
=> made dialog more wide when searching and used css to cut off the end when needed

apps/admin-ui/cypress/support/pages/admin-ui/SidebarPage.ts, apps/admin-ui/src/components/realm-selector/RealmSelector.tsx
Cleans up the realm selector code a bit which will hopefully prevent failures in the Cypress test suite. Some components have been un-nested to prevent re-renders that might affect the tests.
=> Clean up realm selector code

apps/admin-ui/package.json, apps/admin-ui/src/components/help-enabler/HelpHeader.tsx, apps/admin-ui/src/components/table-toolbar/KeycloakDataTable.tsx, apps/admin-ui/src/utils/useStorageItem.ts, apps/admin-ui/src/utils/useStoredState.ts, package-lock.json
Introduces a `useStoredState()` hook to replace [`react-use-localstorage`](https://github.com/dance2die/react-use-localstorage), which has some bugs and is largely unmaintained. This hook also adds a higher level of serialization so that primitive values can be stored.
Wrote this as I needed something more high level for some other code I want to introduce, and the old library got in the way. Figured I might as well fix this up a little.
=> Introduce `useStoredState()` hook

apps/admin-ui/src/clients/ClientsSection.tsx, apps/admin-ui/src/components/external-link/FormattedLink.tsx
Ran into this bug when working on the clients overview for an unrelated reason. I noticed that the 'Home URL' links in the table on the clients overview were getting malformed (and also the link target).
Before:
After:
=> Fix 'Home URL' link in clients overview

apps/account-ui/package.json, apps/admin-ui/package.json, libs/ui-shared/package.json, package-lock.json
Dependabot is ignoring this version, so hopefully updating this will re-start it.
=> Update React Hook Form to latest version

apps/admin-ui/cypress.config.mjs, apps/admin-ui/package.json, package-lock.json
Removes the WebPack pre-proccessor from Cypress config, which is no longer needed now that we do type checking on CI.
=> Remove WebPack pre-proccessor from Cypress config

apps/admin-ui/src/components/download-dialog/DownloadDialog.tsx
After a review from Kun it seemed best to move the helptext into the combobox so users can see it before they select.
=> moved help text into dropdown

apps/account-ui/src/main.tsx
Moves the Account UI to the new root API for React 18 (see [upgrade guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis)).
=> Use new root API to render Account UI

apps/admin-ui/src/groups/GroupTable.tsx, apps/admin-ui/src/groups/GroupsSection.tsx, apps/admin-ui/src/groups/components/GroupTree.tsx
Fixes #3978 
If the user has only query-groups role, then the link for groups in the lefthand tree navigation is still active. If you click on it you will get an error.
The group names should not be rendered as a link unless the user has the view-users role. This is correct in the list view but not in the tree view.
Give a user only query-groups role from the realm-management client.
Go to Groups section.  See that the group names in the tree are not rendered as links and the kabab menu is hidden.
=> Make role restrictions on group tree match group table.

apps/admin-ui/src/realm-settings/EmailTab.tsx
Fixes #4420 
Warning message `To test the connection you must first configure an e-mail address for the current user (admin).` might be hidden if user does not scroll to the bottom.  This can lead the user to think that the SMTP `Test connection` button is improperly disabled.
1. In user section, remove email for current user.
2. See warning message now appears above `Test connection` button instead of below it.
=> Move smtp warning so it will be seen without scrolling.

apps/admin-ui/public/resources/en/authentication-help.json, apps/admin-ui/src/authentication/RequiredActions.tsx, apps/admin-ui/src/authentication/components/DraggableTable.tsx
This commit adds a new column field called `thTooltipText` to the `DraggableTable` component, which allows users to add a tooltip next to the column name in the `th` of the table.
There used to be a tooltip text next to "Default Action" text on the "Authentication" view. This PR adds it back in.
This PR adds a new optional column field called `thTooltipText` to the DraggableTable component. With this field, a tooltip text can be provided like this:
```jsx
<DraggableTable
columns={[
{
name: "default",
displayKey: "authentication:setAsDefaultAction",
thTooltipText: "authentication-help:authDefaultActionTooltip"
}
]}
>
</DraggableTable>
```
Before
After
=> Add thTooltipText prop to DraggableTable component

.github/workflows/cypress.yml
There was some issues running Cypress tests for release/21.0:
It was using github.ref for the repository, rather than for ref, when checking out Keycloak sources.
This is a "forward port" from fixing it in `release/21.0` branch:
https://github.com/keycloak/keycloak-ui/commit/21000a73098dbab70ec73d91d2905113dfd4b64f
=> Fix checkout of Keycloak server for release branches

apps/admin-ui/cypress/e2e/events_test.spec.ts, apps/admin-ui/cypress/support/pages/admin-ui/manage/realm_settings/tabs/realmsettings_events_subtabs/AdminEventsSettingsTab.ts
now creates a new realm to change the setting.
That way on failure it can retry
=> made the admin events test repeatable

apps/admin-ui/src/clients/advanced/OpenIdConnectCompatibilityModes.tsx
Fixes #4451 
Role restriction should be `manage-clients` and not `manage-realm`
See #4451
=> Fix role restriction for OIDC Compatibility Modes

apps/admin-ui/src/clients/keys/Certificate.tsx
Replaces PatternFly's `GenerateId` component with the new [`useId()` hook](https://beta.reactjs.org/reference/react/useId) from React.
=> Replace `GenerateId` component with React's `useId()` hook

apps/admin-ui/src/clients/advanced/AdvancedSettings.tsx
Closes #4545 
Wrong client attribute `tls-client-certificate-bound-access-tokens` was used by the admin UI instead of `tls.client.certificate.bound.access.tokens` which caused holder-of-key-token to no longer be supported.
See #4545 reproduction steps which contains a correct realm/client to test the fix.
- ~User-visible strings are using the react-i18next framework (useTranslation)~
- ~Help has been implemented~
- ~Axe check has been run and resulting a11y issues have been resolved~
- ~Manual keyboard and screen reader checks have been run and resulting a11y issues have been resolved~
- ~Unit tests have been created/updated~
This fix send the correct client attribute to the backend
```json
"attributes" : {
"oidc.ciba.grant.enabled" : "false",
"client.secret.creation.time" : "1675974958", …
```
=> Fix client certificate bound access token toggle
